name = "Percolation"
version = "0.1.0"
keywords = ["math", "probability", "percolation", "statistical-mechanics"]
defaultTargets = ["Percolation"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "Percolation"
globs = ["Percolation.+"]
