import Percolation.Bernoulli.FKG
import Mathlib.MeasureTheory.Measure.SeparableMeasure

/-!
# The FKG inequality for general increasing events (Theorem 2.4)

Source: Grimmett, *Percolation* (2nd ed., 1999), §2.2, Theorem (2.4)(b) and its
corollaries, pp. 34–36 (source id `grimmett-percolation-1999`).

The book removes the finite-support restriction with a martingale argument. Here we take an
equivalent approximation route with less machinery, recorded as a proof divergence on the
comparator card (the statements are unchanged, in fact slightly stronger — no countability
of the index is needed):

1. the finitely supported events form a set algebra generating the ambient σ-algebra
   (`measurableSpace_eq_generateFrom_finiteSupportEvents`), so by measure-density every
   measurable event is approximable in measure by finitely supported events;
2. coordinate blocks are independent under the product measure, giving the *splice
   factorization*: conditioning on the trace over a finite support `E` amounts to the
   splice map `spliceOn E s` (`setBernoulli_real_inter_finiteCylinder`,
   `setBernoulli_real_eq_sum_splice`);
3. the *slice probability* `sliceProbability E p A` — the probability of `A` given the
   trace on `E` — is a finitely supported, `[0,1]`-valued, increasing observable with
   `∫ sliceProbability = P(A)` (tower), `sliceProbability C = 1_C` for `C` supported on `E`
   (exactness), and an `L¹`-contraction in the event;
4. finite FKG applied to the slices plus an `ε`-approximation closes the general case
   `Percolation.setBernoulli_real_fkg`, with decreasing, mixed, iterated (2.7) and
   cubic-lattice (`Percolation.bernoulliBondMeasure_real_fkg`) corollaries.
-/

namespace Percolation

open MeasureTheory ProbabilityTheory MeasurableSpace
open scoped ENNReal unitInterval symmDiff

variable {ι : Type*}

/-! ### The algebra of finitely supported events generates the σ-algebra -/

/-- The events depending on finitely many coordinates. -/
def finiteSupportEvents (ι : Type*) : Set (Set (Set ι)) :=
  {A | ∃ E : Finset ι, DependsOn E A}

theorem isSetAlgebra_finiteSupportEvents :
    IsSetAlgebra (finiteSupportEvents ι) := by
  classical
  refine ⟨⟨∅, dependsOn_empty_event ∅⟩, ?_, ?_⟩
  · rintro A ⟨E, hA⟩
    exact ⟨E, hA.compl⟩
  · rintro A B ⟨E, hA⟩ ⟨F, hB⟩
    exact ⟨E ∪ F, (hA.mono Finset.subset_union_left).union
      (hB.mono Finset.subset_union_right)⟩

/-- The ambient σ-algebra of the configuration space is contained in the σ-algebra
generated by the finitely supported events. -/
theorem le_generateFrom_finiteSupportEvents :
    (inferInstance : MeasurableSpace (Set ι)) ≤
      MeasurableSpace.generateFrom (finiteSupportEvents ι) := by
  have h : (inferInstance : MeasurableSpace (Set ι)) =
      ⨆ e : ι, MeasurableSpace.comap (fun ω : Set ι => e ∈ ω) inferInstance := rfl
  rw [h]
  refine iSup_le fun e => ?_
  intro s hs
  obtain ⟨S, -, rfl⟩ := hs
  refine MeasurableSpace.measurableSet_generateFrom ⟨{e}, ?_⟩
  intro ω η hagree
  have he : (e ∈ ω) = (e ∈ η) := propext (hagree e (Finset.mem_singleton_self e))
  show (e ∈ ω : Prop) ∈ S ↔ (e ∈ η : Prop) ∈ S
  rw [he]

/-- The ambient σ-algebra of the configuration space is generated by the finitely
supported events. -/
theorem measurableSpace_eq_generateFrom_finiteSupportEvents :
    (inferInstance : MeasurableSpace (Set ι)) =
      MeasurableSpace.generateFrom (finiteSupportEvents ι) := by
  refine le_antisymm le_generateFrom_finiteSupportEvents
    (MeasurableSpace.generateFrom_le ?_)
  rintro A ⟨E, hA⟩
  exact hA.measurableSet

/-- Finitely supported events approximate every measurable event in measure. -/
theorem exists_dependsOn_measureReal_symmDiff_lt (μ : Measure (Set ι))
    [IsProbabilityMeasure μ] {A : Set (Set ι)} (hA : MeasurableSet A) {ε : ℝ}
    (hε : 0 < ε) :
    ∃ (E : Finset ι) (C : Set (Set ι)), DependsOn E C ∧ μ.real (A ∆ C) < ε := by
  have hdense : μ.MeasureDense (finiteSupportEvents ι) :=
    Measure.MeasureDense.of_generateFrom_isSetAlgebra_finite (μ := μ)
      isSetAlgebra_finiteSupportEvents measurableSpace_eq_generateFrom_finiteSupportEvents
  obtain ⟨C, ⟨E, hC⟩, hlt⟩ := hdense.approx A hA (measure_ne_top μ A) ε hε
  refine ⟨E, C, hC, ?_⟩
  rw [measureReal_def]
  exact ENNReal.toReal_lt_of_lt_ofReal hlt

/-! ### Independence of disjoint coordinate blocks -/

/-- The coordinate events indexed by a set of coordinates. -/
def coordinateEvents (S : Set ι) : Set (Set (Set ι)) :=
  {C | ∃ e ∈ S, {ω : Set ι | e ∈ ω} = C}

theorem measurableSet_coordinateEvent (e : ι) :
    MeasurableSet {ω : Set ι | e ∈ ω} := by
  classical
  have h : {ω : Set ι | e ∈ ω} = {ω : Set ι | (({e} : Finset ι) : Set ι) ⊆ ω} := by
    ext ω
    simp
  rw [h]
  exact measurableSet_superset_finset {e}

theorem generateFrom_coordinateEvents_le (S : Set ι) :
    MeasurableSpace.generateFrom (coordinateEvents S) ≤
      (inferInstance : MeasurableSpace (Set ι)) := by
  refine MeasurableSpace.generateFrom_le ?_
  rintro C ⟨e, _, rfl⟩
  exact measurableSet_coordinateEvent e

/-- Disjoint coordinate blocks generate independent σ-algebras under the Bernoulli
product measure. -/
theorem indep_generateFrom_coordinateEvents (p : I) {S T : Set ι} (hST : Disjoint S T) :
    Indep (MeasurableSpace.generateFrom (coordinateEvents S))
      (MeasurableSpace.generateFrom (coordinateEvents T))
      setBer((Set.univ : Set ι), p) := by
  classical
  exact ProbabilityTheory.iIndepSet.indep_generateFrom_of_disjoint
    (fun e => measurableSet_coordinateEvent e)
    (setBernoulli_iIndepSet_mem_univ p) S T hST

/-- A cylinder over `E` is measurable for the coordinate block containing `E`. -/
theorem measurableSet_finiteCylinder_generateFrom {E s : Finset ι} {S : Set ι}
    (hES : (E : Set ι) ⊆ S) (hs : s ⊆ E) :
    MeasurableSet[MeasurableSpace.generateFrom (coordinateEvents S)]
      (finiteCylinder E s) := by
  classical
  have hrepr : finiteCylinder E s =
      (⋂ e ∈ s, {ω : Set ι | e ∈ ω}) ∩ (⋂ e ∈ E \ s, {ω : Set ι | e ∈ ω}ᶜ) := by
    ext ω
    simp only [mem_finiteCylinder, Set.mem_inter_iff, Set.mem_iInter, Set.mem_compl_iff,
      Set.mem_setOf_eq, Finset.mem_sdiff]
    constructor
    · intro h
      exact ⟨fun e he => (h e (hs he)).mpr he,
        fun e he => fun hω => he.2 ((h e he.1).mp hω)⟩
    · rintro ⟨hin, hout⟩ e he
      constructor
      · intro hω
        by_contra hes
        exact hout e ⟨he, hes⟩ hω
      · intro hes
        exact hin e hes
  rw [hrepr]
  refine MeasurableSet.inter ?_ ?_
  · refine Finset.measurableSet_biInter _ fun e he =>
      MeasurableSpace.measurableSet_generateFrom ?_
    exact ⟨e, hES (hs he), rfl⟩
  · refine Finset.measurableSet_biInter _ fun e he =>
      MeasurableSet.compl (MeasurableSpace.measurableSet_generateFrom ?_)
    exact ⟨e, hES (Finset.mem_sdiff.mp he).1, rfl⟩

/-- An event supported on `F` is measurable for any coordinate block containing `F`. -/
theorem DependsOn.measurableSet_generateFrom_coordinateEvents {F : Finset ι} {S : Set ι}
    (hFS : (F : Set ι) ⊆ S) {A : Set (Set ι)} (hA : DependsOn F A) :
    MeasurableSet[MeasurableSpace.generateFrom (coordinateEvents S)] A := by
  classical
  have hrepr : A = ⋃ s ∈ F.powerset.filter (fun s : Finset ι => (↑s : Set ι) ∈ A),
      finiteCylinder F s := by
    ext ω
    rw [Set.mem_iUnion₂]
    constructor
    · intro hω
      exact ⟨restrictTo F ω,
        Finset.mem_filter.mpr ⟨Finset.mem_powerset.mpr (restrictTo_subset F ω),
          (hA.mem_iff_restrictTo_mem ω).mp hω⟩,
        mem_finiteCylinder_restrictTo F ω⟩
    · rintro ⟨s, hs, hω⟩
      exact (hA fun e he => hω e he).mpr (Finset.mem_filter.mp hs).2
  rw [hrepr]
  exact (F.powerset.filter _).measurableSet_biUnion fun s hs =>
    measurableSet_finiteCylinder_generateFrom hFS
      (Finset.mem_powerset.mp (Finset.mem_filter.mp hs).1)

/-- The splice preimage of an event supported on `F` is supported on `F \ E`. -/
theorem DependsOn.dependsOn_preimage_spliceOn [DecidableEq ι] {E s F : Finset ι}
    (hs : s ⊆ E) {A : Set (Set ι)} (hA : DependsOn F A) :
    DependsOn (F \ E) ((fun ω => spliceOn E s ω) ⁻¹' A) := by
  intro ω η hagree
  refine hA fun e he => ?_
  by_cases heE : e ∈ E
  · rw [mem_spliceOn_of_mem heE, mem_spliceOn_of_mem heE]
  · rw [mem_spliceOn_of_notMem hs heE, mem_spliceOn_of_notMem hs heE]
    exact hagree e (Finset.mem_sdiff.mpr ⟨he, heE⟩)

/-- The splice map is measurable from the complementary coordinate block. -/
theorem measurable_spliceOn_generateFrom {E s : Finset ι} (hs : s ⊆ E) :
    @Measurable (Set ι) (Set ι)
      (MeasurableSpace.generateFrom (coordinateEvents ((E : Set ι)ᶜ))) _
      (fun ω => spliceOn E s ω) := by
  classical
  have h : @Measurable (Set ι) (Set ι)
      (MeasurableSpace.generateFrom (coordinateEvents ((E : Set ι)ᶜ)))
      (MeasurableSpace.generateFrom (finiteSupportEvents ι))
      (fun ω => spliceOn E s ω) := by
    refine @measurable_generateFrom _ _
      (MeasurableSpace.generateFrom (coordinateEvents ((E : Set ι)ᶜ))) _ _ ?_
    rintro A ⟨F, hA⟩
    refine (hA.dependsOn_preimage_spliceOn
      hs).measurableSet_generateFrom_coordinateEvents ?_
    intro e he
    have hmem := Finset.mem_sdiff.mp (by simpa using he)
    simpa using hmem.2
  intro t ht
  exact h (le_generateFrom_finiteSupportEvents (ι := ι) t ht)

/-- On the cylinder prescribing the trace `s`, the splice is the identity. -/
theorem spliceOn_eq_self_of_mem_finiteCylinder {E s : Finset ι} (hs : s ⊆ E) {ω : Set ι}
    (hω : ω ∈ finiteCylinder E s) : spliceOn E s ω = ω := by
  ext e
  by_cases heE : e ∈ E
  · rw [mem_spliceOn_of_mem heE]
    exact (hω e heE).symm
  · rw [mem_spliceOn_of_notMem hs heE]

/-- **Splice factorization**: the measure of an event intersected with a trace cylinder
factorizes into the spliced event and the cylinder weight. This is the finite-support
conditioning identity behind Grimmett's induction. -/
theorem setBernoulli_real_inter_finiteCylinder (p : I) {E s : Finset ι} (hs : s ⊆ E)
    {A : Set (Set ι)} (hAm : MeasurableSet A) :
    setBer((Set.univ : Set ι), p).real (A ∩ finiteCylinder E s) =
      setBer((Set.univ : Set ι), p).real ((fun ω => spliceOn E s ω) ⁻¹' A) *
        finiteBernoulliWeight E (p : ℝ) s := by
  classical
  have hsplice_id : A ∩ finiteCylinder E s =
      ((fun ω => spliceOn E s ω) ⁻¹' A) ∩ finiteCylinder E s := by
    ext ω
    constructor
    · rintro ⟨hA', hcyl⟩
      exact ⟨by rwa [Set.mem_preimage, spliceOn_eq_self_of_mem_finiteCylinder hs hcyl],
        hcyl⟩
    · rintro ⟨hA', hcyl⟩
      rw [Set.mem_preimage, spliceOn_eq_self_of_mem_finiteCylinder hs hcyl] at hA'
      exact ⟨hA', hcyl⟩
  rw [hsplice_id]
  have hindep := indep_generateFrom_coordinateEvents p
    (S := ((E : Set ι))ᶜ) (T := (E : Set ι)) disjoint_compl_left
  have hX : MeasurableSet[MeasurableSpace.generateFrom (coordinateEvents ((E : Set ι)ᶜ))]
      ((fun ω => spliceOn E s ω) ⁻¹' A) :=
    measurable_spliceOn_generateFrom hs hAm
  have hY : MeasurableSet[MeasurableSpace.generateFrom (coordinateEvents (E : Set ι))]
      (finiteCylinder E s) :=
    measurableSet_finiteCylinder_generateFrom subset_rfl hs
  have hXm : MeasurableSet ((fun ω => spliceOn E s ω) ⁻¹' A) :=
    generateFrom_coordinateEvents_le _ _ hX
  have hYm : MeasurableSet (finiteCylinder E s) := measurableSet_finiteCylinder hs
  have hprod := (ProbabilityTheory.indepSet_iff_measure_inter_eq_mul hXm hYm
    (setBer((Set.univ : Set ι), p))).mp (hindep.indepSet_of_measurableSet hX hY)
  rw [measureReal_def, hprod, ENNReal.toReal_mul, ← measureReal_def, ← measureReal_def,
    setBernoulli_real_finiteCylinder hs p]

/-- **Splice decomposition** of the measure of an event over the traces of a finite
support (the tower identity over the cylinder partition). -/
theorem setBernoulli_real_eq_sum_splice (p : I) (E : Finset ι) {A : Set (Set ι)}
    (hAm : MeasurableSet A) :
    setBer((Set.univ : Set ι), p).real A =
      ∑ s ∈ E.powerset, finiteBernoulliWeight E (p : ℝ) s *
        setBer((Set.univ : Set ι), p).real ((fun ω => spliceOn E s ω) ⁻¹' A) := by
  classical
  have hcover : A = ⋃ s ∈ E.powerset, A ∩ finiteCylinder E s := by
    ext ω
    rw [Set.mem_iUnion₂]
    constructor
    · intro hω
      exact ⟨restrictTo E ω, Finset.mem_powerset.mpr (restrictTo_subset E ω),
        hω, mem_finiteCylinder_restrictTo E ω⟩
    · rintro ⟨s, _, hω, _⟩
      exact hω
  have hdisj : Set.PairwiseDisjoint (↑E.powerset : Set (Finset ι))
      (fun s => A ∩ finiteCylinder E s) :=
    (pairwiseDisjoint_finiteCylinder E).mono fun s => Set.inter_subset_right
  have hsum : setBer((Set.univ : Set ι), p).real A =
      ∑ s ∈ E.powerset, setBer((Set.univ : Set ι), p).real (A ∩ finiteCylinder E s) := by
    conv_lhs => rw [hcover]
    exact measureReal_biUnion_finset hdisj fun s hs =>
      hAm.inter (measurableSet_finiteCylinder (Finset.mem_powerset.mp hs))
  rw [hsum]
  refine Finset.sum_congr rfl fun s hs => ?_
  rw [setBernoulli_real_inter_finiteCylinder p (Finset.mem_powerset.mp hs) hAm, mul_comm]

/-! ### The slice probability -/

/-- The probability of `A` given the trace of `ω` on the finite support `E`: freeze the
`E`-coordinates of `ω` and average over the others. This is the conditional probability
`P_p(A ∣ ω(e), e ∈ E)` of Grimmett's proof, realized by the splice map. -/
noncomputable def sliceProbability (E : Finset ι) (p : I) (A : Set (Set ι)) (ω : Set ι) :
    ℝ :=
  setBer((Set.univ : Set ι), p).real ((fun η => spliceOn E (restrictTo E ω) η) ⁻¹' A)

theorem sliceProbability_dependsOnFun (E : Finset ι) (p : I) (A : Set (Set ι)) :
    DependsOnFun E (sliceProbability E p A) := by
  intro ω η hagree
  have hres : restrictTo E ω = restrictTo E η := by
    ext e
    rw [mem_restrictTo, mem_restrictTo]
    constructor
    · rintro ⟨heE, heω⟩
      exact ⟨heE, (hagree e heE).mp heω⟩
    · rintro ⟨heE, heη⟩
      exact ⟨heE, (hagree e heE).mpr heη⟩
  rw [sliceProbability, sliceProbability, hres]

theorem sliceProbability_nonneg (E : Finset ι) (p : I) (A : Set (Set ι)) (ω : Set ι) :
    0 ≤ sliceProbability E p A ω :=
  measureReal_nonneg

theorem sliceProbability_le_one (E : Finset ι) (p : I) (A : Set (Set ι)) (ω : Set ι) :
    sliceProbability E p A ω ≤ 1 := by
  rw [sliceProbability, ← probReal_univ (μ := setBer((Set.univ : Set ι), p))]
  exact measureReal_mono (Set.subset_univ _)

/-- The slice probability of an increasing event is an increasing observable. -/
theorem IsIncreasingEvent.isIncreasingRandomVariable_sliceProbability {A : Set (Set ι)}
    (hA : IsIncreasingEvent A) (E : Finset ι) (p : I) :
    IsIncreasingRandomVariable (sliceProbability E p A) := by
  intro ω η hωη
  refine measureReal_mono (fun ζ hζ => ?_)
  rw [Set.mem_preimage] at hζ ⊢
  refine hA (spliceOn_mono_left (restrictTo_mono hωη) ζ) hζ

/-- **Exactness**: on an event supported inside `E`, the slice probability is the
indicator. -/
theorem DependsOn.sliceProbability_eq_indicator {E F : Finset ι} {C : Set (Set ι)}
    (hC : DependsOn F C) (hFE : F ⊆ E) (p : I) (ω : Set ι) :
    sliceProbability E p C ω = C.indicator (fun _ => 1) ω := by
  have hC' : DependsOn E C := hC.mono hFE
  have hmem : ∀ η : Set ι, spliceOn E (restrictTo E ω) η ∈ C ↔ ω ∈ C := by
    intro η
    refine hC' fun e he => ?_
    rw [mem_spliceOn_of_mem he, mem_restrictTo]
    simp [he]
  by_cases hω : ω ∈ C
  · have : (fun η => spliceOn E (restrictTo E ω) η) ⁻¹' C = Set.univ :=
      Set.eq_univ_of_forall fun η => (hmem η).mpr hω
    rw [sliceProbability, this, probReal_univ, Set.indicator_of_mem hω]
  · have : (fun η => spliceOn E (restrictTo E ω) η) ⁻¹' C = ∅ := by
      ext η
      simp only [Set.mem_preimage, Set.mem_empty_iff_false, iff_false]
      exact fun hη => hω ((hmem η).mp hη)
    rw [sliceProbability, this, measureReal_empty, Set.indicator_of_notMem hω]

/-- Probabilities of two events differ by at most the probability of their symmetric
difference. -/
theorem setBernoulli_real_sub_le_symmDiff (p : I) (U V : Set (Set ι)) :
    setBer((Set.univ : Set ι), p).real U - setBer((Set.univ : Set ι), p).real V ≤
      setBer((Set.univ : Set ι), p).real (U ∆ V) := by
  have hsub : U ⊆ V ∪ (U ∆ V) := by
    intro ζ hζ
    by_cases hζV : ζ ∈ V
    · exact Or.inl hζV
    · exact Or.inr (Set.mem_symmDiff.mpr (Or.inl ⟨hζ, hζV⟩))
  have h1 : setBer((Set.univ : Set ι), p).real U ≤
      setBer((Set.univ : Set ι), p).real (V ∪ U ∆ V) :=
    measureReal_mono hsub
  have h2 : setBer((Set.univ : Set ι), p).real (V ∪ U ∆ V) ≤
      setBer((Set.univ : Set ι), p).real V +
        setBer((Set.univ : Set ι), p).real (U ∆ V) :=
    measureReal_union_le V (U ∆ V)
  linarith

/-- **`L¹`-contraction**, pointwise form: slice probabilities of two events differ by at
most the slice probability of the symmetric difference. -/
theorem abs_sliceProbability_sub_le (E : Finset ι) (p : I) (A B : Set (Set ι))
    (ω : Set ι) :
    |sliceProbability E p A ω - sliceProbability E p B ω| ≤
      sliceProbability E p (A ∆ B) ω := by
  have hpre : (fun η => spliceOn E (restrictTo E ω) η) ⁻¹' (A ∆ B) =
      ((fun η => spliceOn E (restrictTo E ω) η) ⁻¹' A) ∆
        ((fun η => spliceOn E (restrictTo E ω) η) ⁻¹' B) := by
    simp [Set.symmDiff_def]
  show |setBer((Set.univ : Set ι), p).real ((fun η => spliceOn E (restrictTo E ω) η) ⁻¹' A) -
      setBer((Set.univ : Set ι), p).real ((fun η => spliceOn E (restrictTo E ω) η) ⁻¹' B)| ≤
    setBer((Set.univ : Set ι), p).real ((fun η => spliceOn E (restrictTo E ω) η) ⁻¹' (A ∆ B))
  rw [hpre, abs_sub_le_iff]
  refine ⟨setBernoulli_real_sub_le_symmDiff p _ _, ?_⟩
  have h := setBernoulli_real_sub_le_symmDiff p
    ((fun η => spliceOn E (restrictTo E ω) η) ⁻¹' B)
    ((fun η => spliceOn E (restrictTo E ω) η) ⁻¹' A)
  rwa [symmDiff_comm] at h

/-- **Tower identity**: the slice probability integrates to the probability. -/
theorem integral_sliceProbability (E : Finset ι) (p : I) {A : Set (Set ι)}
    (hAm : MeasurableSet A) :
    ∫ ω, sliceProbability E p A ω ∂ setBer((Set.univ : Set ι), p) =
      setBer((Set.univ : Set ι), p).real A := by
  classical
  rw [(sliceProbability_dependsOnFun E p A).integral_setBernoulli p,
    setBernoulli_real_eq_sum_splice p E hAm]
  refine Finset.sum_congr rfl fun s hs => ?_
  show finiteBernoulliWeight E (p : ℝ) s * sliceProbability E p A (↑s : Set ι) =
    finiteBernoulliWeight E (p : ℝ) s *
      setBer((Set.univ : Set ι), p).real ((fun ω => spliceOn E s ω) ⁻¹' A)
  rw [sliceProbability, restrictTo_coe E s (Finset.mem_powerset.mp hs)]

/-! ### The general FKG inequality -/

/-- Bounded finitely supported observables are measurable. -/
theorem DependsOnFun.measurable {E : Finset ι} {X : Set ι → ℝ} (hX : DependsOnFun E X) :
    Measurable X := by
  classical
  have hrepr : X = fun ω => ∑ s ∈ E.powerset,
      (finiteCylinder E s).indicator (fun _ => X (↑s : Set ι)) ω :=
    funext fun ω => hX.eq_sum_indicator_finiteCylinder ω
  rw [hrepr]
  exact Finset.measurable_sum _ fun s hs =>
    measurable_const.indicator (measurableSet_finiteCylinder (Finset.mem_powerset.mp hs))

/-- Bounded measurable functions on the probability space are integrable. -/
theorem integrable_of_bounded_measurable {μ : Measure (Set ι)} [IsProbabilityMeasure μ]
    {X : Set ι → ℝ} (hX : Measurable X) {C : ℝ} (hC : ∀ ω, |X ω| ≤ C) :
    Integrable X μ :=
  (integrable_const C).mono' hX.aestronglyMeasurable (ae_of_all _ fun ω => by
    simpa [Real.norm_eq_abs] using hC ω)

/-- **The FKG inequality** (Grimmett Theorem (2.4b)) for arbitrary increasing measurable
events of the Bernoulli product measure. -/
theorem setBernoulli_real_fkg (p : I) {A B : Set (Set ι)}
    (hAinc : IsIncreasingEvent A) (hBinc : IsIncreasingEvent B)
    (hAm : MeasurableSet A) (hBm : MeasurableSet B) :
    setBer((Set.univ : Set ι), p).real A * setBer((Set.univ : Set ι), p).real B ≤
      setBer((Set.univ : Set ι), p).real (A ∩ B) := by
  classical
  set μ := setBer((Set.univ : Set ι), p) with hμ
  refine le_of_forall_pos_le_add fun ε hε => ?_
  obtain ⟨EA, CA, hCA, hA_approx⟩ :=
    exists_dependsOn_measureReal_symmDiff_lt μ hAm (by positivity : (0:ℝ) < ε / 4)
  obtain ⟨EB, CB, hCB, hB_approx⟩ :=
    exists_dependsOn_measureReal_symmDiff_lt μ hBm (by positivity : (0:ℝ) < ε / 4)
  set E := EA ∪ EB with hE
  set f := sliceProbability E p A with hf
  set g := sliceProbability E p B with hg
  have hfd : DependsOnFun E f := sliceProbability_dependsOnFun E p A
  have hgd : DependsOnFun E g := sliceProbability_dependsOnFun E p B
  have hf0 : ∀ ω, 0 ≤ f ω := sliceProbability_nonneg E p A
  have hf1 : ∀ ω, f ω ≤ 1 := sliceProbability_le_one E p A
  have hg0 : ∀ ω, 0 ≤ g ω := sliceProbability_nonneg E p B
  have hg1 : ∀ ω, g ω ≤ 1 := sliceProbability_le_one E p B
  -- Step 1: `μ(A)μ(B) = (∫f)(∫g) ≤ ∫ fg` by finite FKG on the slices.
  have hproduct : DependsOnFun E (fun ω => f ω * g ω) := fun ω η h => by
    show f ω * g ω = f η * g η
    rw [hfd h, hgd h]
  have hstep1 : μ.real A * μ.real B ≤ ∫ ω, f ω * g ω ∂μ := by
    rw [← integral_sliceProbability E p hAm, ← integral_sliceProbability E p hBm]
    rw [hfd.integral_setBernoulli p, hgd.integral_setBernoulli p,
      hproduct.integral_setBernoulli p]
    exact finiteBernoulliExpectation_mul_fkg_of_monotone p.2.1 p.2.2
      (fun s t hst _ =>
        (hAinc.isIncreasingRandomVariable_sliceProbability E p)
          (Finset.coe_subset.mpr hst))
      (fun s t hst _ =>
        (hBinc.isIncreasingRandomVariable_sliceProbability E p)
          (Finset.coe_subset.mpr hst))
  -- Integrability of everything in sight.
  have hCAm : MeasurableSet CA := hCA.measurableSet
  have hCBm : MeasurableSet CB := hCB.measurableSet
  have hfm : Measurable f := hfd.measurable
  have hgm : Measurable g := hgd.measurable
  have h1A : Measurable (A.indicator fun _ => (1 : ℝ)) :=
    measurable_const.indicator hAm
  have h1B : Measurable (B.indicator fun _ => (1 : ℝ)) :=
    measurable_const.indicator hBm
  have hind_bound : ∀ (S : Set (Set ι)) (ω : Set ι),
      |S.indicator (fun _ => (1 : ℝ)) ω| ≤ 1 := by
    intro S ω
    by_cases hω : ω ∈ S <;> simp [hω]
  -- Step 2: `∫|slice X − 1_X| ≤ 2 μ(X ∆ CX)` for `X ∈ {A, B}`.
  have hslice_diff : ∀ (X : Set (Set ι)) (EX : Finset ι) (CX : Set (Set ι)),
      DependsOn EX CX → EX ⊆ E → MeasurableSet X → MeasurableSet CX →
      ∫ ω, |sliceProbability E p X ω - X.indicator (fun _ => 1) ω| ∂μ ≤
        2 * μ.real (X ∆ CX) := by
    intro X EX CX hCX hEXE hXm hCXm
    have hXCm : MeasurableSet (X ∆ CX) := hXm.symmDiff hCXm
    have hslice_meas : Measurable (sliceProbability E p X) :=
      (sliceProbability_dependsOnFun E p X).measurable
    have h1X : Measurable (X.indicator fun _ => (1 : ℝ)) :=
      measurable_const.indicator hXm
    have hint1 : Integrable (fun ω => |sliceProbability E p X ω -
        X.indicator (fun _ => 1) ω|) μ := by
      refine Integrable.abs (integrable_of_bounded_measurable (hslice_meas.sub h1X)
        (C := 2) ?_)
      intro ω
      have hb := hind_bound X ω
      have h0 := sliceProbability_nonneg E p X ω
      have h1 := sliceProbability_le_one E p X ω
      rw [abs_sub_le_iff]
      constructor <;> nlinarith [le_abs_self (X.indicator (fun _ => (1:ℝ)) ω),
        neg_abs_le (X.indicator (fun _ => (1:ℝ)) ω)]
    have hpoint : ∀ ω, |sliceProbability E p X ω - X.indicator (fun _ => 1) ω| ≤
        sliceProbability E p (X ∆ CX) ω + (X ∆ CX).indicator (fun _ => 1) ω := by
      intro ω
      have htri : |sliceProbability E p X ω - X.indicator (fun _ => 1) ω| ≤
          |sliceProbability E p X ω - sliceProbability E p CX ω| +
            |sliceProbability E p CX ω - X.indicator (fun _ => 1) ω| :=
        abs_sub_le _ _ _
      have hcontr := abs_sliceProbability_sub_le E p X CX ω
      have hexact := hCX.sliceProbability_eq_indicator hEXE p ω
      have hindic : |sliceProbability E p CX ω - X.indicator (fun _ => 1) ω| =
          (X ∆ CX).indicator (fun _ => 1) ω := by
        rw [hexact]
        by_cases hωX : ω ∈ X <;> by_cases hωC : ω ∈ CX <;>
          simp [hωX, hωC, Set.mem_symmDiff]
      rw [hindic] at htri
      exact htri.trans (add_le_add hcontr le_rfl)
    have hint_slice : Integrable (fun ω => sliceProbability E p (X ∆ CX) ω) μ := by
      refine integrable_of_bounded_measurable
        ((sliceProbability_dependsOnFun E p (X ∆ CX)).measurable) (C := 1) ?_
      intro ω
      rw [abs_of_nonneg (sliceProbability_nonneg E p (X ∆ CX) ω)]
      exact sliceProbability_le_one E p (X ∆ CX) ω
    have hint_ind : Integrable ((X ∆ CX).indicator fun _ => (1 : ℝ)) μ :=
      integrable_of_bounded_measurable (measurable_const.indicator hXCm)
        (hind_bound (X ∆ CX))
    calc ∫ ω, |sliceProbability E p X ω - X.indicator (fun _ => 1) ω| ∂μ
        ≤ ∫ ω, (sliceProbability E p (X ∆ CX) ω +
            (X ∆ CX).indicator (fun _ => 1) ω) ∂μ :=
          integral_mono hint1 (hint_slice.add hint_ind) hpoint
      _ = ∫ ω, sliceProbability E p (X ∆ CX) ω ∂μ +
            ∫ ω, (X ∆ CX).indicator (fun _ => 1) ω ∂μ :=
          integral_add hint_slice hint_ind
      _ = 2 * μ.real (X ∆ CX) := by
          rw [integral_sliceProbability E p hXCm, integral_indicator_const (1 : ℝ) hXCm,
            smul_eq_mul, mul_one]
          ring
  -- Step 3: pointwise `f · g ≤ 1_{A∩B} + |f − 1_A| + |g − 1_B|`, then integrate.
  have hpoint2 : ∀ ω, f ω * g ω ≤ (A ∩ B).indicator (fun _ => 1) ω +
      (|f ω - A.indicator (fun _ => 1) ω| + |g ω - B.indicator (fun _ => 1) ω|) := by
    intro ω
    set a := A.indicator (fun _ => (1 : ℝ)) ω with ha
    set b := B.indicator (fun _ => (1 : ℝ)) ω with hb
    have hABind : (A ∩ B).indicator (fun _ => (1 : ℝ)) ω = a * b := by
      by_cases hA' : ω ∈ A <;> by_cases hB' : ω ∈ B <;>
        simp [ha, hb, hA', hB', Set.mem_inter_iff]
    have hb0 : 0 ≤ b := Set.indicator_apply_nonneg fun _ => zero_le_one
    have hb1 : b ≤ 1 := Set.indicator_apply_le' (fun _ => le_refl 1) fun _ => zero_le_one
    have h1 : f ω * (g ω - b) ≤ |g ω - b| := by
      calc f ω * (g ω - b) ≤ |f ω * (g ω - b)| := le_abs_self _
        _ = |f ω| * |g ω - b| := abs_mul _ _
        _ ≤ 1 * |g ω - b| := by
            refine mul_le_mul_of_nonneg_right ?_ (abs_nonneg _)
            rw [abs_of_nonneg (hf0 ω)]
            exact hf1 ω
        _ = |g ω - b| := one_mul _
    have h2 : b * (f ω - a) ≤ |f ω - a| := by
      calc b * (f ω - a) ≤ |b * (f ω - a)| := le_abs_self _
        _ = |b| * |f ω - a| := abs_mul _ _
        _ ≤ 1 * |f ω - a| := by
            refine mul_le_mul_of_nonneg_right ?_ (abs_nonneg _)
            rw [abs_of_nonneg hb0]
            exact hb1
        _ = |f ω - a| := one_mul _
    have hexpand : f ω * g ω = a * b + (f ω * (g ω - b) + b * (f ω - a)) := by ring
    rw [hABind]
    linarith
  -- Integrability of every integrand in sight.
  have habs_f : Integrable (fun ω => |f ω - A.indicator (fun _ => 1) ω|) μ := by
    refine Integrable.abs (integrable_of_bounded_measurable (hfm.sub h1A) (C := 2) ?_)
    intro ω
    have hb := hind_bound A ω
    rw [abs_sub_le_iff]
    constructor <;> nlinarith [le_abs_self (A.indicator (fun _ => (1:ℝ)) ω),
      neg_abs_le (A.indicator (fun _ => (1:ℝ)) ω), hf0 ω, hf1 ω]
  have habs_g : Integrable (fun ω => |g ω - B.indicator (fun _ => 1) ω|) μ := by
    refine Integrable.abs (integrable_of_bounded_measurable (hgm.sub h1B) (C := 2) ?_)
    intro ω
    have hb := hind_bound B ω
    rw [abs_sub_le_iff]
    constructor <;> nlinarith [le_abs_self (B.indicator (fun _ => (1:ℝ)) ω),
      neg_abs_le (B.indicator (fun _ => (1:ℝ)) ω), hg0 ω, hg1 ω]
  have h1AB : Integrable ((A ∩ B).indicator fun _ => (1 : ℝ)) μ :=
    integrable_of_bounded_measurable (measurable_const.indicator (hAm.inter hBm))
      (hind_bound (A ∩ B))
  have hfg_int : Integrable (fun ω => f ω * g ω) μ := by
    refine integrable_of_bounded_measurable (hfm.mul hgm) (C := 1) ?_
    intro ω
    rw [abs_of_nonneg (mul_nonneg (hf0 ω) (hg0 ω))]
    nlinarith [hf0 ω, hf1 ω, hg0 ω, hg1 ω]
  have hstep2 : ∫ ω, f ω * g ω ∂μ ≤ μ.real (A ∩ B) +
      (∫ ω, |f ω - A.indicator (fun _ => 1) ω| ∂μ +
        ∫ ω, |g ω - B.indicator (fun _ => 1) ω| ∂μ) := by
    have habs_fg : Integrable (fun ω => |f ω - A.indicator (fun _ => 1) ω| +
        |g ω - B.indicator (fun _ => 1) ω|) μ := habs_f.add habs_g
    have hRHS_int : Integrable (fun ω => (A ∩ B).indicator (fun _ => (1 : ℝ)) ω +
        (|f ω - A.indicator (fun _ => 1) ω| + |g ω - B.indicator (fun _ => 1) ω|)) μ :=
      h1AB.add habs_fg
    have hmono := integral_mono hfg_int hRHS_int hpoint2
    rw [integral_add h1AB habs_fg, integral_add habs_f habs_g,
      integral_indicator_const (1 : ℝ) (hAm.inter hBm), smul_eq_mul, mul_one] at hmono
    exact hmono
  -- Step 4: combine and let `ε → 0`.
  have hA_est := hslice_diff A EA CA hCA Finset.subset_union_left hAm hCA.measurableSet
  have hB_est := hslice_diff B EB CB hCB Finset.subset_union_right hBm hCB.measurableSet
  have := hstep1.trans (hstep2.trans (by linarith [hA_est, hB_est, hA_approx, hB_approx] :
    μ.real (A ∩ B) + (∫ ω, |f ω - A.indicator (fun _ => 1) ω| ∂μ +
      ∫ ω, |g ω - B.indicator (fun _ => 1) ω| ∂μ) ≤ μ.real (A ∩ B) + ε))
  exact this

/-- FKG for two arbitrary decreasing measurable events (Grimmett p. 34). -/
theorem setBernoulli_real_fkg_of_decreasing (p : I) {A B : Set (Set ι)}
    (hAdec : IsDecreasingEvent A) (hBdec : IsDecreasingEvent B)
    (hAm : MeasurableSet A) (hBm : MeasurableSet B) :
    setBer((Set.univ : Set ι), p).real A * setBer((Set.univ : Set ι), p).real B ≤
      setBer((Set.univ : Set ι), p).real (A ∩ B) := by
  have hfkg := setBernoulli_real_fkg p hAdec.compl hBdec.compl hAm.compl hBm.compl
  have hcAB : Aᶜ ∩ Bᶜ = (A ∪ B)ᶜ := (Set.compl_union A B).symm
  have hA' : setBer((Set.univ : Set ι), p).real Aᶜ =
      1 - setBer((Set.univ : Set ι), p).real A := by
    rw [measureReal_compl hAm, probReal_univ]
  have hB' : setBer((Set.univ : Set ι), p).real Bᶜ =
      1 - setBer((Set.univ : Set ι), p).real B := by
    rw [measureReal_compl hBm, probReal_univ]
  have hunion : setBer((Set.univ : Set ι), p).real (A ∪ B) +
      setBer((Set.univ : Set ι), p).real (A ∩ B) =
      setBer((Set.univ : Set ι), p).real A + setBer((Set.univ : Set ι), p).real B :=
    measureReal_union_add_inter₀ hBm.nullMeasurableSet
  have hcompl : setBer((Set.univ : Set ι), p).real (A ∪ B)ᶜ =
      1 - setBer((Set.univ : Set ι), p).real (A ∪ B) := by
    rw [measureReal_compl (hAm.union hBm), probReal_univ]
  rw [hcAB, hcompl, hA', hB'] at hfkg
  nlinarith [hfkg, hunion]

/-- Negative correlation of an arbitrary increasing and an arbitrary decreasing measurable
event (Grimmett p. 34). -/
theorem setBernoulli_real_le_mul_of_increasing_decreasing (p : I) {A B : Set (Set ι)}
    (hAinc : IsIncreasingEvent A) (hBdec : IsDecreasingEvent B)
    (hAm : MeasurableSet A) (hBm : MeasurableSet B) :
    setBer((Set.univ : Set ι), p).real (A ∩ B) ≤
      setBer((Set.univ : Set ι), p).real A * setBer((Set.univ : Set ι), p).real B := by
  have hfkg := setBernoulli_real_fkg p hAinc hBdec.compl hAm hBm.compl
  have hB' : setBer((Set.univ : Set ι), p).real Bᶜ =
      1 - setBer((Set.univ : Set ι), p).real B := by
    rw [measureReal_compl hBm, probReal_univ]
  have hsplit : setBer((Set.univ : Set ι), p).real (A ∩ B) +
      setBer((Set.univ : Set ι), p).real (A ∩ Bᶜ) =
      setBer((Set.univ : Set ι), p).real A := by
    rw [← measureReal_union (μ := setBer((Set.univ : Set ι), p))
        (Set.disjoint_left.mpr fun ω hω1 hω2 => hω2.2 hω1.2) (hAm.inter hBm.compl)]
    congr 1
    ext ω
    simp only [Set.mem_union, Set.mem_inter_iff, Set.mem_compl_iff]
    tauto
  rw [hB'] at hfkg
  nlinarith [hfkg, hsplit]

/-- **Iterated FKG** (Grimmett (2.7)) for arbitrary increasing measurable events. -/
theorem setBernoulli_prod_le_real_biInter_fkg' {κ : Type*} (p : I) {J : Finset κ}
    {A : κ → Set (Set ι)} (hAinc : ∀ i ∈ J, IsIncreasingEvent (A i))
    (hAm : ∀ i ∈ J, MeasurableSet (A i)) :
    ∏ i ∈ J, setBer((Set.univ : Set ι), p).real (A i) ≤
      setBer((Set.univ : Set ι), p).real (⋂ i ∈ J, A i) := by
  classical
  induction J using Finset.induction_on with
  | empty => simp
  | insert a J ha ih =>
    have hstep := setBernoulli_real_fkg p (hAinc a (Finset.mem_insert_self a J))
      (isIncreasingEvent_biInter fun i hi => hAinc i (Finset.mem_insert_of_mem hi))
      (hAm a (Finset.mem_insert_self a J))
      (Finset.measurableSet_biInter J fun i hi => hAm i (Finset.mem_insert_of_mem hi))
    rw [Finset.prod_insert ha]
    have hrest := ih (fun i hi => hAinc i (Finset.mem_insert_of_mem hi))
      (fun i hi => hAm i (Finset.mem_insert_of_mem hi))
    calc setBer((Set.univ : Set ι), p).real (A a) *
          ∏ i ∈ J, setBer((Set.univ : Set ι), p).real (A i)
        ≤ setBer((Set.univ : Set ι), p).real (A a) *
          setBer((Set.univ : Set ι), p).real (⋂ i ∈ J, A i) :=
          mul_le_mul_of_nonneg_left hrest measureReal_nonneg
      _ ≤ setBer((Set.univ : Set ι), p).real (A a ∩ ⋂ i ∈ J, A i) := hstep
      _ = setBer((Set.univ : Set ι), p).real (⋂ i ∈ insert a J, A i) := by
          rw [Finset.set_biInter_insert]

/-! ### Cubic lattice specializations -/

/-- **The FKG inequality on the cubic lattice** (Grimmett Theorem (2.4b)) for arbitrary
increasing measurable bond events. -/
theorem bernoulliBondMeasure_real_fkg {d : ℕ} (p : I) {A B : Set (EdgeConfiguration d)}
    (hAinc : IsIncreasingEvent A) (hBinc : IsIncreasingEvent B)
    (hAm : MeasurableSet A) (hBm : MeasurableSet B) :
    (bernoulliBondMeasure d p).real A * (bernoulliBondMeasure d p).real B ≤
      (bernoulliBondMeasure d p).real (A ∩ B) := by
  simpa [bernoulliBondMeasure] using setBernoulli_real_fkg p hAinc hBinc hAm hBm

/-- FKG on the cubic lattice for arbitrary decreasing measurable bond events. -/
theorem bernoulliBondMeasure_real_fkg_of_decreasing {d : ℕ} (p : I)
    {A B : Set (EdgeConfiguration d)}
    (hAdec : IsDecreasingEvent A) (hBdec : IsDecreasingEvent B)
    (hAm : MeasurableSet A) (hBm : MeasurableSet B) :
    (bernoulliBondMeasure d p).real A * (bernoulliBondMeasure d p).real B ≤
      (bernoulliBondMeasure d p).real (A ∩ B) := by
  simpa [bernoulliBondMeasure] using
    setBernoulli_real_fkg_of_decreasing p hAdec hBdec hAm hBm

/-- Iterated FKG (Grimmett (2.7)) on the cubic lattice for arbitrary increasing measurable
bond events. -/
theorem bernoulliBondMeasure_prod_le_real_biInter_fkg' {d : ℕ} {κ : Type*} (p : I)
    {J : Finset κ} {A : κ → Set (EdgeConfiguration d)}
    (hAinc : ∀ i ∈ J, IsIncreasingEvent (A i)) (hAm : ∀ i ∈ J, MeasurableSet (A i)) :
    ∏ i ∈ J, (bernoulliBondMeasure d p).real (A i) ≤
      (bernoulliBondMeasure d p).real (⋂ i ∈ J, A i) := by
  simpa [bernoulliBondMeasure] using setBernoulli_prod_le_real_biInter_fkg' p hAinc hAm

end Percolation
