import Percolation.Bernoulli.Coupling
import Percolation.Bernoulli.FKGInfinite
import Mathlib.Combinatorics.SimpleGraph.Diam

/-!
# Stochastic domination and finite-range dependence

The primary definition follows Grimmett (7.63): comparison of expectations of every bounded,
increasing, measurable real function on site configurations.  An event-level consequence is
provided for the block constructions.
-/

namespace Percolation

open MeasureTheory ProbabilityTheory
open scoped unitInterval

/-- A real function is bounded uniformly on its entire domain. -/
def IsBoundedRealFunction {X : Type*} (f : X → ℝ) : Prop :=
  ∃ C : ℝ, ∀ x, |f x| ≤ C

/-- Stochastic domination in the exact expectation formulation of Grimmett (7.63). -/
def StochasticallyDominates {ι : Type*}
    (μ ν : Measure (Set ι)) : Prop :=
  ∀ f : Set ι → ℝ, Measurable f → IsIncreasingRandomVariable f →
    IsBoundedRealFunction f → ∫ ω, f ω ∂ν ≤ ∫ ω, f ω ∂μ

theorem StochasticallyDominates.refl {ι : Type*} (μ : Measure (Set ι)) :
    StochasticallyDominates μ μ := by
  intro f _hf _hinc _hbdd
  exact le_rfl

theorem StochasticallyDominates.trans {ι : Type*} {μ ν ξ : Measure (Set ι)}
    (hμν : StochasticallyDominates μ ν) (hνξ : StochasticallyDominates ν ξ) :
    StochasticallyDominates μ ξ := by
  intro f hf hinc hbdd
  exact (hνξ f hf hinc hbdd).trans (hμν f hf hinc hbdd)

/-- The monotone uniform coupling gives the basic iid stochastic ordering.  Besides being useful
in block comparisons, this theorem is an executable sanity check that the orientation of
`StochasticallyDominates` agrees with Grimmett's convention. -/
theorem setBernoulli_stochasticallyDominates {ι : Type*} [Countable ι]
    {p q : I} (hpq : p ≤ q) :
    StochasticallyDominates setBer((Set.univ : Set ι), q)
      setBer((Set.univ : Set ι), p) := by
  intro f hf hinc hbdd
  obtain ⟨C, hC⟩ := hbdd
  exact hinc.setBernoulli_integral_mono hf hpq
    (integrable_of_bounded_measurable hf hC)
    (integrable_of_bounded_measurable hf hC)

/-- Stochastic domination compares every increasing measurable event. -/
theorem StochasticallyDominates.measureReal_le {ι : Type*}
    {μ ν : Measure (Set ι)} (h : StochasticallyDominates μ ν)
    {A : Set (Set ι)} (hAm : MeasurableSet A) (hA : IsIncreasingEvent A) :
    ν.real A ≤ μ.real A := by
  let f : Set ι → ℝ := A.indicator fun _ ↦ 1
  have hfm : Measurable f := measurable_const.indicator hAm
  have hfi : IsIncreasingRandomVariable f := hA.indicator_isIncreasingRandomVariable
  have hfb : IsBoundedRealFunction f := by
    refine ⟨1, ?_⟩
    intro ω
    by_cases hω : ω ∈ A <;> simp [f, hω]
  have hle := h f hfm hfi hfb
  dsimp [f] at hle
  rw [integral_indicator_const (1 : ℝ) hAm, integral_indicator_const (1 : ℝ) hAm,
    smul_eq_mul, smul_eq_mul, mul_one, mul_one] at hle
  exact hle

/-- The sigma-algebra generated by site coordinates in `S`. -/
@[reducible] def siteCoordinateMeasurableSpace
    (ι : Type*) (S : Set ι) : MeasurableSpace (Set ι) :=
  MeasurableSpace.generateFrom {{ω : Set ι | x ∈ ω} | x ∈ S}

theorem siteCoordinateMeasurableSpace_le (ι : Type*) (S : Set ι) :
    siteCoordinateMeasurableSpace ι S ≤ (inferInstance : MeasurableSpace (Set ι)) := by
  rw [siteCoordinateMeasurableSpace]
  apply MeasurableSpace.generateFrom_le
  intro A hA
  rcases hA with ⟨x, _hx, rfl⟩
  exact measurableSet_mem x

/-- A site law is `k`-dependent when coordinate sigma-algebras at mutual graph distance greater
than `k` are independent. -/
def KDependent {ι : Type*} (G : SimpleGraph ι) (k : ℕ) (μ : Measure (Set ι)) : Prop :=
  ∀ A B : Set ι,
    (∀ x ∈ A, ∀ y ∈ B, (k : ℕ∞) < G.edist x y) →
      Indep (siteCoordinateMeasurableSpace ι A) (siteCoordinateMeasurableSpace ι B) μ

theorem KDependent.mono {ι : Type*} {G : SimpleGraph ι} {μ : Measure (Set ι)}
    {k l : ℕ} (h : KDependent G k μ) (hkl : k ≤ l) : KDependent G l μ := by
  intro A B hsep
  apply h A B
  intro x hx y hy
  exact lt_of_le_of_lt (by exact_mod_cast hkl) (hsep x hx y hy)

/-- Every iid site field is `k`-dependent for every `k`. -/
theorem setBernoulli_kDependent {ι : Type*} [Countable ι] [DecidableEq ι]
    (G : SimpleGraph ι) (k : ℕ) (p : I) :
    KDependent G k setBer((Set.univ : Set ι), p) := by
  intro A B hsep
  have hdisj : Disjoint A B := Set.disjoint_left.2 fun x hxA hxB ↦ by
    have h := hsep x hxA x hxB
    simp at h
  have hsm : ∀ x : ι, MeasurableSet {s : Set ι | x ∈ s} := fun x ↦ measurableSet_mem x
  simpa [siteCoordinateMeasurableSpace] using
    (ProbabilityTheory.iIndepSet.indep_generateFrom_of_disjoint
      (μ := setBer((Set.univ : Set ι), p))
      (s := fun x : ι ↦ {η : Set ι | x ∈ η}) hsm
      (setBernoulli_iIndepSet_mem_univ p) A B hdisj)

/-- Independence of two sub-σ-algebras is transported through a measurable pushforward. -/
theorem Indep.map_measure {Ω β : Type*} [MeasurableSpace Ω] [mβ : MeasurableSpace β]
    {μ : Measure Ω} [IsZeroOrProbabilityMeasure μ] {f : Ω → β} (hf : Measurable f)
    {m₁ m₂ : MeasurableSpace β}
    (hm₁ : m₁ ≤ mβ)
    (hm₂ : m₂ ≤ mβ)
    (h : Indep (MeasurableSpace.comap f m₁) (MeasurableSpace.comap f m₂) μ) :
    @Indep β m₁ m₂ mβ
      (@Measure.map Ω β _ mβ f μ) := by
  let ν : @Measure β mβ :=
    @Measure.map Ω β _ mβ f μ
  change @Indep β m₁ m₂ mβ ν
  rw [@indep_iff_forall_indepSet β m₁ m₂
    mβ ν]
  intro s t hs ht
  have hsGlobal : @MeasurableSet β mβ s := by
    exact hm₁ s hs
  have htGlobal : @MeasurableSet β mβ t := by
    exact hm₂ t ht
  have hsComap : MeasurableSet[MeasurableSpace.comap f m₁] (f ⁻¹' s) :=
    ⟨s, hs, rfl⟩
  have htComap : MeasurableSet[MeasurableSpace.comap f m₂] (f ⁻¹' t) :=
    ⟨t, ht, rfl⟩
  have hind := h.indepSet_of_measurableSet hsComap htComap
  have hmapInter : ν (s ∩ t) = μ (f ⁻¹' (s ∩ t)) := by
    dsimp [ν]
    exact @Measure.map_apply Ω β _ mβ μ f hf (s ∩ t) (hsGlobal.inter htGlobal)
  have hmapS : ν s = μ (f ⁻¹' s) := by
    dsimp [ν]
    exact @Measure.map_apply Ω β _ mβ μ f hf s hsGlobal
  have hmapT : ν t = μ (f ⁻¹' t) := by
    dsimp [ν]
    exact @Measure.map_apply Ω β _ mβ μ f hf t htGlobal
  apply (indepSet_iff_indepSets_singleton hsGlobal htGlobal ν).mpr
  apply indepSets_singleton_iff.mpr
  calc
    ν (s ∩ t) = μ (f ⁻¹' (s ∩ t)) := hmapInter
    _ = μ (f ⁻¹' s) * μ (f ⁻¹' t) := by
      simpa [Set.preimage_inter] using hind.measure_inter_eq_mul
    _ = ν s * ν t := by
      rw [hmapS, hmapT]

end Percolation
