import Mathlib.Probability.Independence.ZeroOne
import Percolation.Bernoulli.FKGInfinite

/-!
# Tail zero--one law for finite-modification invariant Bernoulli events

The coordinate type is denumerable.  We enumerate it, identify the sigma algebra outside every
finite prefix with a sub-sigma-algebra of the corresponding tail block, and use the existing
finite splice map to prove tail measurability.
-/

namespace Percolation

open Filter MeasureTheory MeasurableSpace ProbabilityTheory
open scoped MeasureTheory ENNReal
open scoped unitInterval

variable {iota : Type*} [DecidableEq iota] [Denumerable iota]

/-- The canonical enumeration supplied by a `Denumerable` instance. -/
noncomputable def denumerableEnumeration : ℕ ≃ iota :=
  (Denumerable.eqv iota).symm

/-- The first `n` coordinates in the canonical enumeration. -/
noncomputable def denumerablePrefix (n : ℕ) : Finset iota :=
  (Finset.range n).image denumerableEnumeration

/-- The sigma algebra generated by the `n`-th coordinate. -/
@[reducible] def enumeratedCoordinateMeasurableSpace (n : ℕ) : MeasurableSpace (Set iota) :=
  MeasurableSpace.generateFrom
    {{omega : Set iota | denumerableEnumeration n ∈ omega}}

theorem iIndep_enumeratedCoordinateMeasurableSpace (p : I) :
    iIndep (enumeratedCoordinateMeasurableSpace (iota := iota))
      setBer((Set.univ : Set iota), p) := by
  rw [← iIndepSet_iff_iIndep]
  exact (setBernoulli_iIndepSet_mem_univ (ι := iota) p).precomp
    denumerableEnumeration.injective

theorem generateFrom_compl_denumerablePrefix_le_tailBlock (n : ℕ) :
    MeasurableSpace.generateFrom
        (coordinateEvents (((denumerablePrefix (iota := iota) n : Finset iota) : Set iota)ᶜ)) ≤
      ⨆ m ≥ n, enumeratedCoordinateMeasurableSpace (iota := iota) m := by
  apply MeasurableSpace.generateFrom_le
  rintro A ⟨a, ha, rfl⟩
  let m := denumerableEnumeration.symm a
  have ham : denumerableEnumeration m = a := denumerableEnumeration.apply_symm_apply a
  have hnm : n ≤ m := by
    by_contra hmn
    have hmRange : m ∈ Finset.range n := Finset.mem_range.mpr (Nat.lt_of_not_ge hmn)
    have haPrefix : a ∈ denumerablePrefix (iota := iota) n := by
      rw [denumerablePrefix]
      exact Finset.mem_image.mpr ⟨m, hmRange, ham⟩
    exact ha haPrefix
  rw [MeasurableSpace.measurableSet_iSup]
  apply MeasurableSpace.GenerateMeasurable.basic
  refine ⟨m, ?_⟩
  rw [MeasurableSpace.measurableSet_iSup]
  apply MeasurableSpace.GenerateMeasurable.basic
  refine ⟨hnm, ?_⟩
  apply MeasurableSpace.measurableSet_generateFrom
  simp [ham]

/-- An event is unchanged when an arbitrary finite set of coordinates is forced closed. -/
def IsInvariantUnderFiniteClosing (A : Set (Set iota)) : Prop :=
  ∀ (E : Finset iota) (omega : Set iota),
    spliceOn E ∅ omega ∈ A ↔ omega ∈ A

theorem IsInvariantUnderFiniteClosing.measurableSet_compl_prefix
    {A : Set (Set iota)} (hA : MeasurableSet A)
    (hinv : IsInvariantUnderFiniteClosing A) (n : ℕ) :
    MeasurableSet[MeasurableSpace.generateFrom
      (coordinateEvents (((denumerablePrefix (iota := iota) n : Finset iota) : Set iota)ᶜ))] A := by
  let E := denumerablePrefix (iota := iota) n
  have hpre : (fun omega : Set iota ↦ spliceOn E ∅ omega) ⁻¹' A = A := by
    ext omega
    exact hinv E omega
  rw [← hpre]
  exact (measurable_spliceOn_generateFrom (E := E) (s := ∅) (by simp)) hA

theorem IsInvariantUnderFiniteClosing.measurableSet_tail
    {A : Set (Set iota)} (hA : MeasurableSet A)
    (hinv : IsInvariantUnderFiniteClosing A) :
    MeasurableSet[limsup (enumeratedCoordinateMeasurableSpace (iota := iota)) atTop] A := by
  rw [limsup_eq_iInf_iSup_of_nat]
  rw [MeasurableSpace.measurableSet_iInf]
  intro n
  exact generateFrom_compl_denumerablePrefix_le_tailBlock (iota := iota) n A
    (hinv.measurableSet_compl_prefix hA n)

/-- Kolmogorov zero--one law in the form needed for global percolation events. -/
theorem bernoulli_zero_or_one_of_invariantUnderFiniteClosing
    (p : I) {A : Set (Set iota)} (hA : MeasurableSet A)
    (hinv : IsInvariantUnderFiniteClosing A) :
    setBer((Set.univ : Set iota), p) A = 0 ∨
      setBer((Set.univ : Set iota), p) A = 1 := by
  apply measure_zero_or_one_of_measurableSet_limsup_atTop
    (m0 := inferInstance) (s := enumeratedCoordinateMeasurableSpace (iota := iota))
  · intro n
    apply MeasurableSpace.generateFrom_le
    rintro A hA
    rw [Set.mem_singleton_iff.mp hA]
    exact measurableSet_coordinateEvent (denumerableEnumeration n)
  · exact iIndep_enumeratedCoordinateMeasurableSpace p
  · exact hinv.measurableSet_tail hA

end Percolation
