import Percolation.Critical.AdaptiveDecisionOutcome

/-!
# Realizing adaptive decision-tree leaves as exploration states

The Bellman tree replays Boolean decisions through a deterministic site exploration.  This file
proves that an exact adaptive-history leaf really produces the replayed state when the same
history-dependent answer oracle drives the exploration.  Exhausted frontiers require separate
care: the total decision tree continues with harmless dummy queries, while both replayed and
actual exploration states remain fixed.
-/

namespace Percolation

open MeasureTheory ProbabilityTheory Classical

namespace SiteExploration

variable {V Omega : Type*} [DecidableEq V] [LinearOrder V]

/-- Interpret a decision-tree suffix after an already established exploration history. -/
def prefixedAdaptiveAnswer
    (prior : List (V × Bool))
    (answer : Omega → List (V × Bool) → V → Bool) :
    Omega → List (V × Bool) → V → Bool :=
  fun omega history v ↦ answer omega (prior ++ history) v

omit [DecidableEq V] [LinearOrder V] in
theorem measurableAnswer_prefixedAdaptiveAnswer
    [MeasurableSpace Omega]
    {answer : Omega → List (V × Bool) → V → Bool}
    (hanswer : AdaptiveSiteExploration.MeasurableAnswer answer)
    (prior : List (V × Bool)) :
    AdaptiveSiteExploration.MeasurableAnswer (prefixedAdaptiveAnswer prior answer) :=
  fun history v ↦ hanswer (prior ++ history) v

/-- A history-dependent step agrees with the static constant-`b` step whenever the oracle returns
`b` at the (possible) next query. -/
theorem toAdaptive_step_eq_step_const
    (E : SiteExploration V)
    (answer : List (V × Bool) → V → Bool)
    (s : SiteExplorationState V) (b : Bool)
    (hanswer : ∀ v, nextVertex s = some v → answer s.history v = b) :
    E.toAdaptive.step answer s = E.step (fun _ ↦ b) s := by
  classical
  by_cases hnone : nextVertex s = none
  · have hfrontier : s.frontier = ∅ := (nextVertex_eq_none_iff s).1 hnone
    rw [E.step_eq_self_of_frontier_eq_empty (fun _ ↦ b) hfrontier]
    simp [AdaptiveSiteExploration.step, hnone]
  · obtain ⟨v, hnext⟩ := Option.ne_none_iff_exists'.mp hnone
    have hv := hanswer v hnext
    cases b <;> simp [AdaptiveSiteExploration.step, SiteExploration.step,
      SiteExploration.toAdaptive, hnext] at hv ⊢ <;> exact hv

/-- Along a query history generated by `replayQuery`, either exploration has already exhausted
its frontier or the state's stored history is exactly the generated history. -/
theorem replayState_history_eq_or_frontier_eq_empty
    (E : SiteExploration V) (root : V) :
    ∀ {n : ℕ} (bits : Fin n → Bool),
      (E.replayState
          (AdaptiveSiteExploration.adaptiveQueryHistory (E.replayQuery root)
            (List.ofFn bits))).frontier = ∅ ∨
        (E.replayState
          (AdaptiveSiteExploration.adaptiveQueryHistory (E.replayQuery root)
            (List.ofFn bits))).history =
          E.initial.history ++
            AdaptiveSiteExploration.adaptiveQueryHistory (E.replayQuery root)
              (List.ofFn bits) := by
  intro n
  induction n with
  | zero =>
      intro bits
      right
      simp [replayState, replayStateFrom,
        AdaptiveSiteExploration.adaptiveQueryHistory]
  | succ n ih =>
      intro bits
      let bitsInit := Fin.init bits
      let b := bits (Fin.last n)
      let history := AdaptiveSiteExploration.adaptiveQueryHistory (E.replayQuery root)
        (List.ofFn bitsInit)
      have hbits : Fin.snoc bitsInit b = bits := Fin.snoc_init_self bits
      have hfull :
          AdaptiveSiteExploration.adaptiveQueryHistory (E.replayQuery root)
              (List.ofFn bits) =
            history ++ [(E.replayQuery root history, b)] := by
        rw [← hbits, AdaptiveSiteExploration.adaptiveQueryHistory_ofFn_snoc]
      have ihPrefix := ih bitsInit
      rw [hfull]
      by_cases hfrontier : (E.replayState history).frontier = ∅
      · left
        rw [E.replayState_append_eq_of_frontier_eq_empty root history b hfrontier]
        exact hfrontier
      · right
        have hhistory : (E.replayState history).history = E.initial.history ++ history :=
          ihPrefix.resolve_left hfrontier
        have hnextNe : nextVertex (E.replayState history) ≠ none := by
          intro hnone
          exact hfrontier ((nextVertex_eq_none_iff _).1 hnone)
        obtain ⟨v, hnext⟩ := Option.ne_none_iff_exists'.mp hnextNe
        have hquery : E.replayQuery root history = v :=
          E.replayQuery_eq_of_nextVertex_eq_some root history hnext
        rw [E.replayState_append_singleton]
        cases b <;> simp [SiteExploration.step, hnext, hhistory, hquery,
          List.append_assoc]

/-- Membership in an exact decision-tree leaf identifies the actual history-dependent exploration
state with the state obtained by replaying that leaf. -/
theorem toAdaptive_stateAfter_eq_replayState_of_mem_leaf
    (E : SiteExploration V) (root : V)
    (answer : Omega → List (V × Bool) → V → Bool) :
    ∀ {n : ℕ} (bits : Fin n → Bool) (omega : Omega),
      omega ∈ AdaptiveSiteExploration.adaptiveDecisionLeafEvent
          (prefixedAdaptiveAnswer E.initial.history answer)
          (E.replayQuery root) bits →
        E.toAdaptive.stateAfter (answer omega) n =
          E.replayState
            (AdaptiveSiteExploration.adaptiveQueryHistory (E.replayQuery root)
              (List.ofFn bits)) := by
  intro n
  induction n with
  | zero =>
      intro bits omega _hleaf
      rfl
  | succ n ih =>
      intro bits omega hleaf
      let bitsInit := Fin.init bits
      let b := bits (Fin.last n)
      let history := AdaptiveSiteExploration.adaptiveQueryHistory (E.replayQuery root)
        (List.ofFn bitsInit)
      have hbits : Fin.snoc bitsInit b = bits := Fin.snoc_init_self bits
      have hfull :
          AdaptiveSiteExploration.adaptiveQueryHistory (E.replayQuery root)
              (List.ofFn bits) =
            history ++ [(E.replayQuery root history, b)] := by
        rw [← hbits, AdaptiveSiteExploration.adaptiveQueryHistory_ofFn_snoc]
      have hleaf' :
          omega ∈ AdaptiveSiteExploration.adaptiveDecisionLeafEvent
              (prefixedAdaptiveAnswer E.initial.history answer)
              (E.replayQuery root) bitsInit ∩
            {omega | prefixedAdaptiveAnswer E.initial.history answer omega history
              (E.replayQuery root history) = b} := by
        rw [← AdaptiveSiteExploration.adaptiveDecisionLeafEvent_snoc]
        simpa [hbits] using hleaf
      have hstate := ih bitsInit omega hleaf'.1
      rw [AdaptiveSiteExploration.stateAfter, hstate, hfull,
        E.replayState_append_singleton]
      apply E.toAdaptive_step_eq_step_const
      intro v hnext
      have hfrontier : (E.replayState history).frontier ≠ ∅ := by
        intro hEmpty
        have : nextVertex (E.replayState history) = none :=
          (nextVertex_eq_none_iff _).2 hEmpty
        rw [hnext] at this
        contradiction
      have hhistory :
          (E.replayState history).history = E.initial.history ++ history :=
        (E.replayState_history_eq_or_frontier_eq_empty root bitsInit).resolve_left
          hfrontier
      have hquery : E.replayQuery root history = v :=
        E.replayQuery_eq_of_nextVertex_eq_some root history hnext
      rw [hhistory, ← hquery]
      exact hleaf'.2

/-- Concrete event that the actual history-dependent exploration has accepted a target vertex by
time `n`. -/
def adaptiveTargetHitEvent
    (E : SiteExploration V)
    (answer : Omega → List (V × Bool) → V → Bool)
    (target : Finset V) (n : ℕ) : Set Omega :=
  {omega | ∃ t ∈ target, t ∈ (E.toAdaptive.stateAfter (answer omega) n).occupied}

theorem measurableSet_adaptiveTargetHitEvent
    [MeasurableSpace Omega] [Countable V]
    (E : SiteExploration V)
    {answer : Omega → List (V × Bool) → V → Bool}
    (hanswer : AdaptiveSiteExploration.MeasurableAnswer answer)
    (target : Finset V) (n : ℕ) :
    MeasurableSet (E.adaptiveTargetHitEvent answer target n) := by
  have hrepr : E.adaptiveTargetHitEvent answer target n =
      ⋃ s : SiteExplorationState V, ⋃ (_hit : ∃ t ∈ target, t ∈ s.occupied),
        {omega | E.toAdaptive.stateAfter (answer omega) n = s} := by
    ext omega
    simp only [adaptiveTargetHitEvent, Set.mem_setOf_eq, Set.mem_iUnion]
    constructor
    · intro hhit
      exact ⟨E.toAdaptive.stateAfter (answer omega) n, hhit, rfl⟩
    · rintro ⟨s, hhit, hs⟩
      simpa [hs] using hhit
  rw [hrepr]
  apply MeasurableSet.iUnion
  intro s
  apply MeasurableSet.iUnion
  intro _hit
  exact E.toAdaptive.measurableSet_stateAfter_fiber hanswer n s

/-- Event that the limiting actual exploration accepts at least one target vertex. -/
def adaptiveLimitTargetHitEvent
    (E : SiteExploration V)
    (answer : Omega → List (V × Bool) → V → Bool)
    (target : Finset V) : Set Omega :=
  {omega | ∃ t ∈ target, t ∈ E.toAdaptive.occupiedLimit (answer omega)}

theorem measurableSet_adaptiveLimitTargetHitEvent
    [MeasurableSpace Omega] [Countable V]
    (E : SiteExploration V)
    {answer : Omega → List (V × Bool) → V → Bool}
    (hanswer : AdaptiveSiteExploration.MeasurableAnswer answer)
    (target : Finset V) :
    MeasurableSet (E.adaptiveLimitTargetHitEvent answer target) := by
  have hrepr : E.adaptiveLimitTargetHitEvent answer target =
      ⋃ t ∈ target, {omega | t ∈ E.toAdaptive.occupiedLimit (answer omega)} := by
    ext omega
    simp [adaptiveLimitTargetHitEvent]
  rw [hrepr]
  exact target.measurableSet_biUnion fun t _ht ↦
    E.toAdaptive.measurableSet_mem_occupiedLimit hanswer t

theorem adaptiveTargetHitEvent_subset_adaptiveLimitTargetHitEvent
    (E : SiteExploration V)
    (answer : Omega → List (V × Bool) → V → Bool)
    (target : Finset V) (n : ℕ) :
    E.adaptiveTargetHitEvent answer target n ⊆
      E.adaptiveLimitTargetHitEvent answer target := by
  rintro omega ⟨t, htTarget, htOccupied⟩
  exact ⟨t, htTarget, E.toAdaptive.occupied_subset_occupiedLimit (answer omega) n htOccupied⟩

/-- Every winning replay leaf is a genuine target hit by the actual exploration. -/
theorem adaptiveDecisionWinEvent_subset_adaptiveTargetHitEvent
    (E : SiteExploration V) (root : V)
    (answer : Omega → List (V × Bool) → V → Bool)
    (target : Finset V) (n : ℕ) :
    AdaptiveSiteExploration.adaptiveDecisionWinEvent
        (prefixedAdaptiveAnswer E.initial.history answer) (E.replayQuery root)
        (E.replayHitsTarget target) n ⊆
      E.adaptiveTargetHitEvent answer target n := by
  intro omega homega
  simp only [AdaptiveSiteExploration.adaptiveDecisionWinEvent,
    Set.mem_iUnion] at homega
  obtain ⟨bits, hwin, hleaf⟩ := homega
  have hstate := E.toAdaptive_stateAfter_eq_replayState_of_mem_leaf root
    answer bits omega hleaf
  change ∃ t ∈ target, t ∈ (E.toAdaptive.stateAfter (answer omega) n).occupied
  rw [hstate]
  exact hwin

/-- Conversely, the actual finite-time target-hit event lies in the winning replay leaf selected
by the sample.  Together with the preceding theorem this identifies the Bellman outcome event
exactly, rather than only by a one-sided inclusion. -/
theorem adaptiveTargetHitEvent_subset_adaptiveDecisionWinEvent
    (E : SiteExploration V) (root : V)
    (answer : Omega → List (V × Bool) → V → Bool)
    (target : Finset V) (n : ℕ) :
    E.adaptiveTargetHitEvent answer target n ⊆
      AdaptiveSiteExploration.adaptiveDecisionWinEvent
        (prefixedAdaptiveAnswer E.initial.history answer) (E.replayQuery root)
        (E.replayHitsTarget target) n := by
  intro omega hhit
  let bits := AdaptiveSiteExploration.adaptiveDecisionBits
    (prefixedAdaptiveAnswer E.initial.history answer) (E.replayQuery root) omega n
  have hleaf : omega ∈ AdaptiveSiteExploration.adaptiveDecisionLeafEvent
      (prefixedAdaptiveAnswer E.initial.history answer) (E.replayQuery root) bits :=
    AdaptiveSiteExploration.mem_adaptiveDecisionLeafEvent_adaptiveDecisionBits
      _ _ omega n
  have hstate := E.toAdaptive_stateAfter_eq_replayState_of_mem_leaf root
    answer bits omega hleaf
  have hwin : E.replayHitsTarget target
      (AdaptiveSiteExploration.adaptiveQueryHistory (E.replayQuery root)
        (List.ofFn bits)) := by
    change ∃ t ∈ target, t ∈
      (E.replayState
        (AdaptiveSiteExploration.adaptiveQueryHistory (E.replayQuery root)
          (List.ofFn bits))).occupied
    rw [← hstate]
    exact hhit
  exact Set.mem_iUnion.mpr ⟨bits, Set.mem_iUnion.mpr ⟨hwin, hleaf⟩⟩

theorem adaptiveTargetHitEvent_eq_adaptiveDecisionWinEvent
    (E : SiteExploration V) (root : V)
    (answer : Omega → List (V × Bool) → V → Bool)
    (target : Finset V) (n : ℕ) :
    E.adaptiveTargetHitEvent answer target n =
      AdaptiveSiteExploration.adaptiveDecisionWinEvent
        (prefixedAdaptiveAnswer E.initial.history answer) (E.replayQuery root)
        (E.replayHitsTarget target) n :=
  Set.Subset.antisymm
    (E.adaptiveTargetHitEvent_subset_adaptiveDecisionWinEvent root answer target n)
    (E.adaptiveDecisionWinEvent_subset_adaptiveTargetHitEvent root answer target n)

/-- An upper history-wise answer bound controls the probability of the concrete finite-time
target-hit event by the iid completion probability with the root forced open.  This is the
event-level counterpart of `adaptiveDecisionWinMass_le_completionHitProbability_initial`.

The bound is ratio-free: null histories require no special conditional-probability convention. -/
theorem adaptiveTargetHitEvent_probability_le_rooted_completion
    [Fintype V] [MeasurableSpace Omega]
    (G : SimpleGraph V) (neighbors : V → Finset V)
    (mem_neighbors : ∀ {x y}, y ∈ neighbors x ↔ G.Adj x y)
    (mu : Measure Omega) [IsProbabilityMeasure mu]
    {answer : Omega → List (V × Bool) → V → Bool}
    (hanswer : AdaptiveSiteExploration.MeasurableAnswer answer)
    (admissible : List (V × Bool) → V → Prop)
    (q : ℝ) (hq0 : 0 ≤ q) (hq1 : q ≤ 1)
    (root : V)
    (hupper : AdaptiveSiteExploration.HasAdaptiveAnswerUpperBoundOn
      mu
        (prefixedAdaptiveAnswer
          (rootedSiteExploration G neighbors mem_neighbors root).initial.history answer)
        admissible q)
    (target : Finset V)
    (hquery : ∀ history,
      admissible history
        ((rootedSiteExploration G neighbors mem_neighbors root).replayQuery root history)) :
    mu.real ((rootedSiteExploration G neighbors mem_neighbors root).adaptiveTargetHitEvent
        answer target
        (rootedSiteExploration G neighbors mem_neighbors root).initial.remaining.card) ≤
      (rootedSiteExploration G neighbors mem_neighbors root).completionHitProbability
        q root target (rootedSiteExploration G neighbors mem_neighbors root).initial := by
  let E := rootedSiteExploration G neighbors mem_neighbors root
  have hanswerPrefixed : AdaptiveSiteExploration.MeasurableAnswer
      (prefixedAdaptiveAnswer E.initial.history answer) :=
    measurableAnswer_prefixedAdaptiveAnswer hanswer E.initial.history
  have hwinMeasure :
      mu.real (AdaptiveSiteExploration.adaptiveDecisionWinEvent
        (prefixedAdaptiveAnswer E.initial.history answer) (E.replayQuery root)
          (E.replayHitsTarget target) E.initial.remaining.card) =
        AdaptiveSiteExploration.adaptiveDecisionWinMass mu
          (prefixedAdaptiveAnswer E.initial.history answer) (E.replayQuery root)
          (E.replayHitsTarget target) [] E.initial.remaining.card :=
    AdaptiveSiteExploration.measureReal_adaptiveDecisionWinEvent
      mu hanswerPrefixed (E.replayQuery root) (E.replayHitsTarget target)
        E.initial.remaining.card
  change mu.real (E.adaptiveTargetHitEvent answer target E.initial.remaining.card) ≤
    E.completionHitProbability q root target E.initial
  rw [E.adaptiveTargetHitEvent_eq_adaptiveDecisionWinEvent root answer target,
    hwinMeasure]
  exact E.adaptiveDecisionWinMass_le_completionHitProbability_initial
    mu hanswerPrefixed admissible q hq0 hq1 hupper root target hquery
    (rootedSiteExploration_initial_wellFormed G neighbors mem_neighbors root)
    (rootedSiteExploration_initial_openRootedAt G neighbors mem_neighbors root)
    (rootedSiteExploration_initial_frontierClosed G neighbors mem_neighbors root)

/-- The abstract Bellman comparison now bounds the probability of a concrete finite-time target
hit in the actual history-dependent exploration. -/
theorem finiteSiteHitsTarget_probability_le_adaptiveTargetHitEvent
    [Fintype V] [MeasurableSpace Omega]
    (G : SimpleGraph V) (neighbors : V → Finset V)
    (mem_neighbors : ∀ {x y}, y ∈ neighbors x ↔ G.Adj x y)
    (mu : Measure Omega) [IsProbabilityMeasure mu]
    {answer : Omega → List (V × Bool) → V → Bool}
    (hanswer : AdaptiveSiteExploration.MeasurableAnswer answer)
    (admissible : List (V × Bool) → V → Prop)
    (q : ℝ) (hq0 : 0 ≤ q) (hq1 : q ≤ 1)
    (root : V)
    (hlower : AdaptiveSiteExploration.HasAdaptiveAnswerLowerBoundOn
      mu
        (prefixedAdaptiveAnswer
          (rootedSiteExploration G neighbors mem_neighbors root).initial.history answer)
        admissible q)
    (target : Finset V)
    (hquery : ∀ history,
      ((rootedSiteExploration G neighbors mem_neighbors root).replayState history
        ).frontier.Nonempty →
      ¬ (rootedSiteExploration G neighbors mem_neighbors root).replayHitsTarget
        target history →
      admissible history
        ((rootedSiteExploration G neighbors mem_neighbors root).replayQuery root history)) :
    finiteBernoulliProbability Finset.univ q (finiteSiteHitsTarget G root target) ≤
      mu.real ((rootedSiteExploration G neighbors mem_neighbors root).adaptiveTargetHitEvent
        answer target
        (rootedSiteExploration G neighbors mem_neighbors root).initial.remaining.card) := by
  let E := rootedSiteExploration G neighbors mem_neighbors root
  have hanswerPrefixed : AdaptiveSiteExploration.MeasurableAnswer
      (prefixedAdaptiveAnswer E.initial.history answer) :=
    measurableAnswer_prefixedAdaptiveAnswer hanswer E.initial.history
  have hbellman := finiteSiteHitsTarget_probability_le_adaptiveDecisionWinMass
    G neighbors mem_neighbors mu hanswerPrefixed admissible q hq0 hq1 hlower
      root target hquery
  have hwinMeasure :
      mu.real (AdaptiveSiteExploration.adaptiveDecisionWinEvent
        (prefixedAdaptiveAnswer E.initial.history answer) (E.replayQuery root)
          (E.replayHitsTarget target) E.initial.remaining.card) =
        AdaptiveSiteExploration.adaptiveDecisionWinMass mu
          (prefixedAdaptiveAnswer E.initial.history answer) (E.replayQuery root)
          (E.replayHitsTarget target) [] E.initial.remaining.card :=
    AdaptiveSiteExploration.measureReal_adaptiveDecisionWinEvent
      mu hanswerPrefixed (E.replayQuery root) (E.replayHitsTarget target)
        E.initial.remaining.card
  change finiteBernoulliProbability Finset.univ q (finiteSiteHitsTarget G root target) ≤
    mu.real (E.adaptiveTargetHitEvent answer target E.initial.remaining.card)
  calc
    finiteBernoulliProbability Finset.univ q (finiteSiteHitsTarget G root target) ≤
        mu.real (AdaptiveSiteExploration.adaptiveDecisionWinEvent
          (prefixedAdaptiveAnswer E.initial.history answer) (E.replayQuery root)
            (E.replayHitsTarget target) E.initial.remaining.card) := by
      rw [hwinMeasure]
      exact hbellman
    _ ≤ mu.real (E.adaptiveTargetHitEvent answer target E.initial.remaining.card) :=
      measureReal_mono
        (E.adaptiveDecisionWinEvent_subset_adaptiveTargetHitEvent root answer target _)

/-- Limit-set form of the finite target comparison. -/
theorem finiteSiteHitsTarget_probability_le_adaptiveLimitTargetHitEvent
    [Fintype V] [MeasurableSpace Omega]
    (G : SimpleGraph V) (neighbors : V → Finset V)
    (mem_neighbors : ∀ {x y}, y ∈ neighbors x ↔ G.Adj x y)
    (mu : Measure Omega) [IsProbabilityMeasure mu]
    {answer : Omega → List (V × Bool) → V → Bool}
    (hanswer : AdaptiveSiteExploration.MeasurableAnswer answer)
    (admissible : List (V × Bool) → V → Prop)
    (q : ℝ) (hq0 : 0 ≤ q) (hq1 : q ≤ 1)
    (root : V)
    (hlower : AdaptiveSiteExploration.HasAdaptiveAnswerLowerBoundOn
      mu
        (prefixedAdaptiveAnswer
          (rootedSiteExploration G neighbors mem_neighbors root).initial.history answer)
        admissible q)
    (target : Finset V)
    (hquery : ∀ history,
      ((rootedSiteExploration G neighbors mem_neighbors root).replayState history
        ).frontier.Nonempty →
      ¬ (rootedSiteExploration G neighbors mem_neighbors root).replayHitsTarget
        target history →
      admissible history
        ((rootedSiteExploration G neighbors mem_neighbors root).replayQuery root history)) :
    finiteBernoulliProbability Finset.univ q (finiteSiteHitsTarget G root target) ≤
      mu.real (adaptiveLimitTargetHitEvent
        (rootedSiteExploration G neighbors mem_neighbors root) answer target) := by
  let E := rootedSiteExploration G neighbors mem_neighbors root
  calc
    finiteBernoulliProbability Finset.univ q (finiteSiteHitsTarget G root target) ≤
        mu.real (E.adaptiveTargetHitEvent answer target E.initial.remaining.card) :=
      finiteSiteHitsTarget_probability_le_adaptiveTargetHitEvent
        G neighbors mem_neighbors mu hanswer admissible q hq0 hq1 root hlower target hquery
    _ ≤ mu.real (E.adaptiveLimitTargetHitEvent answer target) :=
      measureReal_mono
        (E.adaptiveTargetHitEvent_subset_adaptiveLimitTargetHitEvent answer target _)

end SiteExploration

end Percolation
