import Percolation.Critical.ConnectivitySkeleton
import Mathlib.Logic.Equiv.Option

/-!
# Connected-kernel partition bounds

This file isolates the summation argument behind Grimmett (6.94).  A finite connected network
whose edge kernel is at most one has partition function at most one row-sum factor for every
vertex except the pinned root.  The formulation permits repeated edges; this is useful for
decoded connectivity skeletons and makes the estimate robust under harmless coding choices.
-/

namespace Percolation

open Set SimpleGraph
open scoped BigOperators ENNReal

variable {V E α : Type*}

/-- The simple graph generated by a finite endpoint family. -/
def finiteNetworkGraph [Fintype E] (ends : E → V × V) : SimpleGraph V where
  Adj u v := u ≠ v ∧ ∃ e, ends e = (u, v) ∨ ends e = (v, u)
  symm := by
    rintro u v ⟨huv, e, h | h⟩
    · exact ⟨huv.symm, e, Or.inr h⟩
    · exact ⟨huv.symm, e, Or.inl h⟩
  loopless := by
    exact ⟨fun u h ↦ h.1 rfl⟩

/-- The endpoint-product partition function with one vertex pinned. -/
noncomputable def connectedKernelPartition [Fintype V] [Fintype E]
    (ends : E → V × V) (K : α → α → ℝ≥0∞) (root : V) (a : α) : ℝ≥0∞ :=
  by
    classical
    exact ∑' ψ : V → α,
      if ψ root = a then ∏ e : E, K (ψ (ends e).1) (ψ (ends e).2) else 0

/-- Split a function into its value at one point and its restriction to the complement. -/
def piSplitAt [DecidableEq V] (c : V) : (V → α) ≃ α × ({v : V // v ≠ c} → α) :=
  (Equiv.piCongrLeft (fun _ : V ↦ α) (Equiv.optionSubtypeNe c)).symm.trans
    Equiv.piOptionEquivProd

@[simp] theorem piSplitAt_fst [DecidableEq V] (c : V) (f : V → α) :
    (piSplitAt c f).1 = f c := by
  simp [piSplitAt, Equiv.piCongrLeft, Equiv.piCongrLeft']

@[simp] theorem piSplitAt_snd [DecidableEq V] (c : V) (f : V → α)
    (v : {v : V // v ≠ c}) :
    (piSplitAt c f).2 v = f v := by
  simp [piSplitAt, Equiv.piCongrLeft, Equiv.piCongrLeft']

@[simp] theorem piSplitAt_symm_apply_self [DecidableEq V] (c : V)
    (q : α × ({v : V // v ≠ c} → α)) : (piSplitAt c).symm q c = q.1 := by
  simp [piSplitAt, Equiv.piCongrLeft, Equiv.piCongrLeft']

@[simp] theorem piSplitAt_symm_apply_ne [DecidableEq V] (c : V)
    (q : α × ({v : V // v ≠ c} → α)) (v : {v : V // v ≠ c}) :
    (piSplitAt c).symm q v = q.2 v := by
  simp [piSplitAt, Equiv.piCongrLeft, Equiv.piCongrLeft', v.2]

/-- Edge indices not incident to a chosen vertex. -/
def RemainingEdge [Fintype E] (ends : E → V × V) (c : V) :=
  {e : E // (ends e).1 ≠ c ∧ (ends e).2 ≠ c}

noncomputable instance [Fintype E] [DecidableEq V] (ends : E → V × V) (c : V) :
    Fintype (RemainingEdge ends c) :=
  Fintype.ofFinset
    (Finset.univ.filter (fun e ↦ (ends e).1 ≠ c ∧ (ends e).2 ≠ c))
    (by
      intro e
      change (e ∈ Finset.univ.filter
        (fun e ↦ (ends e).1 ≠ c ∧ (ends e).2 ≠ c)) ↔
          ((ends e).1 ≠ c ∧ (ends e).2 ≠ c)
      simp)

/-- Endpoints of the network induced away from one vertex. -/
def remainingEnds [Fintype E] (ends : E → V × V) (c : V) :
    RemainingEdge ends c → {v : V // v ≠ c} × {v : V // v ≠ c} :=
  fun e ↦ (⟨(ends e.1).1, e.2.1⟩, ⟨(ends e.1).2, e.2.2⟩)

/-- Deleting the incident edge indices realizes the induced graph on the complement. -/
theorem finiteNetworkGraph_remainingEnds [Fintype E] [DecidableEq V]
    (ends : E → V × V) (c : V) :
    finiteNetworkGraph (remainingEnds ends c) =
      (finiteNetworkGraph ends).induce {c}ᶜ := by
  ext u v
  change (u ≠ v ∧ ∃ e : RemainingEdge ends c,
      remainingEnds ends c e = (u, v) ∨ remainingEnds ends c e = (v, u)) ↔
    ((u : V) ≠ v ∧ ∃ e : E,
      ends e = ((u : V), (v : V)) ∨ ends e = ((v : V), (u : V)))
  constructor
  · rintro ⟨huv, e, he | he⟩
    · refine ⟨fun huv' ↦ huv (Subtype.ext huv'), e.1, Or.inl ?_⟩
      exact Prod.ext (congrArg Subtype.val (congrArg Prod.fst he))
        (congrArg Subtype.val (congrArg Prod.snd he))
    · refine ⟨fun huv' ↦ huv (Subtype.ext huv'), e.1, Or.inr ?_⟩
      exact Prod.ext (congrArg Subtype.val (congrArg Prod.fst he))
        (congrArg Subtype.val (congrArg Prod.snd he))
  · rintro ⟨huv, e, he | he⟩
    · have he1 : (ends e).1 ≠ c := by simpa [he] using u.2
      have he2 : (ends e).2 ≠ c := by simpa [he] using v.2
      refine ⟨fun huv' ↦ huv (congrArg Subtype.val huv'), ⟨e, he1, he2⟩, Or.inl ?_⟩
      exact Prod.ext (Subtype.ext (congrArg Prod.fst he))
        (Subtype.ext (congrArg Prod.snd he))
    · have he1 : (ends e).1 ≠ c := by simpa [he] using v.2
      have he2 : (ends e).2 ≠ c := by simpa [he] using u.2
      refine ⟨fun huv' ↦ huv (congrArg Subtype.val huv'), ⟨e, he1, he2⟩, Or.inr ?_⟩
      exact Prod.ext (Subtype.ext (congrArg Prod.fst he))
        (Subtype.ext (congrArg Prod.snd he))

/-- Keeping one incident edge and all nonincident edges only increases a product of factors in
`[0,1]`. -/
theorem network_product_le_incident_mul_remaining
    [Fintype E] [DecidableEq E] [DecidableEq V]
    (ends : E → V × V) (K : α → α → ℝ≥0∞)
    (hKsymm : ∀ a b, K a b = K b a) (hKle : ∀ a b, K a b ≤ 1)
    (c u : V) (e₀ : E)
    (he₀ : ends e₀ = (c, u) ∨ ends e₀ = (u, c)) (ψ : V → α) :
    (∏ e : E, K (ψ (ends e).1) (ψ (ends e).2)) ≤
      K (ψ c) (ψ u) *
        ∏ e : RemainingEdge ends c,
          K (ψ (ends e.1).1) (ψ (ends e.1).2) := by
  classical
  let S : Finset E := {e₀} ∪ Finset.univ.filter
    (fun e ↦ (ends e).1 ≠ c ∧ (ends e).2 ≠ c)
  have hsub : S ⊆ Finset.univ := Finset.subset_univ _
  have hprod := Finset.prod_le_prod_of_subset_of_le_one
    (f := fun e ↦ K (ψ (ends e).1) (ψ (ends e).2)) hsub
    (fun _ _ ↦ bot_le) (fun e _ _ ↦ hKle _ _)
  calc
    (∏ e : E, K (ψ (ends e).1) (ψ (ends e).2)) ≤
        ∏ e ∈ S, K (ψ (ends e).1) (ψ (ends e).2) := by
      simpa only using hprod
    _ = K (ψ c) (ψ u) *
        ∏ e : RemainingEdge ends c,
          K (ψ (ends e.1).1) (ψ (ends e.1).2) := by
      have heNot : e₀ ∉ Finset.univ.filter
          (fun e ↦ (ends e).1 ≠ c ∧ (ends e).2 ≠ c) := by
        simp only [Finset.mem_filter, Finset.mem_univ, true_and]
        rcases he₀ with he₀ | he₀ <;> simp [he₀]
      rw [Finset.prod_union (Finset.disjoint_singleton_left.mpr heNot), Finset.prod_singleton]
      congr 1
      · rcases he₀ with he₀ | he₀
        · simp [he₀]
        · simp [he₀, hKsymm]
      · exact Finset.prod_subtype
          (Finset.univ.filter (fun e ↦ (ends e).1 ≠ c ∧ (ends e).2 ≠ c))
          (by simp) (fun e ↦ K (ψ (ends e).1) (ψ (ends e).2))


end Percolation
