import Percolation.Critical.AdaptiveAnswerHistory

/-!
# History-indexed oriented restart laws

This file packages the exact remaining probability interface in the Grimmett--Marstrand block
construction.  A query records its physical center, signed direction, revealed region, and
boundary thresholds.  A protocol must prove that its literal adaptive history cell is the
intersection of the current closed-boundary cell with earlier information on coordinates
disjoint from the new restart support.  Lemma 7.17 then supplies the ratio-free answer bound
required by Lemma 7.24.

The package is infrastructure, not an assumption in a source-facing theorem: Theorem 7.2 must
construct a protocol and discharge every field from its concrete reveal schedule.
-/

namespace Percolation

open MeasureTheory ProbabilityTheory
open scoped unitInterval

/-- All geometric and threshold data for one oriented restart query. -/
structure OrientedRestartQuery (d : ℕ) where
  center : Cubic d
  direction : CubicDirection d
  region : Finset (Cubic d)
  beta : CubicEdge d → I

namespace OrientedRestartQuery

def successEvent {d : ℕ} (Q : OrientedRestartQuery d)
    (m n : ℕ) (p : I) (delta : ℝ) : Set (CubicEdge d → ℝ) :=
  orientedSprinkledRestartEvent Q.center Q.direction m n Q.region p Q.beta delta

def boundaryHistoryEvent {d : ℕ} (Q : OrientedRestartQuery d)
    (n : ℕ) : Set (CubicEdge d → ℝ) :=
  orientedBoundaryClosedHistoryEvent Q.center Q.direction Q.region n Q.beta

noncomputable def restartSupport {d : ℕ} (Q : OrientedRestartQuery d)
    (m n : ℕ) : Finset (CubicEdge d) :=
  orientedRestartSupport Q.center Q.direction m n Q.region

theorem measurableSet_successEvent_coordSigma {d : ℕ} (Q : OrientedRestartQuery d)
    (m n : ℕ) (p : I) (delta : ℝ) :
    MeasurableSet[coordSigma (CubicEdge d)
      (Q.restartSupport m n : Set (CubicEdge d))]
      (Q.successEvent m n p delta) :=
  measurableSet_orientedSprinkledRestartEvent_coordSigma
    Q.center Q.direction m n Q.region p Q.beta delta

end OrientedRestartQuery

namespace AdaptiveSiteExploration

variable {V : Type*}

/-- Success-event family generated by a history-indexed oriented restart query. -/
def orientedRestartSuccessFamily {d : ℕ}
    (query : List (V × Bool) → V → OrientedRestartQuery d)
    (m n : ℕ) (p : I) (delta : ℝ) :
    List (V × Bool) → V → Set (CubicEdge d → ℝ) :=
  fun history v => (query history v).successEvent m n p delta

/-- A concrete protocol certificate for adjoining one fresh oriented restart to every exact
adaptive history.  `history_eq` prevents the construction from replacing the real answer
history by a coarser boundary event. -/
structure FreshOrientedRestartProtocol
    (d : ℕ) (V : Type*) (m n : ℕ) (p : I) (delta epsilon : ℝ) where
  query : List (V × Bool) → V → OrientedRestartQuery d
  pastSupport : List (V × Bool) → V → Finset (CubicEdge d)
  past : List (V × Bool) → V → Set (CubicEdge d → ℝ)
  past_measurable : ∀ history v,
    MeasurableSet[coordSigma (CubicEdge d)
      (pastSupport history v : Set (CubicEdge d))] (past history v)
  fresh : ∀ history v,
    Disjoint (pastSupport history v : Set (CubicEdge d))
      ((query history v).restartSupport m n : Set (CubicEdge d))
  history_eq : ∀ history v,
    adaptiveAnswerHistoryEvent
        (eventAdaptiveAnswer (orientedRestartSuccessFamily query m n p delta)) history =
      past history v ∩ (query history v).boundaryHistoryEvent n
  restart_gt : ∀ history v,
    (1 - epsilon) *
        (couplingMeasure (CubicEdge d)).real
          ((query history v).boundaryHistoryEvent n) <
      (couplingMeasure (CubicEdge d)).real
        ((query history v).successEvent m n p delta ∩
          (query history v).boundaryHistoryEvent n)

namespace FreshOrientedRestartProtocol

variable {d : ℕ} {m n : ℕ} {p : I} {delta epsilon : ℝ}
    (P : FreshOrientedRestartProtocol d V m n p delta epsilon)

noncomputable def answer :
    (CubicEdge d → ℝ) → List (V × Bool) → V → Bool :=
  eventAdaptiveAnswer (orientedRestartSuccessFamily P.query m n p delta)

theorem measurableAnswer : MeasurableAnswer P.answer := by
  apply measurableAnswer_eventAdaptiveAnswer
  intro history v
  have h := (P.query history v).measurableSet_successEvent_coordSigma m n p delta
  exact (coordSigma_le _) _ h

/-- The protocol's concrete event answer satisfies the history-wise ratio-free premise used by
the source-facing Lemma 7.24. -/
theorem hasAdaptiveAnswerLowerBound :
    HasAdaptiveAnswerLowerBoundOn (couplingMeasure (CubicEdge d)) P.answer
      (fun _ _ => True) (1 - epsilon) := by
  apply hasAdaptiveAnswerLowerBoundOn_eventAdaptiveAnswer
  intro history v _
  rw [P.history_eq history v]
  exact orientedSprinkledRestart_inter_past_history_ge
    (P.query history v).center (P.query history v).direction
    (P.query history v).region p (P.query history v).beta delta epsilon
    (P.pastSupport history v) (P.past history v)
    (P.past_measurable history v) (P.fresh history v) (P.restart_gt history v)

end FreshOrientedRestartProtocol

end AdaptiveSiteExploration

end Percolation
