import Percolation.Critical.DynamicLaterSiteRuntime

/-!
# Exact-history stability of the total non-root runtime

The total runtime must be deterministic on each accumulated source-history cell, including its
mixed-witness selections and outgoing anchors.  These lemmas provide that invariant without
assuming that the corresponding coarse site succeeds.
-/

namespace Percolation

open scoped unitInterval

namespace LaterSiteRuntime

/-- A total runtime refines the incoming accumulated-history cell under a monotone threshold
policy. -/
theorem runFrom_historyProfile_event_subset
    {d m n : ℕ} (hmn : 2 * m ≤ n)
    (inletCenter : Cubic d) (incoming : CubicDirection d)
    (firstFlip secondFlip : Fin d → Bool)
    (p : I) (delta : ℝ) (incremented : RootExtensionThresholdPolicy d)
    (hmono : ∀ S a e, S.lower e ≤ incremented S a e)
    (X : CubicEdge d → ℝ) (R : LaterSiteRuntime d) (offset : ℕ)
    (directions : List (CubicDirection d)) :
    (runFrom hmn inletCenter incoming firstFlip secondFlip p delta incremented X
      R offset directions).source.historyProfile.event ⊆ R.source.historyProfile.event := by
  induction directions generalizing R offset with
  | nil => exact Set.Subset.rfl
  | cons a rest ih =>
      let Q := R.restartQuery inletCenter incoming firstFlip secondFlip a offset
      let R' := R.step hmn inletCenter incoming firstFlip secondFlip
        p delta incremented X a offset
      have hstep : R'.source.historyProfile.event ⊆ R.source.historyProfile.event := by
        exact R.source.next_historyProfile_event_subset_historyProfile_event
          (Q.restartSupport m n) p (incremented R.source a) X (hmono R.source a)
      exact (ih (R := R') (offset := offset + 1)).trans hstep

/-- A realization belongs to the terminal accumulated-history cell generated by its own total
runtime on the common nonnegative coupling support. -/
theorem mem_runFrom_historyProfile
    {d m n : ℕ} (hmn : 2 * m ≤ n)
    (inletCenter : Cubic d) (incoming : CubicDirection d)
    (firstFlip secondFlip : Fin d → Bool)
    (p : I) (delta : ℝ) (incremented : RootExtensionThresholdPolicy d)
    (X : CubicEdge d → ℝ) (R : LaterSiteRuntime d) (offset : ℕ)
    (directions : List (CubicDirection d))
    (hnonneg : X ∈ SourceFiniteEdgeRevealState.nonnegativeCouplingEvent)
    (hcurrent : X ∈ R.source.historyProfile.event) :
    X ∈ (runFrom hmn inletCenter incoming firstFlip secondFlip p delta incremented X
      R offset directions).source.historyProfile.event := by
  induction directions generalizing R offset with
  | nil => exact hcurrent
  | cons a rest ih =>
      let Q := R.restartQuery inletCenter incoming firstFlip secondFlip a offset
      let R' := R.step hmn inletCenter incoming firstFlip secondFlip
        p delta incremented X a offset
      apply ih (R := R') (offset := offset + 1)
      exact R.source.mem_next_historyProfile
        (Q.restartSupport m n) p (incremented R.source a) X hcurrent hnonneg

/-- One total runtime step, including its selected target and outgoing table, is constant on
the realized successor history cell. -/
theorem step_eq_of_mem_nextHistoryProfile
    {d m n : ℕ} (hmn : 2 * m ≤ n)
    (R : LaterSiteRuntime d) (inletCenter : Cubic d)
    (incoming : CubicDirection d) (firstFlip secondFlip : Fin d → Bool)
    (p : I) (delta : ℝ) (incremented : RootExtensionThresholdPolicy d)
    (X Y : CubicEdge d → ℝ) (a : CubicDirection d) (k : ℕ)
    (hTargetFresh :
      let center := R.slotCenterFor inletCenter a k
      let flip := R.slotTransverseFlip incoming firstFlip secondFlip a k
      let F := cubicRestartFrameIso center a flip
      Disjoint (cubicEdgeEndpointVertices (R.source.referenceExploredEdges F))
        (cubicEdgeEndpointVertices (seededBoundaryTargetSupport d a.1 m n)))
    (hadds : ∀ e ∈ (R.restartQuery inletCenter incoming firstFlip secondFlip a k
      ).boundarySupport n,
      (incremented R.source a e : ℝ) = (R.source.lower e : ℝ) + delta)
    (hcurrent : X ∈ R.source.historyProfile.event)
    (hnonneg : X ∈ SourceFiniteEdgeRevealState.nonnegativeCouplingEvent)
    (hY : Y ∈ (R.step hmn inletCenter incoming firstFlip secondFlip
      p delta incremented X a k).source.historyProfile.event) :
    R.step hmn inletCenter incoming firstFlip secondFlip
        p delta incremented Y a k =
      R.step hmn inletCenter incoming firstFlip secondFlip
        p delta incremented X a k := by
  let center := R.slotCenterFor inletCenter a k
  let flip := R.slotTransverseFlip incoming firstFlip secondFlip a k
  let Q := R.restartQuery inletCenter incoming firstFlip secondFlip a k
  have hselected : R.source.selectedMixedWitness (m := m) (n := n)
        center a flip p delta Y =
      R.source.selectedMixedWitness (m := m) (n := n)
        center a flip p delta X := by
    unfold SourceFiniteEdgeRevealState.selectedMixedWitness
    apply R.source.selectedMixedRestartSeedWitness_eq_of_mem_nextHistoryProfile
      center a flip p delta (incremented R.source a) X Y hTargetFresh
    · intro e he
      rw [R.source.framedQuery_physicalBoundaryThreshold]
      exact hadds e (by simpa [Q, center, flip] using he)
    · exact hcurrent
    · exact hnonneg
    · simpa [step, Q, center, flip] using hY
  have hsource :
      R.source.next (Q.restartSupport m n) p (incremented R.source a) Y =
        R.source.next (Q.restartSupport m n) p (incremented R.source a) X := by
    apply R.source.next_eq_of_mem_next_historyProfile
    simpa [step, Q, center, flip] using hY
  apply LaterSiteRuntime.ext
  · simpa [step, Q, center, flip] using hsource
  · simp [step, selectedTarget, selectedWitness, Q, center, flip, hselected]
  · simp [step, selectedTarget, selectedWitness, Q, center, flip, hselected]
  · simp [step, selectedTarget, selectedWitness, Q, center, flip, hselected]
  · simp [step, selectedTarget, selectedWitness, Q, center, flip, hselected]

/-- The complete total runtime is constant on its terminal accumulated-history cell. -/
theorem runFrom_eq_of_mem_historyProfile
    {d m n : ℕ} (hmn : 2 * m ≤ n)
    (inletCenter : Cubic d) (incoming : CubicDirection d)
    (firstFlip secondFlip : Fin d → Bool)
    (p : I) (delta : ℝ) (incremented : RootExtensionThresholdPolicy d)
    (hmono : ∀ S a e, S.lower e ≤ incremented S a e)
    (X Y : CubicEdge d → ℝ) (R : LaterSiteRuntime d) (offset : ℕ)
    (directions : List (CubicDirection d))
    (hadds : ∀ j (hj : j < directions.length) e,
      let Rj := runFrom hmn inletCenter incoming firstFlip secondFlip
        p delta incremented X R offset (directions.take j)
      let a := directions[j]
      (incremented Rj.source a e : ℝ) = (Rj.source.lower e : ℝ) + delta)
    (hfresh : ∀ j (hj : j < directions.length),
      let Rj := runFrom hmn inletCenter incoming firstFlip secondFlip
        p delta incremented X R offset (directions.take j)
      let a := directions[j]
      let center := Rj.slotCenterFor inletCenter a (offset + j)
      let flip := Rj.slotTransverseFlip incoming firstFlip secondFlip a (offset + j)
      let F := cubicRestartFrameIso center a flip
      Disjoint (cubicEdgeEndpointVertices (Rj.source.referenceExploredEdges F))
        (cubicEdgeEndpointVertices (seededBoundaryTargetSupport d a.1 m n)))
    (hcurrent : X ∈ R.source.historyProfile.event)
    (hnonneg : X ∈ SourceFiniteEdgeRevealState.nonnegativeCouplingEvent)
    (hY : Y ∈ (runFrom hmn inletCenter incoming firstFlip secondFlip
      p delta incremented X R offset directions).source.historyProfile.event) :
    runFrom hmn inletCenter incoming firstFlip secondFlip
        p delta incremented Y R offset directions =
      runFrom hmn inletCenter incoming firstFlip secondFlip
        p delta incremented X R offset directions := by
  induction directions generalizing R offset with
  | nil => rfl
  | cons a rest ih =>
      let Q := R.restartQuery inletCenter incoming firstFlip secondFlip a offset
      let RX := R.step hmn inletCenter incoming firstFlip secondFlip
        p delta incremented X a offset
      let RY := R.step hmn inletCenter incoming firstFlip secondFlip
        p delta incremented Y a offset
      have hYnext : Y ∈ RX.source.historyProfile.event := by
        exact runFrom_historyProfile_event_subset hmn inletCenter incoming
          firstFlip secondFlip p delta incremented hmono X RX (offset + 1) rest hY
      have hfreshFirst :
          let center := R.slotCenterFor inletCenter a offset
          let flip := R.slotTransverseFlip incoming firstFlip secondFlip a offset
          let F := cubicRestartFrameIso center a flip
          Disjoint (cubicEdgeEndpointVertices (R.source.referenceExploredEdges F))
            (cubicEdgeEndpointVertices (seededBoundaryTargetSupport d a.1 m n)) := by
        simpa using hfresh 0 (by simp)
      have haddsFirst : ∀ e ∈ Q.boundarySupport n,
          (incremented R.source a e : ℝ) = (R.source.lower e : ℝ) + delta := by
        intro e _he
        simpa [Q] using hadds 0 (by simp) e
      have hstep : RY = RX :=
        step_eq_of_mem_nextHistoryProfile hmn R inletCenter incoming
          firstFlip secondFlip p delta incremented X Y a offset
          hfreshFirst haddsFirst hcurrent hnonneg hYnext
      have hcurrentNext : X ∈ RX.source.historyProfile.event := by
        exact R.source.mem_next_historyProfile
          (Q.restartSupport m n) p (incremented R.source a) X hcurrent hnonneg
      have hrest :
          runFrom hmn inletCenter incoming firstFlip secondFlip p delta incremented Y
              RX (offset + 1) rest =
            runFrom hmn inletCenter incoming firstFlip secondFlip p delta incremented X
              RX (offset + 1) rest := by
        apply ih (R := RX) (offset := offset + 1)
        · intro j hj e
          have hs := hadds (j + 1) (by simp; omega) e
          simpa [RX, Q, List.take_succ_cons, runFrom, Nat.add_assoc] using hs
        · intro j hj
          have hs := hfresh (j + 1) (by simp; omega)
          simpa [RX, Q, List.take_succ_cons, runFrom, Nat.add_assoc,
            Nat.add_comm, Nat.add_left_comm] using hs
        · exact hcurrentNext
        · exact hY
      change runFrom hmn inletCenter incoming firstFlip secondFlip p delta incremented Y
          RY (offset + 1) rest =
        runFrom hmn inletCenter incoming firstFlip secondFlip p delta incremented X
          RX (offset + 1) rest
      rw [hstep]
      exact hrest

/-- Every successful restart in a total non-root schedule remains successful throughout the
terminal accumulated-history cell.  Together with `runFrom_eq_of_mem_historyProfile`, this
says that both the Boolean answer and every published seed anchor are determined by the finite
history cell. -/
theorem succeedsFrom_of_mem_historyProfile
    {d m n : ℕ} (hmn : 2 * m ≤ n)
    (inletCenter : Cubic d) (incoming : CubicDirection d)
    (firstFlip secondFlip : Fin d → Bool)
    (p : I) (delta : ℝ) (incremented : RootExtensionThresholdPolicy d)
    (hmono : ∀ S a e, S.lower e ≤ incremented S a e)
    (X Y : CubicEdge d → ℝ) (R : LaterSiteRuntime d) (offset : ℕ)
    (directions : List (CubicDirection d))
    (hadds : ∀ j (hj : j < directions.length) e,
      let Rj := runFrom hmn inletCenter incoming firstFlip secondFlip
        p delta incremented X R offset (directions.take j)
      let a := directions[j]
      (incremented Rj.source a e : ℝ) = (Rj.source.lower e : ℝ) + delta)
    (hfresh : ∀ j (hj : j < directions.length),
      let Rj := runFrom hmn inletCenter incoming firstFlip secondFlip
        p delta incremented X R offset (directions.take j)
      let a := directions[j]
      let center := Rj.slotCenterFor inletCenter a (offset + j)
      let flip := Rj.slotTransverseFlip incoming firstFlip secondFlip a (offset + j)
      let F := cubicRestartFrameIso center a flip
      Disjoint (cubicEdgeEndpointVertices (Rj.source.referenceExploredEdges F))
        (cubicEdgeEndpointVertices (seededBoundaryTargetSupport d a.1 m n)))
    (hcurrent : X ∈ R.source.historyProfile.event)
    (hnonneg : X ∈ SourceFiniteEdgeRevealState.nonnegativeCouplingEvent)
    (hsuccess : succeedsFrom hmn inletCenter incoming firstFlip secondFlip
      p delta incremented X R offset directions)
    (hY : Y ∈ (runFrom hmn inletCenter incoming firstFlip secondFlip
      p delta incremented X R offset directions).source.historyProfile.event) :
    succeedsFrom hmn inletCenter incoming firstFlip secondFlip
      p delta incremented Y R offset directions := by
  induction directions generalizing R offset with
  | nil => trivial
  | cons a rest ih =>
      let Q := R.restartQuery inletCenter incoming firstFlip secondFlip a offset
      let RX := R.step hmn inletCenter incoming firstFlip secondFlip
        p delta incremented X a offset
      let RY := R.step hmn inletCenter incoming firstFlip secondFlip
        p delta incremented Y a offset
      have hYnext : Y ∈ RX.source.historyProfile.event := by
        exact runFrom_historyProfile_event_subset hmn inletCenter incoming
          firstFlip secondFlip p delta incremented hmono X RX (offset + 1) rest hY
      have hfreshFirst :
          let center := R.slotCenterFor inletCenter a offset
          let flip := R.slotTransverseFlip incoming firstFlip secondFlip a offset
          let F := cubicRestartFrameIso center a flip
          Disjoint (cubicEdgeEndpointVertices (R.source.referenceExploredEdges F))
            (cubicEdgeEndpointVertices (seededBoundaryTargetSupport d a.1 m n)) := by
        simpa using hfresh 0 (by simp)
      have haddsFirst : ∀ e ∈ Q.boundarySupport n,
          (incremented R.source a e : ℝ) = (R.source.lower e : ℝ) + delta := by
        intro e _he
        simpa [Q] using hadds 0 (by simp) e
      have hfirstY : Y ∈ Q.successEvent m n p delta := by
        apply R.source.framedSuccessEvent_of_mem_nextHistoryProfile
          (R.slotCenterFor inletCenter a offset) a
          (R.slotTransverseFlip incoming firstFlip secondFlip a offset)
          p delta (incremented R.source a) X Y hfreshFirst
        · intro e he
          rw [R.source.framedQuery_physicalBoundaryThreshold]
          exact haddsFirst e (by simpa [Q] using he)
        · exact hsuccess.1
        · exact hYnext
      have hstep : RY = RX :=
        step_eq_of_mem_nextHistoryProfile hmn R inletCenter incoming
          firstFlip secondFlip p delta incremented X Y a offset
          hfreshFirst haddsFirst hcurrent hnonneg hYnext
      have hcurrentNext : X ∈ RX.source.historyProfile.event := by
        exact R.source.mem_next_historyProfile
          (Q.restartSupport m n) p (incremented R.source a) X hcurrent hnonneg
      refine ⟨hfirstY, ?_⟩
      change succeedsFrom hmn inletCenter incoming firstFlip secondFlip
        p delta incremented Y RY (offset + 1) rest
      rw [hstep]
      apply ih (R := RX) (offset := offset + 1)
      · intro j hj e
        have hs := hadds (j + 1) (by simp; omega) e
        simpa [RX, Q, List.take_succ_cons, runFrom, Nat.add_assoc] using hs
      · intro j hj
        have hs := hfresh (j + 1) (by simp; omega)
        simpa [RX, Q, List.take_succ_cons, runFrom, Nat.add_assoc,
          Nat.add_comm, Nat.add_left_comm] using hs
      · exact hcurrentNext
      · exact hsuccess.2
      · exact hY

end LaterSiteRuntime

end Percolation
