import Percolation.Critical.AdaptiveDecisionRealization
import Percolation.Critical.AdaptiveSetAnswerSupport
import Percolation.Critical.BondExploration
import Percolation.Critical.ExplorationHistory
import Percolation.Critical.FiniteSiteExplorationCompleteness

/-!
# Incoming-green domination for finite bond explorations

An undirected open edge can be replaced by two independent directed darts.  A non-root vertex is
called green when at least one incoming dart is open.  The boundary-edge exploration then reaches
only green vertices.  This file proves that the resulting history-dependent green answers are
dominated by iid site percolation at density `1 - (1-p)^Delta` when all degrees are at most
`Delta`.

Every directed dart has countably many independent copies.  The physical coupling uses copy zero;
the occurrence counter uses later copies only on malformed histories that query a site repeatedly.
Consequently the upper adaptive kernel is valid on every literal history, not merely histories of
positive probability generated by the intended exploration.
-/

namespace Percolation

open MeasureTheory ProbabilityTheory Classical
open scoped unitInterval

namespace IncomingGreenDomination

variable {V : Type*} [Fintype V] [DecidableEq V]
  (G : SimpleGraph V) [DecidableRel G.Adj]

abbrev Coordinate := FiniteBondExploration.DirectedCoordinate G

/-- The copy-`k` incoming darts at `v`. -/
def incomingDartSupport (v : V) (k : ℕ) : Finset (Coordinate G) :=
  (Finset.univ.filter fun d : G.Dart ↦ d.snd = v).image
    (fun d ↦ Sum.inl (d, k))

@[simp]
theorem mem_incomingDartSupport_iff (v : V) (k : ℕ) (c : Coordinate G) :
    c ∈ incomingDartSupport G v k ↔
      ∃ d : G.Dart, d.snd = v ∧ c = Sum.inl (d, k) := by
  simp [incomingDartSupport, eq_comm]

/-- Number of earlier literal queries of `v`. -/
def vertexOccurrence (history : List (V × Bool)) (v : V) : ℕ :=
  history.countP fun entry ↦ decide (entry.1 = v)

@[simp]
theorem vertexOccurrence_nil (v : V) : vertexOccurrence ([] : List (V × Bool)) v = 0 := by
  simp [vertexOccurrence]

theorem vertexOccurrence_append (left right : List (V × Bool)) (v : V) :
    vertexOccurrence (left ++ right) v =
      vertexOccurrence left v + vertexOccurrence right v := by
  simp [vertexOccurrence, List.countP_append]

@[simp]
theorem vertexOccurrence_append_singleton_same
    (history : List (V × Bool)) (v : V) (b : Bool) :
    vertexOccurrence (history ++ [(v, b)]) v = vertexOccurrence history v + 1 := by
  simp [vertexOccurrence, List.countP_append]

@[simp]
theorem vertexOccurrence_append_singleton_ne
    (history : List (V × Bool)) {u v : V} (huv : u ≠ v) (b : Bool) :
    vertexOccurrence (history ++ [(u, b)]) v = vertexOccurrence history v := by
  simp [vertexOccurrence, List.countP_append, huv]

/-- Coordinate block used by the next answer at a literal history. -/
def answerSupport (history : List (V × Bool)) (v : V) : Finset (Coordinate G) :=
  incomingDartSupport G v (vertexOccurrence history v)

/-- The next site is declared open when one coordinate in its fresh incoming-dart block is open. -/
noncomputable def answer
    (omega : Set (Coordinate G)) (history : List (V × Bool)) (v : V) : Bool :=
  decide (¬ Disjoint (answerSupport G history v : Set (Coordinate G)) omega)

theorem answer_eq_true_iff
    (omega : Set (Coordinate G)) (history : List (V × Bool)) (v : V) :
    answer G omega history v = true ↔
      ¬ Disjoint (answerSupport G history v : Set (Coordinate G)) omega := by
  simp [answer]

/-- Different vertices or different occurrence indices use disjoint incoming-dart blocks. -/
theorem disjoint_incomingDartSupport_of_ne
    {u v : V} {i j : ℕ} (h : u ≠ v ∨ i ≠ j) :
    Disjoint (incomingDartSupport G u i : Set (Coordinate G))
      (incomingDartSupport G v j : Set (Coordinate G)) := by
  rw [Set.disjoint_left]
  intro c hcu hcv
  obtain ⟨d, hdSnd, rfl⟩ := (mem_incomingDartSupport_iff G u i c).mp hcu
  obtain ⟨e, heSnd, heq⟩ := (mem_incomingDartSupport_iff G v j _).mp hcv
  have hpair : (d, i) = (e, j) := Sum.inl.inj heq
  have hde : d = e := congrArg Prod.fst hpair
  have hij : i = j := congrArg Prod.snd hpair
  rcases h with huv | hij'
  · apply huv
    rw [← hdSnd, ← heSnd, hde]
  · exact hij' hij

/-- Every block read by a literal history is disjoint from the fresh block selected after that
history. -/
theorem disjoint_historySupport_answerSupport :
    ∀ (prior suffix : List (V × Bool)) (v : V),
      Disjoint
        (AdaptiveSiteExploration.adaptiveAnswerHistorySupportFrom
          (answerSupport G) prior suffix : Set (Coordinate G))
        (answerSupport G (prior ++ suffix) v : Set (Coordinate G)) := by
  intro prior suffix
  induction suffix generalizing prior with
  | nil =>
      intro v
      simp
  | cons head suffix ih =>
      rcases head with ⟨u, b⟩
      intro v
      simp only [AdaptiveSiteExploration.adaptiveAnswerHistorySupportFrom,
        Finset.coe_union]
      apply Disjoint.union_left
      · apply disjoint_incomingDartSupport_of_ne G
        by_cases huv : u = v
        · subst v
          right
          rw [vertexOccurrence_append]
          simp [vertexOccurrence]
        · exact Or.inl huv
      · simpa [List.append_assoc] using ih (prior ++ [(u, b)]) v

theorem disjoint_adaptiveAnswerHistorySupport_answerSupport
    (history : List (V × Bool)) (v : V) :
    Disjoint
      (AdaptiveSiteExploration.adaptiveAnswerHistorySupport (answerSupport G) history :
        Set (Coordinate G))
      (answerSupport G history v : Set (Coordinate G)) := by
  simpa [AdaptiveSiteExploration.adaptiveAnswerHistorySupport] using
    disjoint_historySupport_answerSupport G [] history v

/-- Answer fibers depend only on the selected incoming-dart block. -/
theorem hasFiniteSetAnswerSupports_answer :
    AdaptiveSiteExploration.HasFiniteSetAnswerSupports (answer G) (answerSupport G) := by
  intro history v b
  intro omega eta hagree
  have hhit :
      (¬ Disjoint (answerSupport G history v : Set (Coordinate G)) omega) ↔
        ¬ Disjoint (answerSupport G history v : Set (Coordinate G)) eta := by
    simp only [Set.not_disjoint_iff]
    constructor
    · rintro ⟨c, hcS, hcOmega⟩
      exact ⟨c, hcS, (hagree c hcS).mp hcOmega⟩
    · rintro ⟨c, hcS, hcEta⟩
      exact ⟨c, hcS, (hagree c hcS).mpr hcEta⟩
  cases b
  · simpa [answer] using not_congr hhit
  · simpa [answer] using hhit

theorem measurableAnswer_answer : AdaptiveSiteExploration.MeasurableAnswer (answer G) :=
  (hasFiniteSetAnswerSupports_answer G).measurableAnswer

/-- The incoming-dart block has one coordinate per neighbor of `v`. -/
theorem card_incomingDartSupport (v : V) (k : ℕ) :
    (incomingDartSupport G v k).card = G.degree v := by
  rw [incomingDartSupport, Finset.card_image_of_injective]
  · have hfiber :
        (Finset.univ.filter fun d : G.Dart ↦ d.snd = v).card =
          (Finset.univ.filter fun d : G.Dart ↦ d.fst = v).card := by
      apply Finset.card_bij (fun d _hd ↦ d.symm)
      · intro d hd
        simpa [SimpleGraph.Dart.symm] using hd
      · intro d₁ _hd₁ d₂ _hd₂ hde
        exact SimpleGraph.Dart.symm_involutive.injective hde
      · intro d hd
        refine ⟨d.symm, ?_, ?_⟩
        · simpa [SimpleGraph.Dart.symm] using hd
        · exact d.symm_symm
    rw [hfiber]
    exact G.dart_fst_fiber_card_eq_degree v
  · intro d e hde
    exact congrArg Prod.fst (Sum.inl.inj hde)

/-- Site density supplied by directed incoming darts when degrees are bounded by `Delta`. -/
def density (p : I) (Delta : ℕ) : ℝ :=
  1 - (1 - (p : ℝ)) ^ Delta

theorem density_nonneg (p : I) (Delta : ℕ) : 0 ≤ density p Delta := by
  unfold density
  exact sub_nonneg.mpr
    (pow_le_one₀ (unitInterval.one_minus_nonneg p) (unitInterval.one_minus_le_one p))

theorem density_le_one (p : I) (Delta : ℕ) : density p Delta ≤ 1 := by
  unfold density
  linarith [pow_nonneg (unitInterval.one_minus_nonneg p) Delta]

/-- Ordinary finite-graph bond connectivity to a target set. -/
def bondHitsTargetEvent (root : V) (target : Finset V) : Set (Set (Sym2 V)) :=
  {omega | ∃ t ∈ target, FiniteBondExploration.BondReachable G root omega t}

theorem dependsOn_bondHitsTargetEvent (root : V) (target : Finset V) :
    DependsOn G.edgeFinset (bondHitsTargetEvent G root target) := by
  intro omega eta hagree
  constructor
  · rintro ⟨t, htTarget, w, hw⟩
    refine ⟨t, htTarget, w, ?_⟩
    intro e he
    exact (hagree e (by simpa using w.edges_subset_edgeSet he)).mp (hw e he)
  · rintro ⟨t, htTarget, w, hw⟩
    refine ⟨t, htTarget, w, ?_⟩
    intro e he
    exact (hagree e (by simpa using w.edges_subset_edgeSet he)).mpr (hw e he)

theorem measurableSet_bondHitsTargetEvent (root : V) (target : Finset V) :
    MeasurableSet (bondHitsTargetEvent G root target) :=
  (dependsOn_bondHitsTargetEvent G root target).measurableSet

/-- Embed physical undirected edges into the enlarged exploration coordinate space. -/
def bondCoordinateEmbedding : Sym2 V ↪ Sum (Sym2 V) ℕ where
  toFun := Sum.inl
  inj' := Sum.inl_injective

theorem projectedBondHitsTargetEvent_eq_preimage
    (root : V) (target : Finset V) :
    FiniteBondExploration.projectedBondHitsTargetEvent G root target =
      (fun omega : Set (Sum (Sym2 V) ℕ) ↦ bondCoordinateEmbedding ⁻¹' omega) ⁻¹'
        bondHitsTargetEvent G root target := by
  rfl

/-- Adding countably many unused coordinates does not change the physical finite bond event. -/
theorem setBernoulli_real_projectedBondHitsTargetEvent_eq
    (p : I) (root : V) (target : Finset V) :
    setBer((Set.univ : Set (Sum (Sym2 V) ℕ)), p).real
        (FiniteBondExploration.projectedBondHitsTargetEvent G root target) =
      setBer((Set.univ : Set (Sym2 V)), p).real
        (bondHitsTargetEvent G root target) := by
  let f : Sym2 V ↪ Sum (Sym2 V) ℕ := bondCoordinateEmbedding
  have hmap := setBernoulli_map_preimage_univ f p
  have hmeas := measurableSet_bondHitsTargetEvent G root target
  rw [← hmap, map_measureReal_apply (measurable_preimage_embedding f) hmeas]
  exact congrArg
    (setBer((Set.univ : Set (Sum (Sym2 V) ℕ)), p)).real
    (projectedBondHitsTargetEvent_eq_preimage G root target).symm

/-- Support obtained after fixing an initial exploration history. -/
def prefixedAnswerSupport (prior history : List (V × Bool)) (v : V) :
    Finset (Coordinate G) :=
  answerSupport G (prior ++ history) v

theorem adaptiveAnswerHistorySupportFrom_prefixedAnswerSupport
    (prior history : List (V × Bool)) :
    AdaptiveSiteExploration.adaptiveAnswerHistorySupportFrom
        (prefixedAnswerSupport G prior) [] history =
      AdaptiveSiteExploration.adaptiveAnswerHistorySupportFrom
        (answerSupport G) prior history := by
  suffices h : ∀ (pref suffix : List (V × Bool)),
      AdaptiveSiteExploration.adaptiveAnswerHistorySupportFrom
          (prefixedAnswerSupport G prior) pref suffix =
        AdaptiveSiteExploration.adaptiveAnswerHistorySupportFrom
          (answerSupport G) (prior ++ pref) suffix by
    simpa using h [] history
  intro pref suffix
  induction suffix generalizing pref with
  | nil => rfl
  | cons head suffix ih =>
      rcases head with ⟨v, b⟩
      simp only [AdaptiveSiteExploration.adaptiveAnswerHistorySupportFrom,
        prefixedAnswerSupport]
      rw [ih]
      simp [List.append_assoc]

theorem hasFiniteSetAnswerSupports_prefixedAnswer (prior : List (V × Bool)) :
    AdaptiveSiteExploration.HasFiniteSetAnswerSupports
      (SiteExploration.prefixedAdaptiveAnswer prior (answer G))
      (prefixedAnswerSupport G prior) := by
  intro history v b
  exact hasFiniteSetAnswerSupports_answer G (prior ++ history) v b

theorem disjoint_prefixedHistorySupport_prefixedAnswerSupport
    (prior history : List (V × Bool)) (v : V) :
    Disjoint
      (AdaptiveSiteExploration.adaptiveAnswerHistorySupport
          (prefixedAnswerSupport G prior) history : Set (Coordinate G))
      (prefixedAnswerSupport G prior history v : Set (Coordinate G)) := by
  rw [AdaptiveSiteExploration.adaptiveAnswerHistorySupport,
    adaptiveAnswerHistorySupportFrom_prefixedAnswerSupport]
  exact disjoint_historySupport_answerSupport G prior history v

/-- A single fresh incoming-dart answer has probability at most
`1 - (1-p)^Delta`. -/
theorem answer_true_probability_le_density
    (p : I) (Delta : ℕ) (hdegree : ∀ v, G.degree v ≤ Delta)
    (history : List (V × Bool)) (v : V) :
    setBer((Set.univ : Set (Coordinate G)), p).real
        {omega : Set (Coordinate G) | answer G omega history v = true} ≤
      density p Delta := by
  have hevent :
      {omega : Set (Coordinate G) | answer G omega history v = true} =
        {omega : Set (Coordinate G) |
          ¬ Disjoint (answerSupport G history v : Set (Coordinate G)) omega} := by
    ext omega
    simp [answer]
  rw [hevent, setBernoulli_real_not_disjoint_finset_univ,
    show (answerSupport G history v).card = G.degree v by
      exact card_incomingDartSupport G v (vertexOccurrence history v)]
  unfold density
  apply sub_le_sub_left
  exact pow_le_pow_of_le_one (unitInterval.one_minus_nonneg p)
    (unitInterval.one_minus_le_one p) (hdegree v)

/-- The incoming-green oracle, after any fixed prior history, is uniformly dominated by iid
site answers at density `1 - (1-p)^Delta`. -/
theorem hasAdaptiveAnswerUpperBoundOn_prefixedAnswer
    (p : I) (Delta : ℕ) (hdegree : ∀ v, G.degree v ≤ Delta)
    (prior : List (V × Bool)) :
    AdaptiveSiteExploration.HasAdaptiveAnswerUpperBoundOn
      setBer((Set.univ : Set (Coordinate G)), p)
      (SiteExploration.prefixedAdaptiveAnswer prior (answer G))
      (fun _history _v ↦ True) (density p Delta) := by
  apply AdaptiveSiteExploration.hasAdaptiveAnswerUpperBoundOn_setBernoulli_of_fresh_support
    p (hasFiniteSetAnswerSupports_prefixedAnswer G prior)
      (fun _history _v ↦ True) (density p Delta)
  · intro history v _h
    exact disjoint_prefixedHistorySupport_prefixedAnswerSupport G prior history v
  · intro history v _h
    exact answer_true_probability_le_density G p Delta hdegree (prior ++ history) v

/-- On a first non-root query, the occurrence-indexed answer reads exactly the physical
copy-zero incoming-green field. -/
theorem answer_eq_configurationAnswer_directedGreen_of_occurrence_zero
    (root v : V) (omega : Set (Coordinate G)) (history : List (V × Bool))
    (hvroot : v ≠ root) (hocc : vertexOccurrence history v = 0) :
    answer G omega history v =
      configurationAnswer (FiniteBondExploration.directedGreenConfiguration G root omega) v := by
  unfold answer configurationAnswer answerSupport
  apply decide_eq_decide.mpr
  rw [Set.not_disjoint_iff]
  simp only [hocc]
  constructor
  · rintro ⟨c, hcSupport, hcOmega⟩
    obtain ⟨d, hdSnd, rfl⟩ :=
      (mem_incomingDartSupport_iff G v 0 c).mp hcSupport
    exact Or.inr ⟨d, hdSnd, hcOmega⟩
  · intro hvGreen
    rcases hvGreen with hvr | ⟨d, hdSnd, hdOpen⟩
    · exact (hvroot hvr).elim
    · exact ⟨Sum.inl (d, 0),
        (mem_incomingDartSupport_iff G v 0 _).mpr ⟨d, hdSnd, rfl⟩, hdOpen⟩

theorem mem_explorationHistoryAccepted_or_rejected_of_mem
    {history : List (V × Bool)} {v : V} {b : Bool}
    (hmem : (v, b) ∈ history) :
    v ∈ explorationHistoryAccepted history ∨
      v ∈ explorationHistoryRejected history := by
  induction history with
  | nil => simp at hmem
  | cons head history ih =>
      rcases head with ⟨u, c⟩
      simp only [List.mem_cons] at hmem
      rcases hmem with hhead | htail
      · cases hhead
        cases b <;> simp [explorationHistoryAccepted, explorationHistoryRejected]
      · have htail' := ih htail
        cases c
        · rcases htail' with haccepted | hrejected
          · exact Or.inl haccepted
          · exact Or.inr (Finset.mem_insert_of_mem hrejected)
        · rcases htail' with haccepted | hrejected
          · exact Or.inl (Finset.mem_insert_of_mem haccepted)
          · exact Or.inr hrejected

/-- A well-formed, history-consistent frontier vertex has not occurred in the recorded history. -/
theorem vertexOccurrence_eq_zero_of_mem_frontier
    {s : SiteExplorationState V} (hwell : s.WellFormed)
    (hconsistent : s.HistoryConsistent) {v : V} (hv : v ∈ s.frontier) :
    vertexOccurrence s.history v = 0 := by
  rw [vertexOccurrence, List.countP_eq_zero]
  intro entry hentry
  rcases entry with ⟨u, b⟩
  by_cases huv : u = v
  · subst u
    have hdecided : v ∈ s.decided := by
      rcases mem_explorationHistoryAccepted_or_rejected_of_mem hentry with
        haccepted | hrejected
      · exact Finset.mem_union_left _ (hconsistent.1 ▸ haccepted)
      · exact Finset.mem_union_right _ (hconsistent.2 ▸ hrejected)
    exact (Finset.disjoint_left.mp hwell.2 hv hdecided).elim
  · simp [huv]

theorem rootedSiteExploration_initial_historyConsistent
    [LinearOrder V] (neighbors : V → Finset V)
    (mem_neighbors : ∀ {x y}, y ∈ neighbors x ↔ G.Adj x y) (root : V) :
    (rootedSiteExploration G neighbors mem_neighbors root).initial.HistoryConsistent := by
  simp [rootedSiteExploration, SiteExplorationState.HistoryConsistent,
    explorationHistoryAccepted, explorationHistoryRejected]

/-- The occurrence-indexed adaptive run and the ordinary run on the physical green field have
identical states at every time. -/
theorem adaptiveState_eq_staticDirectedGreenState
    [LinearOrder V] (neighbors : V → Finset V)
    (mem_neighbors : ∀ {x y}, y ∈ neighbors x ↔ G.Adj x y)
    (root : V) (omega : Set (Coordinate G)) :
    ∀ n,
      ((rootedSiteExploration G neighbors mem_neighbors root).toAdaptive.stateAfter
          (answer G omega) n) =
        (rootedSiteExploration G neighbors mem_neighbors root).stateAfter
          (configurationAnswer
            (FiniteBondExploration.directedGreenConfiguration G root omega)) n := by
  intro n
  induction n with
  | zero => rfl
  | succ n ih =>
      let E := rootedSiteExploration G neighbors mem_neighbors root
      let eta := FiniteBondExploration.directedGreenConfiguration G root omega
      let s := E.toAdaptive.stateAfter (answer G omega) n
      have hwell : s.WellFormed :=
        E.toAdaptive.stateAfter_wellFormed (answer G omega)
          (rootedSiteExploration_initial_wellFormed G neighbors mem_neighbors root) n
      have hconsistent : s.HistoryConsistent :=
        E.toAdaptive.stateAfter_historyConsistent (answer G omega)
          (rootedSiteExploration_initial_historyConsistent G neighbors mem_neighbors root) n
      rw [AdaptiveSiteExploration.stateAfter, SiteExploration.stateAfter, ← ih]
      change E.toAdaptive.step (answer G omega) s =
        E.step (configurationAnswer eta) s
      by_cases hnone : SiteExploration.nextVertex s = none
      · have hfrontier : s.frontier = ∅ :=
          (SiteExploration.nextVertex_eq_none_iff s).mp hnone
        rw [E.toAdaptive.step_eq_self_of_frontier_eq_empty (answer G omega) hfrontier,
          E.step_eq_self_of_frontier_eq_empty (configurationAnswer eta) hfrontier]
      obtain ⟨v, hnext⟩ := Option.ne_none_iff_exists'.mp hnone
      have hvfrontier : v ∈ s.frontier :=
        SiteExploration.mem_frontier_of_nextVertex_eq_some hnext
      have hrootOccupied : root ∈ s.occupied :=
        (E.toAdaptive.stateAfter_openRootedAt (answer G omega) root
          (rootedSiteExploration_initial_openRootedAt G neighbors mem_neighbors root) n).1
      have hvroot : v ≠ root := by
        intro hvr
        subst v
        exact Finset.disjoint_left.mp hwell.2 hvfrontier
          (Finset.mem_union_left _ hrootOccupied)
      have hanswer := answer_eq_configurationAnswer_directedGreen_of_occurrence_zero
        G root v omega s.history hvroot
          (vertexOccurrence_eq_zero_of_mem_frontier hwell hconsistent hvfrontier)
      simp [AdaptiveSiteExploration.step, SiteExploration.step, hnext, hanswer, eta,
        SiteExploration.toAdaptive]

/-- Since the root is already decided, its rooted finite exploration exhausts after the number
of initially undecided vertices, not merely after the coarser `|V|` bound. -/
theorem rootedStateAfter_remaining_frontier_eq_empty
    [LinearOrder V] (neighbors : V → Finset V)
    (mem_neighbors : ∀ {x y}, y ∈ neighbors x ↔ G.Adj x y)
    (root : V) (siteAnswer : V → Bool) :
    let E := rootedSiteExploration G neighbors mem_neighbors root
    (E.stateAfter siteAnswer E.initial.remaining.card).frontier = ∅ := by
  let E := rootedSiteExploration G neighbors mem_neighbors root
  by_contra hne
  have hfrontier :
      (E.stateAfter siteAnswer E.initial.remaining.card).frontier.Nonempty :=
    Finset.nonempty_iff_ne_empty.mpr hne
  have hcard := E.stateAfter_decided_card_eq_add_of_frontier_nonempty siteAnswer
    (rootedSiteExploration_initial_wellFormed G neighbors mem_neighbors root) hfrontier
  have hremaining : E.initial.remaining = Finset.univ.erase root := by
    ext v
    simp [E, rootedSiteExploration, SiteExplorationState.remaining,
      SiteExplorationState.decided]
  have hinitialCard : E.initial.decided.card = 1 := by
    simp [E, rootedSiteExploration, SiteExplorationState.decided]
  have hremainingCard : E.initial.remaining.card = Fintype.card V - 1 := by
    rw [hremaining, Finset.card_erase_of_mem (Finset.mem_univ root)]
    simp
  have hVpos : 0 < Fintype.card V := Fintype.card_pos_iff.mpr ⟨root⟩
  have hstateCard :
      (E.stateAfter siteAnswer E.initial.remaining.card).decided.card = Fintype.card V := by
    calc
      (E.stateAfter siteAnswer E.initial.remaining.card).decided.card =
          E.initial.decided.card + E.initial.remaining.card := hcard
      _ = 1 + (Fintype.card V - 1) := by rw [hinitialCard, hremainingCard]
      _ = Fintype.card V := by omega
  have hdecidedUniv :
      (E.stateAfter siteAnswer E.initial.remaining.card).decided = Finset.univ := by
    apply Finset.eq_of_subset_of_card_le (Finset.subset_univ _)
    simp [hstateCard]
  obtain ⟨v, hvfrontier⟩ := hfrontier
  have hwell := E.stateAfter_wellFormed siteAnswer
    (rootedSiteExploration_initial_wellFormed G neighbors mem_neighbors root)
      E.initial.remaining.card
  exact Finset.disjoint_left.mp hwell.2 hvfrontier
    (hdecidedUniv.symm ▸ Finset.mem_univ v)

/-- At the Bellman depth used by the comparison theorem, the occurrence-indexed adaptive target
event is exactly connectivity in the physical copy-zero incoming-green field. -/
theorem adaptiveTargetHitEvent_eq_directedGreenHitsTargetEvent
    [LinearOrder V] (neighbors : V → Finset V)
    (mem_neighbors : ∀ {x y}, y ∈ neighbors x ↔ G.Adj x y)
    (root : V) (target : Finset V) :
    let E := rootedSiteExploration G neighbors mem_neighbors root
    E.adaptiveTargetHitEvent (answer G) target E.initial.remaining.card =
      FiniteBondExploration.directedGreenHitsTargetEvent G root target := by
  let E := rootedSiteExploration G neighbors mem_neighbors root
  ext omega
  let eta := FiniteBondExploration.directedGreenConfiguration G root omega
  let n := E.initial.remaining.card
  have hstate : E.toAdaptive.stateAfter (answer G omega) n =
      E.stateAfter (configurationAnswer eta) n := by
    exact adaptiveState_eq_staticDirectedGreenState G neighbors mem_neighbors root omega n
  have hfrontier : (E.stateAfter (configurationAnswer eta) n).frontier = ∅ := by
    exact rootedStateAfter_remaining_frontier_eq_empty
      G neighbors mem_neighbors root (configurationAnswer eta)
  have hoccupied :
      ((E.stateAfter (configurationAnswer eta) n).occupied : Set V) =
        siteOpenCluster G eta root := by
    apply E.occupied_eq_siteOpenCluster_of_frontier_eq_empty eta root
    · exact E.stateAfter_openRootedAt (configurationAnswer eta) root
        (rootedSiteExploration_initial_openRootedAt G neighbors mem_neighbors root) n
    · exact E.stateAfter_answersAgree eta
        (rootedSiteExploration_initial_answersAgree G neighbors mem_neighbors
          (by simp [eta, FiniteBondExploration.directedGreenConfiguration])) n
    · exact E.stateAfter_frontierClosed (configurationAnswer eta)
        (rootedSiteExploration_initial_frontierClosed G neighbors mem_neighbors root) n
    · exact hfrontier
  change (∃ t ∈ target, t ∈ (E.toAdaptive.stateAfter (answer G omega) n).occupied) ↔
    ∃ t ∈ target, FiniteBondExploration.GreenReachable G root eta t
  rw [hstate]
  constructor
  · rintro ⟨t, htTarget, htOccupied⟩
    refine ⟨t, htTarget, ?_⟩
    change eta ∈ siteConnectionEvent G root t
    have htOccupiedSet : t ∈
        ((E.stateAfter (configurationAnswer eta) n).occupied : Set V) := htOccupied
    rw [hoccupied] at htOccupiedSet
    exact htOccupiedSet
  · rintro ⟨t, htTarget, htReachable⟩
    refine ⟨t, htTarget, ?_⟩
    change eta ∈ siteConnectionEvent G root t at htReachable
    have htCluster : t ∈ siteOpenCluster G eta root := htReachable
    rw [← hoccupied] at htCluster
    exact htCluster

/-- Incoming-green connectivity is bounded by the iid-site Bellman completion probability at
density `1 - (1-p)^Delta`, with the root forced open on both sides. -/
theorem setBernoulli_directedGreenHitsTarget_le_rootedCompletion
    [LinearOrder V] (neighbors : V → Finset V)
    (mem_neighbors : ∀ {x y}, y ∈ neighbors x ↔ G.Adj x y)
    (p : I) (Delta : ℕ) (hdegree : ∀ v, G.degree v ≤ Delta)
    (root : V) (target : Finset V) :
    let E := rootedSiteExploration G neighbors mem_neighbors root
    setBer((Set.univ : Set (Coordinate G)), p).real
        (FiniteBondExploration.directedGreenHitsTargetEvent G root target) ≤
      E.completionHitProbability (density p Delta) root target E.initial := by
  let E := rootedSiteExploration G neighbors mem_neighbors root
  rw [← adaptiveTargetHitEvent_eq_directedGreenHitsTargetEvent
    G neighbors mem_neighbors root target]
  exact SiteExploration.adaptiveTargetHitEvent_probability_le_rooted_completion
    G neighbors mem_neighbors setBer((Set.univ : Set (Coordinate G)), p)
      (measurableAnswer_answer G) (fun _history _v ↦ True)
      (density p Delta) (density_nonneg p Delta) (density_le_one p Delta) root
      (hasAdaptiveAnswerUpperBoundOn_prefixedAnswer G p Delta hdegree E.initial.history)
      target (fun _history ↦ True.intro)

/-- Finite bond connectivity is bounded by rooted iid-site completion at the classical
directed-edge density `1 - (1-p)^Delta`. -/
theorem setBernoulli_projectedBondHitsTarget_le_rootedCompletion
    [LinearOrder V] (neighbors : V → Finset V)
    (mem_neighbors : ∀ {x y}, y ∈ neighbors x ↔ G.Adj x y)
    (p : I) (Delta : ℕ) (hdegree : ∀ v, G.degree v ≤ Delta)
    (root : V) (target : Finset V) :
    let E := rootedSiteExploration G neighbors mem_neighbors root
    setBer((Set.univ : Set (Sum (Sym2 V) ℕ)), p).real
        (FiniteBondExploration.projectedBondHitsTargetEvent G root target) ≤
      E.completionHitProbability (density p Delta) root target E.initial := by
  let E := rootedSiteExploration G neighbors mem_neighbors root
  exact (FiniteBondExploration.setBernoulli_projectedBondHitsTarget_le_directedGreenHitsTarget
    G p root target).trans
      (setBernoulli_directedGreenHitsTarget_le_rootedCompletion
        G neighbors mem_neighbors p Delta hdegree root target)

/-- Source-facing finite-graph form of the bond-to-site comparison: ordinary bond connectivity
is bounded by iid site connectivity at density `1 - (1-p)^Delta`, conditional on the root being
open (encoded by the rooted completion probability). -/
theorem setBernoulli_bondHitsTarget_le_rootedCompletion
    [LinearOrder V] (neighbors : V → Finset V)
    (mem_neighbors : ∀ {x y}, y ∈ neighbors x ↔ G.Adj x y)
    (p : I) (Delta : ℕ) (hdegree : ∀ v, G.degree v ≤ Delta)
    (root : V) (target : Finset V) :
    let E := rootedSiteExploration G neighbors mem_neighbors root
    setBer((Set.univ : Set (Sym2 V)), p).real
        (bondHitsTargetEvent G root target) ≤
      E.completionHitProbability (density p Delta) root target E.initial := by
  rw [← setBernoulli_real_projectedBondHitsTargetEvent_eq G p root target]
  exact setBernoulli_projectedBondHitsTarget_le_rootedCompletion
    G neighbors mem_neighbors p Delta hdegree root target

/-- Unconditioned finite bond-to-site comparison.  The factor
`1 - (1-p)^Delta` is exactly the probability that the site root is open; retaining it makes the
finite theorem suitable for exhaustion to an ordinary infinite site cluster. -/
theorem density_mul_setBernoulli_bondHitsTarget_le_finiteSiteHitsTarget
    [LinearOrder V] (neighbors : V → Finset V)
    (mem_neighbors : ∀ {x y}, y ∈ neighbors x ↔ G.Adj x y)
    (p : I) (Delta : ℕ) (hdegree : ∀ v, G.degree v ≤ Delta)
    (root : V) (target : Finset V) :
    density p Delta *
        setBer((Set.univ : Set (Sym2 V)), p).real
          (bondHitsTargetEvent G root target) ≤
      finiteBernoulliProbability Finset.univ (density p Delta)
        (SiteExploration.finiteSiteHitsTarget G root target) := by
  let E := rootedSiteExploration G neighbors mem_neighbors root
  calc
    density p Delta *
        setBer((Set.univ : Set (Sym2 V)), p).real
          (bondHitsTargetEvent G root target) ≤
        density p Delta * E.completionHitProbability
          (density p Delta) root target E.initial :=
      mul_le_mul_of_nonneg_left
        (setBernoulli_bondHitsTarget_le_rootedCompletion
          G neighbors mem_neighbors p Delta hdegree root target)
        (density_nonneg p Delta)
    _ = finiteBernoulliProbability Finset.univ (density p Delta)
        (SiteExploration.finiteSiteHitsTarget G root target) := by
      symm
      exact SiteExploration.finiteBernoulliProbability_finiteSiteHitsTarget_eq_mul_rooted_completion
        G neighbors mem_neighbors root target (density p Delta)

end IncomingGreenDomination

end Percolation
