import Percolation.Extensions.LongRangeBranching
import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic

/-!
# Connectivity of one-dimensional long-range percolation

This file develops the deterministic support obstruction and the probability-one support event
needed for Grimmett's Theorem 12.3.  The positive support is encoded by the additive subgroup of
`Z` that it generates; equality with `top` is precisely the invariant form of the source's
`gcd {n : p(n) > 0} = 1` hypothesis.
-/

namespace Percolation

open Filter MeasureTheory ProbabilityTheory
open scoped unitInterval

/-- Signed displacements occurring with positive probability. -/
def longRangePositiveStepSet (p : LongRangeProfile) : Set ℤ :=
  {z | z ≠ 0 ∧ 0 < p z.natAbs}

/-- The additive subgroup generated by the positive-distance support. -/
def longRangeSupportSubgroup (p : LongRangeProfile) : AddSubgroup ℤ :=
  AddSubgroup.closure (longRangePositiveStepSet p)

/-- Aperiodicity of the long-range profile.  For subsets of the positive integers this is
equivalent to saying that their greatest common divisor is one. -/
def LongRangeProfile.IsAperiodic (p : LongRangeProfile) : Prop :=
  longRangeSupportSubgroup p = ⊤

/-- A configuration respects its profile when every open coordinate has positive prescribed
density.  Zero-density coordinates exist in the ambient product space but are absent almost
surely. -/
def longRangeRespectsProfileEvent (p : LongRangeProfile) :
    Set LongRangeConfiguration :=
  {ω | ∀ e ∈ ω, 0 < longRangeEdgeDensity p e}

theorem measurableSet_longRangeRespectsProfileEvent (p : LongRangeProfile) :
    MeasurableSet (longRangeRespectsProfileEvent p) := by
  rw [show longRangeRespectsProfileEvent p =
      ⋂ e : Sym2 ℤ, if longRangeEdgeDensity p e = 0 then
        {ω : LongRangeConfiguration | e ∉ ω} else Set.univ by
    ext ω
    simp only [longRangeRespectsProfileEvent, Set.mem_setOf_eq, Set.mem_iInter]
    constructor
    · intro h e
      split_ifs with he
      · intro heOpen
        have hpos := h e heOpen
        simpa [he] using hpos
      · exact Set.mem_univ ω
    · intro h e heOpen
      have he := h e
      split_ifs at he with hzero
      · exact (he heOpen).elim
      · exact lt_of_le_of_ne (bot_le : 0 ≤ longRangeEdgeDensity p e) (Ne.symm hzero)]
  exact MeasurableSet.iInter fun e ↦ by
    split_ifs
    · exact (measurableSet_coordinateEvent e).compl
    · exact MeasurableSet.univ

/-- Every open coordinate has positive profile density almost surely. -/
theorem longRange_ae_respectsProfile (p : LongRangeProfile) :
    ∀ᵐ ω ∂longRangeMeasure p, ω ∈ longRangeRespectsProfileEvent p := by
  have hcoord : ∀ e : Sym2 ℤ, ∀ᵐ ω ∂longRangeMeasure p,
      e ∈ ω → 0 < longRangeEdgeDensity p e := by
    intro e
    by_cases hzero : longRangeEdgeDensity p e = 0
    · have hreal : (longRangeMeasure p).real {ω | e ∈ ω} = 0 := by
        rw [longRangeMeasure_real_edgeOpen, hzero]
        rfl
      have hmeasure : longRangeMeasure p {ω | e ∈ ω} = 0 := by
        have htoReal : (longRangeMeasure p {ω | e ∈ ω}).toReal = 0 := hreal
        rcases (ENNReal.toReal_eq_zero_iff _).mp htoReal with h | htop
        · exact h
        · exact (measure_ne_top (longRangeMeasure p) {ω | e ∈ ω} htop).elim
      rw [ae_iff]
      simpa [hzero] using hmeasure
    · filter_upwards [] with ω
      intro _he
      exact lt_of_le_of_ne (bot_le : 0 ≤ longRangeEdgeDensity p e) (Ne.symm hzero)
  filter_upwards [ae_all_iff.mpr hcoord] with ω hω
  exact hω

theorem longRangeOpenEdge_displacement_mem_supportSubgroup
    (p : LongRangeProfile) {ω : LongRangeConfiguration}
    (hrespect : ω ∈ longRangeRespectsProfileEvent p) {x y : ℤ}
    (hxy : (longRangeOpenGraph ω).Adj x y) :
    y - x ∈ longRangeSupportSubgroup p := by
  apply AddSubgroup.subset_closure
  have hopen := (longRangeOpenGraph_adj.mp hxy).1
  have hpos := hrespect s(x, y) hopen
  constructor
  · exact sub_ne_zero.mpr hxy.ne.symm
  · simpa [longRangePositiveStepSet, longRangeEdgeDensity,
      longRangeEdgeDistance_mk] using hpos

/-- Every reachable displacement lies in the subgroup generated by the profile support. -/
theorem longRangeReachable_sub_mem_supportSubgroup
    (p : LongRangeProfile) {ω : LongRangeConfiguration}
    (hrespect : ω ∈ longRangeRespectsProfileEvent p) {x y : ℤ}
    (hxy : (longRangeOpenGraph ω).Reachable x y) :
    y - x ∈ longRangeSupportSubgroup p := by
  rcases hxy with ⟨w⟩
  induction w with
  | nil => simp
  | @cons u v z huv w ih =>
      have huvMem := longRangeOpenEdge_displacement_mem_supportSubgroup
        p hrespect huv
      have hsum := (longRangeSupportSubgroup p).add_mem huvMem ih
      convert hsum using 1 <;> ring

theorem longRangeSupportSubgroup_eq_top_of_one_mem
    (p : LongRangeProfile) (h1 : (1 : ℤ) ∈ longRangeSupportSubgroup p) :
    longRangeSupportSubgroup p = ⊤ := by
  rw [AddSubgroup.eq_top_iff']
  intro z
  simpa using (longRangeSupportSubgroup p).zsmul_mem h1 z

/-- A connected profile-respecting configuration forces the support gcd to be one. -/
theorem LongRangeProfile.isAperiodic_of_connected_of_respectsProfile
    (p : LongRangeProfile) {ω : LongRangeConfiguration}
    (hconnected : ω ∈ longRangeConnectedEvent)
    (hrespect : ω ∈ longRangeRespectsProfileEvent p) :
    p.IsAperiodic := by
  have hreach : (longRangeOpenGraph ω).Reachable 0 1 :=
    longRangeOpenGraph_reachable_iff.mpr
      ((mem_longRangeConnectedEvent_iff.mp hconnected) 0 1)
  apply longRangeSupportSubgroup_eq_top_of_one_mem p
  simpa using longRangeReachable_sub_mem_supportSubgroup p hrespect hreach

/-- If the support is periodic, the random graph is almost surely disconnected. -/
theorem longRangeMeasure_connectedEvent_eq_zero_of_not_aperiodic
    (p : LongRangeProfile) (hp : ¬p.IsAperiodic) :
    longRangeMeasure p longRangeConnectedEvent = 0 := by
  have hsubset : longRangeConnectedEvent ⊆
      (longRangeRespectsProfileEvent p)ᶜ := by
    intro ω hconn hrespect
    exact hp (p.isAperiodic_of_connected_of_respectsProfile hconn hrespect)
  apply measure_mono_null hsubset
  exact mem_ae_iff.mp (longRange_ae_respectsProfile p)

theorem longRangeConnectedProbability_eq_zero_of_not_aperiodic
    (p : LongRangeProfile) (hp : ¬p.IsAperiodic) :
    longRangeConnectedProbability p = 0 := by
  rw [longRangeConnectedProbability, measureReal_def,
    longRangeMeasure_connectedEvent_eq_zero_of_not_aperiodic p hp]
  rfl

/-! ### Necessity of divergent total intensity -/

/-- The edge from the origin with a prescribed signed nonzero displacement. -/
def longRangeOriginEdge (s : LongRangeSignedStep) : Sym2 ℤ :=
  s(0, longRangeStepDisplacement s)

@[simp]
theorem longRangeEdgeDistance_originEdge (s : LongRangeSignedStep) :
    longRangeEdgeDistance (longRangeOriginEdge s) = s.1 + 1 := by
  simp [longRangeOriginEdge]

theorem longRangeOriginEdge_injective : Function.Injective longRangeOriginEdge := by
  intro a b h
  change s(0, longRangeStepDisplacement a) =
    s(0, longRangeStepDisplacement b) at h
  rw [Sym2.eq_iff] at h
  rcases h with h | h
  · have hdisp : longRangeStepDisplacement a = longRangeStepDisplacement b := h.2
    rcases a with ⟨m, sa⟩
    rcases b with ⟨n, sb⟩
    cases sa <;> cases sb <;>
      simp [longRangeStepDisplacement] at hdisp ⊢ <;> omega
  · exact (longRangeStepDisplacement_ne_zero a h.2).elim

/-- The origin has no incident open edge. -/
def longRangeOriginIsolatedEvent : Set LongRangeConfiguration :=
  {ω | ∀ s : LongRangeSignedStep, longRangeOriginEdge s ∉ ω}

/-- Origin edges with lengths at most `N`. -/
def longRangeOriginEdgesUpTo (N : ℕ) : Finset (Sym2 ℤ) :=
  (Finset.univ : Finset (Fin N × Bool)).image fun s ↦
    longRangeOriginEdge (s.1.val, s.2)

/-- All origin edges with lengths strictly greater than `N`. -/
def longRangeOriginTailEdges (N : ℕ) : Set (Sym2 ℤ) :=
  {e | ∃ j : ℕ, ∃ b : Bool, e = longRangeOriginEdge (N + j, b)}

def longRangeOriginFiniteClosedEvent (N : ℕ) : Set LongRangeConfiguration :=
  {ω | Disjoint (longRangeOriginEdgesUpTo N : Set (Sym2 ℤ)) ω}

def longRangeOriginTailOpenEvent (N : ℕ) : Set LongRangeConfiguration :=
  {ω | ∃ j : ℕ, ∃ b : Bool, longRangeOriginEdge (N + j, b) ∈ ω}

theorem measurableSet_longRangeOriginFiniteClosedEvent (N : ℕ) :
    MeasurableSet (longRangeOriginFiniteClosedEvent N) :=
  measurableSet_disjoint_finset (longRangeOriginEdgesUpTo N)

theorem measurableSet_longRangeOriginTailOpenEvent (N : ℕ) :
    MeasurableSet (longRangeOriginTailOpenEvent N) := by
  rw [show longRangeOriginTailOpenEvent N =
      ⋃ j : ℕ, ⋃ b : Bool,
        {ω : LongRangeConfiguration | longRangeOriginEdge (N + j, b) ∈ ω} by
    ext ω
    simp [longRangeOriginTailOpenEvent]]
  exact MeasurableSet.iUnion fun j ↦ MeasurableSet.iUnion fun b ↦
    measurableSet_coordinateEvent _

theorem mem_longRangeOriginEdgesUpTo_iff (N : ℕ) (e : Sym2 ℤ) :
    e ∈ longRangeOriginEdgesUpTo N ↔
      ∃ m < N, ∃ b : Bool, e = longRangeOriginEdge (m, b) := by
  rw [longRangeOriginEdgesUpTo, Finset.mem_image]
  constructor
  · rintro ⟨s, _hs, rfl⟩
    exact ⟨s.1.val, s.1.isLt, s.2, rfl⟩
  · rintro ⟨m, hm, b, rfl⟩
    exact ⟨(⟨m, hm⟩, b), Finset.mem_univ _, rfl⟩

theorem disjoint_longRangeOriginEdgesUpTo_tail (N : ℕ) :
    Disjoint (longRangeOriginEdgesUpTo N : Set (Sym2 ℤ))
      (longRangeOriginTailEdges N) := by
  rw [Set.disjoint_left]
  intro e heFinite heTail
  rcases (mem_longRangeOriginEdgesUpTo_iff N e).mp heFinite with
    ⟨m, hm, b, rfl⟩
  rcases heTail with ⟨j, c, heq⟩
  have hstep := longRangeOriginEdge_injective heq
  have hval := congrArg Prod.fst hstep
  simp at hval
  omega

theorem longRangeOriginIsolatedEvent_eq_finite_inter_tailCompl (N : ℕ) :
    longRangeOriginIsolatedEvent =
      longRangeOriginFiniteClosedEvent N ∩
        (longRangeOriginTailOpenEvent N)ᶜ := by
  ext ω
  simp only [longRangeOriginIsolatedEvent, longRangeOriginFiniteClosedEvent,
    longRangeOriginTailOpenEvent, Set.mem_setOf_eq, Set.mem_inter_iff,
    Set.mem_compl_iff, not_exists, Set.disjoint_left]
  constructor
  · intro h
    constructor
    · intro e he hOpen
      rcases (mem_longRangeOriginEdgesUpTo_iff N e).mp he with ⟨m, _hm, b, rfl⟩
      exact h (m, b) hOpen
    · intro j b
      exact h (N + j, b)
  · rintro ⟨hfinite, htail⟩ ⟨m, b⟩
    by_cases hm : m < N
    · intro hOpen
      exact hfinite
        ((mem_longRangeOriginEdgesUpTo_iff N _).mpr ⟨m, hm, b, rfl⟩) hOpen
    · let j := m - N
      have hmj : N + j = m := by dsimp [j]; omega
      simpa [hmj] using htail j b

theorem indepSet_longRangeOriginFinite_tailCompl
    (p : LongRangeProfile) (N : ℕ) :
    IndepSet (longRangeOriginFiniteClosedEvent N)
      (longRangeOriginTailOpenEvent N)ᶜ (longRangeMeasure p) := by
  change IndepSet _ _ (inhomogeneousSetBernoulli (longRangeEdgeDensity p))
  have hindep := indep_generateFrom_coordinateEvents_inhomogeneous
    (longRangeEdgeDensity p) (disjoint_longRangeOriginEdgesUpTo_tail N)
  apply hindep.indepSet_of_measurableSet
  · have hdep : DependsOn (longRangeOriginEdgesUpTo N)
        (longRangeOriginFiniteClosedEvent N) := by
      intro ω η h
      simp only [longRangeOriginFiniteClosedEvent, Set.mem_setOf_eq, Set.disjoint_left]
      exact forall_congr' fun e ↦ forall_congr' fun he ↦ not_congr (h e he)
    exact hdep.measurableSet_generateFrom_coordinateEvents Set.Subset.rfl
  · have htail : MeasurableSet[
        MeasurableSpace.generateFrom
          (coordinateEvents (longRangeOriginTailEdges N))]
        (longRangeOriginTailOpenEvent N) := by
      rw [show longRangeOriginTailOpenEvent N =
        ⋃ j : ℕ, ⋃ b : Bool,
          {ω : LongRangeConfiguration | longRangeOriginEdge (N + j, b) ∈ ω} by
        ext ω
        simp [longRangeOriginTailOpenEvent]]
      exact MeasurableSet.iUnion fun j ↦ MeasurableSet.iUnion fun b ↦
        MeasurableSpace.measurableSet_generateFrom
          ⟨longRangeOriginEdge (N + j, b), ⟨j, b, rfl⟩, rfl⟩
    exact htail.compl

theorem longRangeMeasure_real_originFiniteClosedEvent_pos
    (p : LongRangeProfile) (hp : p.IsStrict) (N : ℕ) :
    0 < (longRangeMeasure p).real (longRangeOriginFiniteClosedEvent N) := by
  rw [longRangeOriginFiniteClosedEvent,
    longRangeMeasure_real_disjoint_finset]
  apply Finset.prod_pos
  intro e he
  rcases (mem_longRangeOriginEdgesUpTo_iff N e).mp he with ⟨m, _hm, b, rfl⟩
  rw [longRangeEdgeDistance_originEdge]
  have hlt := hp (m + 1) (by omega)
  linarith [unitInterval.nonneg (p (m + 1))]

def longRangeOriginLengthOpenEvent (m : ℕ) : Set LongRangeConfiguration :=
  {ω | ∃ b : Bool, longRangeOriginEdge (m, b) ∈ ω}

theorem longRangeMeasure_real_originLengthOpenEvent_le
    (p : LongRangeProfile) (m : ℕ) :
    (longRangeMeasure p).real (longRangeOriginLengthOpenEvent m) ≤
      2 * (p (m + 1) : ℝ) := by
  rw [show longRangeOriginLengthOpenEvent m =
      ⋃ b : Bool, {ω : LongRangeConfiguration |
        longRangeOriginEdge (m, b) ∈ ω} by
    ext ω
    simp [longRangeOriginLengthOpenEvent]]
  calc
    (longRangeMeasure p).real
        (⋃ b : Bool, {ω : LongRangeConfiguration |
          longRangeOriginEdge (m, b) ∈ ω}) ≤
        ∑ b : Bool, (longRangeMeasure p).real
          {ω : LongRangeConfiguration | longRangeOriginEdge (m, b) ∈ ω} :=
      measureReal_iUnion_fintype_le _
    _ = ∑ _b : Bool, (p (m + 1) : ℝ) := by
      apply Finset.sum_congr rfl
      intro b _hb
      rw [longRangeMeasure_real_edgeOpen, longRangeEdgeDensity,
        longRangeEdgeDistance_originEdge]
    _ = 2 * (p (m + 1) : ℝ) := by simp

theorem longRangeMeasure_real_originTailOpenEvent_le
    (p : LongRangeProfile) (N : ℕ)
    (hsum : Summable fun n : ℕ ↦ (p n : ℝ)) :
    (longRangeMeasure p).real (longRangeOriginTailOpenEvent N) ≤
      ∑' j : ℕ, 2 * (p (N + j + 1) : ℝ) := by
  rw [show longRangeOriginTailOpenEvent N =
      ⋃ j : ℕ, longRangeOriginLengthOpenEvent (N + j) by
    ext ω
    simp [longRangeOriginTailOpenEvent, longRangeOriginLengthOpenEvent]]
  apply measureReal_iUnion_nat_le_tsum_of_le
  · intro j
    exact mul_nonneg (by norm_num) (unitInterval.nonneg _)
  · exact (hsum.comp_injective (fun a b h ↦ by omega)).mul_left 2
  · intro j
    exact longRangeMeasure_real_originLengthOpenEvent_le p (N + j)

/-- If the total edge intensity is summable and all edge probabilities are below one, the
origin is isolated with positive probability. -/
theorem longRangeMeasure_real_originIsolatedEvent_pos_of_summable
    (p : LongRangeProfile) (hp : p.IsStrict)
    (hsum : Summable fun n : ℕ ↦ (p n : ℝ)) :
    0 < (longRangeMeasure p).real longRangeOriginIsolatedEvent := by
  let f : ℕ → ℝ := fun n ↦ 2 * (p (n + 1) : ℝ)
  have hfsum : Summable f :=
    (hsum.comp_injective (fun a b h ↦ by omega)).mul_left 2
  have htail : Tendsto (fun N : ℕ ↦ ∑' j : ℕ, f (j + N)) atTop (nhds 0) :=
    _root_.tendsto_sum_nat_add f
  obtain ⟨N, hN⟩ := Metric.tendsto_atTop.1 htail 1 zero_lt_one
  have htailLt : ∑' j : ℕ, 2 * (p (N + j + 1) : ℝ) < 1 := by
    have hN' := hN N (le_refl N)
    rw [Real.dist_eq, sub_zero, abs_of_nonneg] at hN'
    · simpa only [f, add_comm, add_left_comm, add_assoc] using hN'
    · exact tsum_nonneg fun j ↦
        mul_nonneg (by norm_num) (unitInterval.nonneg _)
  have hopenLt :
      (longRangeMeasure p).real (longRangeOriginTailOpenEvent N) < 1 :=
    (longRangeMeasure_real_originTailOpenEvent_le p N hsum).trans_lt htailLt
  have htailComplPos :
      0 < (longRangeMeasure p).real (longRangeOriginTailOpenEvent N)ᶜ := by
    rw [measureReal_compl (measurableSet_longRangeOriginTailOpenEvent N), probReal_univ]
    linarith
  rw [longRangeOriginIsolatedEvent_eq_finite_inter_tailCompl N]
  have hfactor := (indepSet_longRangeOriginFinite_tailCompl p N).measure_inter_eq_mul
  have hfactorReal := congrArg ENNReal.toReal hfactor
  rw [ENNReal.toReal_mul] at hfactorReal
  rw [show (longRangeMeasure p).real
      (longRangeOriginFiniteClosedEvent N ∩ (longRangeOriginTailOpenEvent N)ᶜ) =
        (longRangeMeasure p).real (longRangeOriginFiniteClosedEvent N) *
          (longRangeMeasure p).real (longRangeOriginTailOpenEvent N)ᶜ by
    simpa [Measure.real] using hfactorReal]
  exact mul_pos (longRangeMeasure_real_originFiniteClosedEvent_pos p hp N)
    htailComplPos

theorem longRangeOriginIsolatedEvent_disjoint_connectedEvent :
    Disjoint longRangeOriginIsolatedEvent longRangeConnectedEvent := by
  rw [Set.disjoint_left]
  intro ω hisolated hconnected
  have hconn01 := (mem_longRangeConnectedEvent_iff.mp hconnected) 0 1
  have hreach := longRangeOpenGraph_reachable_iff.mpr hconn01
  rcases hreach with ⟨w⟩
  cases w with
  | @cons _ v z h0v tail =>
      have hv0 : v ≠ 0 := h0v.ne.symm
      let s := longRangeStepOfNonzero v hv0
      have hedge : longRangeOriginEdge s = s(0, v) := by
        rw [longRangeOriginEdge]
        congr 1
        exact longRangeStepDisplacement_stepOfNonzero v hv0
      exact hisolated s (hedge.symm ▸ (longRangeOpenGraph_adj.mp h0v).1)

/-- A summable total intensity prevents almost-sure connectedness. -/
theorem longRangeConnectedProbability_lt_one_of_summable
    (p : LongRangeProfile) (hp : p.IsStrict)
    (hsum : Summable fun n : ℕ ↦ (p n : ℝ)) :
    longRangeConnectedProbability p < 1 := by
  have hiso := longRangeMeasure_real_originIsolatedEvent_pos_of_summable p hp hsum
  have hsumProb : (longRangeMeasure p).real
      (longRangeOriginIsolatedEvent ∪ longRangeConnectedEvent) =
        (longRangeMeasure p).real longRangeOriginIsolatedEvent +
          (longRangeMeasure p).real longRangeConnectedEvent :=
    measureReal_union longRangeOriginIsolatedEvent_disjoint_connectedEvent
      measurableSet_longRangeConnectedEvent
  have hunion : (longRangeMeasure p).real
      (longRangeOriginIsolatedEvent ∪ longRangeConnectedEvent) ≤ 1 := measureReal_le_one
  rw [hsumProb] at hunion
  dsimp [longRangeConnectedProbability]
  linarith

end Percolation
