import Percolation.Critical.HalfSpaceBricks
import Percolation.Critical.SiteExplorationDomination
import Percolation.Planar.Crossings
import Percolation.Planar.CrossingMenger
import Percolation.Core.EdgeMenger
import Percolation.Core.EdgeMengerToSet
import Percolation.Bernoulli.SequentialDomination
import Percolation.Bernoulli.SequentialDominationCountable
import Percolation.Critical.ExplorationLaw
import Percolation.Critical.StaticBlockTranslation
import Percolation.Critical.StaticBlockAdjacency
import Percolation.Critical.StaticBlockPath
import Percolation.Bernoulli.FiniteRangeVariance
import Percolation.Critical.RegionTranslation
import Percolation.Critical.RegionSymmetry
import Percolation.Critical.SiteSymmetry

/-! Transitive axiom audit for the current Chapter 7 infrastructure checkpoint. -/

#print axioms Percolation.dependsOn_halfSpaceBrickGoodEvent
#print axioms Percolation.continuous_halfSpaceBrickGoodProbability
#print axioms Percolation.epsilonGoodBlockLaw_kDependent
#print axioms Percolation.continuous_seedConnectionProbability
#print axioms Percolation.cubicDilatedThickening_eq_minkowskiSum
#print axioms Percolation.slabCriticalProbability_antitone
#print axioms Percolation.cubicCriticalProbability_le_slabCriticalProbability
#print axioms Percolation.cubicTranslationConfigurationPullback_hasInfiniteOpenClusterInVertices_iff
#print axioms Percolation.regionHasInfiniteClusterProbability_translate
#print axioms Percolation.regionCriticalProbability_translate
#print axioms Percolation.hasOpenPathOfLengthAtLeastWithinVertices_graphIso_iff
#print axioms Percolation.cubicGraphIsoConfigurationPullback_hasInfiniteOpenClusterInVertices_iff
#print axioms Percolation.regionHasInfiniteClusterProbability_graphIso
#print axioms Percolation.regionCriticalProbability_graphIso
#print axioms Percolation.siteGraphIsoConfigurationPullback_mem_siteConnectionEvent_iff
#print axioms Percolation.siteGraphIsoConfigurationPullback_hasInfiniteSiteCluster_iff
#print axioms Percolation.siteTheta_graphIso
#print axioms Percolation.siteCriticalProbability_graphIso
#print axioms Percolation.siteExploration_infinite_probability_pos_of_dominates
#print axioms Percolation.stochasticallyDominates_iff_measureReal_le
#print axioms Percolation.HasMonotoneCoupling.stochasticallyDominates
#print axioms Percolation.SiteExploration.reachable_between_of_mem_occupiedLimit
#print axioms Percolation.dependsOn_siteSquareRectangleCrossingEvent
#print axioms Percolation.hasEdgeDisjointSquareRectangleCrossings_iff_isEdgeReachableBetweenFinsets
#print axioms Percolation.mem_interiorDepth_squareRectangleCrossingEvent_iff
#print axioms Percolation.mem_interiorDepth_squareRectangleCrossingEvent_iff_le_max
#print axioms Percolation.bernoulliBondMeasure_real_maxCrossings_le_le
#print axioms Percolation.dependsOn_largeCrossingClusterEvent
#print axioms Percolation.dependsOn_secondMacroscopicClusterEvent
#print axioms Percolation.EdgeMenger.isEdgeReachable_iff_exists_pairwise_edgeDisjoint_paths
#print axioms Percolation.EdgeMenger.isEdgeReachableToFinset_iff_exists_pairwise_edgeDisjoint_walks
#print axioms Percolation.EdgeMenger.isEdgeReachableBetweenFinsets_iff_exists_pairwise_edgeDisjoint_walks
#print axioms Percolation.iidBoolEventMass_le_of_hasSequentialLowerBound
#print axioms Percolation.finiteSequentialLowerBound_stochasticallyDominates
#print axioms Percolation.finiteCylinder_measureReal_le_of_prefixSequential
#print axioms Percolation.infinite_siteSet_probability_eq_one_of_prefixSequential
#print axioms Percolation.infinite_siteSet_probability_pos_of_prefixSequential
#print axioms Percolation.SiteExploration.measurable_occupiedLimit_configurationAnswer
#print axioms Percolation.SiteExploration.occupiedLimit_infinite_probability_pos_of_prefixLowerBound
#print axioms Percolation.finiteBoxGraphLargestComponent_map_translation
#print axioms Percolation.finiteBoxGraph_isEpsilonGood_translation_iff
#print axioms Percolation.epsilonGoodBlockLaw_map_cubicSiteTranslationPullback
#print axioms Percolation.exists_cubicWalk_prefix_to_level_of_end_le
#print axioms Percolation.exists_cubicWalk_prefix_to_level_of_le_end
#print axioms Percolation.finiteBoxGraphLargestComponents_inter_of_good_step
#print axioms Percolation.finiteBoxGraphLargestComponents_inter_of_mem_goodBoxEvents
#print axioms Percolation.finiteBoxGraphComponentVertices_reachable_cubicOpenGraph
#print axioms Percolation.epsilonGoodBlockClusterVertices_reachable_of_good_walk
#print axioms Percolation.epsilonGoodBlockCluster_isCrossing_of_mem_goodBoxEvent
#print axioms Percolation.exists_cubicOpenGraph_reachable_between_faces_of_good_walk
#print axioms Percolation.exists_connectionEvent_between_faces_of_good_walk
#print axioms Percolation.variance_finset_average_le_of_finite_covariance_neighborhood
#print axioms Percolation.measure_average_deviation_le_of_finite_covariance_neighborhood
