import Percolation.Critical.HalfSpaceBricks
import Percolation.Critical.DynamicSteeringSymmetry
import Percolation.Critical.AdaptiveAnswerHistory
import Percolation.Critical.AdaptiveAnswerSupport
import Percolation.Critical.DynamicBlockAnswerLaw
import Percolation.Critical.DynamicRestartPartition
import Percolation.Critical.DynamicRevealCells
import Percolation.Critical.DynamicExploredRegion
import Percolation.Critical.DynamicScheduleCells
import Percolation.Critical.DynamicRevealFreshness
import Percolation.Critical.DynamicProgramSupport
import Percolation.Critical.AdaptiveQueryDomination
import Percolation.Critical.AdaptiveDecisionTree
import Percolation.Critical.AdaptiveDecisionOutcome
import Percolation.Critical.AdaptiveDecisionRealization
import Percolation.Critical.AdaptiveTargetExhaustion
import Percolation.Critical.AdaptiveRegionShells
import Percolation.Critical.AdaptiveSiteExplorationTheorem
import Percolation.Critical.FiniteExplorationTermination
import Percolation.Critical.FiniteSiteExplorationCompleteness
import Percolation.Critical.FiniteExplorationBellman
import Percolation.Critical.SiteExplorationDomination
import Percolation.Planar.Crossings
import Percolation.Planar.CrossingMenger
import Percolation.Core.EdgeMenger
import Percolation.Core.EdgeMengerToSet
import Percolation.Bernoulli.SequentialDomination
import Percolation.Bernoulli.SequentialDominationCountable
import Percolation.Bernoulli.LSSParameters
import Percolation.Bernoulli.LSSDilution
import Percolation.Bernoulli.SequentialDominationEvents
import Percolation.Bernoulli.LSSDilutionSequential
import Percolation.Bernoulli.LSSInduction
import Percolation.Bernoulli.TailZeroOne
import Percolation.Critical.ExplorationLaw
import Percolation.Critical.StaticBlockTranslation
import Percolation.Critical.StaticBlockAdjacency
import Percolation.Critical.StaticBlockPath
import Percolation.Bernoulli.FiniteRangeVariance
import Percolation.Critical.RegionTranslation
import Percolation.Critical.RegionSymmetry
import Percolation.Critical.FiniteSlabLowerBound
import Percolation.Critical.FiniteSlabTLowerBound
import Percolation.Critical.StaticRenormalizationFromSlab
import Percolation.Critical.InfiniteClusterZeroOne
import Percolation.Critical.BoundaryContacts
import Percolation.Critical.BoundaryOrthants
import Percolation.Critical.SeedAmplification
import Percolation.Critical.RestartSprinkling
import Percolation.Critical.RestartGeometry
import Percolation.Critical.DynamicBlockGeometry
import Percolation.Critical.DynamicRevealBudget
import Percolation.Critical.DynamicSteering
import Percolation.Critical.RootedSiteExploration
import Percolation.Critical.AdaptiveExploration
import Percolation.Critical.DynamicBlockCertificate
import Percolation.Critical.BlockSuccessComposition
import Percolation.Critical.DynamicBlockParameters
import Percolation.Critical.ExplorationHistory
import Percolation.Bernoulli.CouplingSymmetry
import Percolation.Critical.SiteSymmetry
import Percolation.Critical.InfiniteClusterDensity
import Percolation.Critical.StaticCoalescence
import Percolation.Critical.StaticGoodAssembly
import Percolation.Critical.StaticLargeCrossing
import Percolation.Critical.SlabConnectivity
import Percolation.Critical.StaticSecondCluster
import Percolation.Critical.StaticAnnularPeeling
import Percolation.Critical.StaticLogInset
import Percolation.Critical.HalfSpaceCriticalAssembly
import Percolation.Critical.SlabLimitAssembly

/-! Transitive axiom audit for the current Chapter 7 infrastructure checkpoint. -/

#print axioms Percolation.dependsOn_halfSpaceBrickGoodEvent
#print axioms Percolation.continuous_halfSpaceBrickGoodProbability
#print axioms Percolation.epsilonGoodBlockLaw_kDependent
#print axioms Percolation.continuous_seedConnectionProbability
#print axioms Percolation.cubicDilatedThickening_eq_minkowskiSum
#print axioms Percolation.slabCriticalProbability_antitone
#print axioms Percolation.cubicCriticalProbability_le_slabCriticalProbability
#print axioms Percolation.cubicTranslationConfigurationPullback_hasInfiniteOpenClusterInVertices_iff
#print axioms Percolation.regionHasInfiniteClusterProbability_translate
#print axioms Percolation.regionCriticalProbability_translate
#print axioms Percolation.hasOpenPathOfLengthAtLeastWithinVertices_graphIso_iff
#print axioms Percolation.cubicGraphIsoConfigurationPullback_hasInfiniteOpenClusterInVertices_iff
#print axioms Percolation.regionHasInfiniteClusterProbability_graphIso
#print axioms Percolation.regionCriticalProbability_graphIso
#print axioms Percolation.siteGraphIsoConfigurationPullback_mem_siteConnectionEvent_iff
#print axioms Percolation.siteGraphIsoConfigurationPullback_hasInfiniteSiteCluster_iff
#print axioms Percolation.siteTheta_graphIso
#print axioms Percolation.siteCriticalProbability_graphIso
#print axioms Percolation.siteExploration_infinite_probability_pos_of_dominates
#print axioms Percolation.stochasticallyDominates_iff_measureReal_le
#print axioms Percolation.HasMonotoneCoupling.stochasticallyDominates
#print axioms Percolation.SiteExploration.reachable_between_of_mem_occupiedLimit
#print axioms Percolation.SiteExploration.step_openRootedAt
#print axioms Percolation.SiteExploration.hasInfiniteSiteCluster_occupiedLimit_of_infinite
#print axioms Percolation.dependsOn_siteSquareRectangleCrossingEvent
#print axioms Percolation.hasEdgeDisjointSquareRectangleCrossings_iff_isEdgeReachableBetweenFinsets
#print axioms Percolation.mem_interiorDepth_squareRectangleCrossingEvent_iff
#print axioms Percolation.mem_interiorDepth_squareRectangleCrossingEvent_iff_le_max
#print axioms Percolation.bernoulliBondMeasure_real_maxCrossings_le_le
#print axioms Percolation.dependsOn_largeCrossingClusterEvent
#print axioms Percolation.dependsOn_secondMacroscopicClusterEvent
#print axioms Percolation.EdgeMenger.isEdgeReachable_iff_exists_pairwise_edgeDisjoint_paths
#print axioms Percolation.EdgeMenger.isEdgeReachableToFinset_iff_exists_pairwise_edgeDisjoint_walks
#print axioms Percolation.EdgeMenger.isEdgeReachableBetweenFinsets_iff_exists_pairwise_edgeDisjoint_walks
#print axioms Percolation.iidBoolEventMass_le_of_hasSequentialLowerBound
#print axioms Percolation.finiteSequentialLowerBound_stochasticallyDominates
#print axioms Percolation.finiteCylinder_measureReal_le_of_prefixSequential
#print axioms Percolation.infinite_siteSet_probability_eq_one_of_prefixSequential
#print axioms Percolation.infinite_siteSet_probability_pos_of_prefixSequential
#print axioms Percolation.SiteExploration.measurable_occupiedLimit_configurationAnswer
#print axioms Percolation.SiteExploration.occupiedLimit_infinite_probability_pos_of_prefixLowerBound
#print axioms Percolation.SiteExploration.occupiedLimit_hasInfiniteSiteCluster_probability_pos_of_prefixLowerBound
#print axioms Percolation.siteExploration_infinite_probability_pos
#print axioms Percolation.finiteBoxGraphLargestComponent_map_translation
#print axioms Percolation.finiteBoxGraph_isEpsilonGood_translation_iff
#print axioms Percolation.epsilonGoodBlockLaw_map_cubicSiteTranslationPullback
#print axioms Percolation.exists_cubicWalk_prefix_to_level_of_end_le
#print axioms Percolation.exists_cubicWalk_prefix_to_level_of_le_end
#print axioms Percolation.finiteBoxGraphLargestComponents_inter_of_good_step
#print axioms Percolation.finiteBoxGraphLargestComponents_inter_of_mem_goodBoxEvents
#print axioms Percolation.finiteBoxGraphComponentVertices_reachable_cubicOpenGraph
#print axioms Percolation.epsilonGoodBlockClusterVertices_reachable_of_good_walk
#print axioms Percolation.epsilonGoodBlockCluster_isCrossing_of_mem_goodBoxEvent
#print axioms Percolation.exists_cubicOpenGraph_reachable_between_faces_of_good_walk
#print axioms Percolation.exists_connectionEvent_between_faces_of_good_walk
#print axioms Percolation.variance_finset_average_le_of_finite_covariance_neighborhood
#print axioms Percolation.measure_average_deviation_le_of_finite_covariance_neighborhood
#print axioms Percolation.disjoint_cubicTranslation_image_edgeSets_of_far
#print axioms Percolation.covariance_translatedCylinderIndicator_eq_zero_of_far
#print axioms Percolation.bernoulliBondMeasure_real_infiniteClusterVertexDensity_deviation_le_of_approx
#print axioms Percolation.infiniteClusterVertexDensity_measureReal_tendsto_zero
#print axioms Percolation.mem_denseInfiniteClusterVertexEvent_iff_card
#print axioms Percolation.denseInfiniteClusterVertexEvent_probability_tendsto_one
#print axioms Percolation.exists_open_walk_to_cubicBoxSurface_in_box_of_mem
#print axioms Percolation.hasInfiniteOpenClusterFrom_mem_connectionToBoxSurfaceEvent
#print axioms Percolation.connectionEventIn_of_infinite_of_not_twoArm
#print axioms Percolation.infiniteClusterCoalescenceEvent_compl_subset_iUnion_twoArm
#print axioms Percolation.bernoulliBondMeasure_real_infiniteClusterCoalescenceEvent_compl_le_sum
#print axioms Percolation.infiniteClusterCoalescenceEvent_probability_tendsto_one_of_twoArm_bound
#print axioms Percolation.measureReal_peeling_le_pow_mul
#print axioms Percolation.measureReal_event_le_pow_of_peeling
#print axioms Percolation.finiteBoxGraphComponentCard_le_boxCard_of_diameter_lt
#print axioms Percolation.FiniteBoxGraph.isEpsilonGood_of_largeCrossing_of_noSecondMacroscopic
#print axioms Percolation.epsilonGoodBoxEvent_compl_subset_largeCrossing_compl_union_secondMacroscopic
#print axioms Percolation.one_sub_bernoulliBondMeasure_real_epsilonGoodBoxEvent_le
#print axioms Percolation.epsilonGoodBox_probability_tendsto_one_of_largeCrossing_of_second
#print axioms Percolation.walk_support_subset_cubicMetricBox_of_edges
#print axioms Percolation.finiteBoxOpenGraph_reachable_of_mem_connectionEventIn
#print axioms Percolation.measurableSet_innerInfiniteClusterReachesFaceEvent
#print axioms Percolation.mem_largeCrossingClusterEvent_of_dense_of_coalescence_of_allFaces
#print axioms Percolation.bernoulliBondMeasure_prod_le_real_biInter_fkg_of_decreasing
#print axioms Percolation.cubicGraphIsoConfigurationPullback_hasInfiniteOpenClusterFrom_iff
#print axioms Percolation.cubicGraphIsoConfigurationPullback_mem_connectionEventIn_iff
#print axioms Percolation.cubicCoordinatePermutation_image_cubicBoxEdges_eq
#print axioms Percolation.innerInfiniteClusterReachesFaceProbability_permutation
#print axioms Percolation.prod_complFaceProbabilities_le_innerHasInfiniteClusterVertexEvent_compl
#print axioms Percolation.one_sub_referenceFaceProbability_tendsto_zero
#print axioms Percolation.allInnerInfiniteClusterFacesEvent_probability_tendsto_one
#print axioms Percolation.allInnerInfiniteClusterFacesEvent_probability_tendsto_one_of_radii
#print axioms Percolation.largeCrossingCluster_probability_tendsto_one_of_coalescence
#print axioms Percolation.mem_finiteThickSlabSVertices_iff
#print axioms Percolation.mem_finiteThickSlabTVertices_iff
#print axioms Percolation.measurableSet_finiteThickSlabSConnectionEvent
#print axioms Percolation.finiteThickSlabSConnectionEvent_self
#print axioms Percolation.mem_slabCornerBoxVertices_iff
#print axioms Percolation.slabCornerVertex_mem
#print axioms Percolation.measurableSet_slabCornerConnectionEvent
#print axioms Percolation.slabCornerConnection_lowerBound_pow_four
#print axioms Percolation.measurableSet_allSlabCornersConnectedEvent
#print axioms Percolation.bernoulliBondMeasure_real_mul_pow_card_le_of_inter_openEdgeSet_subset
#print axioms Percolation.slabCornersConnected_probability_ge_of_fixedBridge
#print axioms Percolation.measurableSet_upwardDistanceAtMost
#print axioms Percolation.couplingMeasure_upwardDistance_le
#print axioms Percolation.IsIncreasingEvent.bernoulliBondMeasure_real_upwardDistanceAtMost_le
#print axioms Percolation.slabCornersConnected_probability_ge_of_boundedRepair
#print axioms Percolation.exists_cubicWalk_length_eq_l1Dist_support_between
#print axioms Percolation.cubicL1Dist_le_sub_two_mul_of_mem_slabCorner_of_agree_first_two
#print axioms Percolation.exists_transverse_cubicPath_in_slabCorner
#print axioms Percolation.mem_upwardDistanceAtMost_connectionWithin_slabCorner_of_agree_first_two
#print axioms Percolation.mem_projectCubicWalkFirstTwo_support_iff
#print axioms Percolation.projectCubicWalkFirstTwo_support_inter_iff
#print axioms Percolation.upwardDistanceAtMost_mono_radius
#print axioms Percolation.mem_upwardDistanceAtMost_connectionWithinVertices_trans
#print axioms Percolation.mem_upwardDistanceAtMost_connectionWithin_slabCorner_of_projected_inter
#print axioms Percolation.mem_upwardDistanceAtMost_allSlabCornersConnectedEvent_of_chain
#print axioms Percolation.mem_upwardDistanceAtMost_allSlabCornersConnectedEvent_of_projected_chain
#print axioms Percolation.mem_slabCornerConnectionEvent_iff_nonempty_witness
#print axioms Percolation.mem_allSlabCornerConnectionEvents_iff_nonempty_witnessFamily
#print axioms Percolation.SlabCornerConnectionWitnessFamily.hasProjectedChain_zero
#print axioms Percolation.squareWalk_support_inter_of_bottomLeft_right_and_bottomRight_top
#print axioms Percolation.squareWalk_support_inter_of_bottomRight_top_and_topRight_left
#print axioms Percolation.squareWalk_support_inter_of_topRight_left_and_topLeft_bottom
#print axioms Percolation.SlabCornerConnectionWitnessFamily.projected_inter_zero_one
#print axioms Percolation.SlabCornerConnectionWitnessFamily.projected_inter_one_two
#print axioms Percolation.SlabCornerConnectionWitnessFamily.projected_inter_two_three
#print axioms Percolation.SlabCornerConnectionWitnessFamily.hasProjectedChain
#print axioms Percolation.slabCornerProjectedChainGeometry
#print axioms Percolation.SlabCornerConnectionWitnessFamily.mem_upwardDistanceAtMost_of_hasProjectedChain
#print axioms Percolation.allSlabCornerConnectionEvents_subset_upwardDistanceAtMost_of_projectedChainGeometry
#print axioms Percolation.slabCornersConnected_probability_ge_of_projectedChainGeometry
#print axioms Percolation.allSlabCornerConnectionEvents_subset_upwardDistanceAtMost
#print axioms Percolation.slabCornersConnected_probability_ge
#print axioms Percolation.mem_coordinateHyperplaneVertices_iff
#print axioms Percolation.mem_coordinateHalfOpenStripVertices_iff
#print axioms Percolation.measurableSet_forwardTwoArmSeparationEvent
#print axioms Percolation.forwardTwoArmSeparationEvent_self_eq_empty
#print axioms Percolation.forwardTwoArmSeparationEvent_eq_empty_of_nat_lt
#print axioms Percolation.exists_cubicWalk_edgePrefix_to_level_of_le_end
#print axioms Percolation.connectionToCoordinateHyperplaneEvent_mono_width
#print axioms Percolation.forwardTwoArmSeparationEvent_anti_width
#print axioms Percolation.forwardTwoArmSeparation_probability_le_pow_of_block_step
#print axioms Percolation.mem_connectionEventWithinVertices_of_mem_finiteBoxGraphComponent
#print axioms Percolation.exists_pair_mem_finiteBoxGraphComponent_lInfDist_eq_diameter
#print axioms Percolation.exists_oriented_coordinate_span_of_le_finiteBoxGraphComponentDiameter
#print axioms Percolation.finiteBoxGraphComponents_eq_of_connectionWithinVertices
#print axioms Percolation.mem_connectionToCoordinateHyperplaneEvent_of_connectionWithin
#print axioms Percolation.exists_forwardTwoArmSeparationEvent_of_crossing_of_secondMacroscopic
#print axioms Percolation.measurableSet_secondMacroscopicClusterStripCoverEvent
#print axioms Percolation.secondMacroscopicClusterEvent_subset_stripCover
#print axioms Percolation.secondMacroscopicCluster_probability_le_card_sq_mul
#print axioms Percolation.secondMacroscopicCluster_probability_le_boxPolynomial_mul
#print axioms Percolation.nat_le_two_mul_mul_div
#print axioms Percolation.secondClusterPeelingRate_pos
#print axioms Percolation.pow_natDiv_le_exp_neg_secondClusterPeelingRate
#print axioms Percolation.exists_secondMacroscopicCluster_probability_le_exp_of_block_step
#print axioms Percolation.exists_cubicWalk_edgePrefix_to_level_of_end_le
#print axioms Percolation.exists_open_cubicWalk_between_levels
#print axioms Percolation.connectionEventWithinVertices_closedBand_eq_connectionEventIn
#print axioms Percolation.dependsOn_forwardTwoArmSeparationEvent
#print axioms Percolation.coordinateBandFrontierVertices_disjoint_of_mem_forwardTwoArm
#print axioms Percolation.coordinateClosedBandEdges_disjoint_freshForwardBandEdges
#print axioms Percolation.forwardTwoArmSeparation_probability_block_step_of_fresh_lowerBound
#print axioms Percolation.cubicGraphIsoConfigurationPullback_mem_connectionEventWithinVertices_iff
#print axioms Percolation.bernoulliBondMeasure_real_connectionEventWithinVertices_graphIso
#print axioms Percolation.coordinateBandToLastIso_mem_finiteThickSlabTVertices_iff
#print axioms Percolation.coordinateClosedStrip_connection_probability_ge_of_uniformFiniteSlab
#print axioms Percolation.forwardTwoArmSeparation_uniform_block_step_of_uniformFiniteSlab
#print axioms Percolation.exists_secondMacroscopicCluster_probability_le_exp_of_uniformFiniteSlab
#print axioms Percolation.connectionToBoxSurfaceEvent_mono_radius
#print axioms Percolation.cubicBoxEdges_mono_radius
#print axioms Percolation.annularPeelingSeparationEvent_anti
#print axioms Percolation.twoArmSeparationEvent_subset_annularPeelingSeparationEvent
#print axioms Percolation.twoArmSeparation_probability_le_pow_of_annular_block_step
#print axioms Percolation.exists_boxShellSlice_pair_chainCorners
#print axioms Percolation.boxShellSlice_connection_probability_ge_of_uniformFiniteSlab
#print axioms Percolation.pow_card_le_allBoxShellChainConnections_probability
#print axioms Percolation.mem_connectionWithin_outerBox_from_first_chainCorner
#print axioms Percolation.boxShellBridgeEvent_subset_connectionWithin_outerBox
#print axioms Percolation.boxShellBridge_probability_ge_of_uniformFiniteSlab
#print axioms Percolation.dependsOn_boxShellBridgeEvent
#print axioms Percolation.annularFrontierVertices_disjoint_of_mem_peeling
#print axioms Percolation.not_mem_next_annularPeeling_of_shellBridge
#print axioms Percolation.annularPeeling_probability_block_step_of_uniformFiniteSlab
#print axioms Percolation.disjoint_cubicVertexIsolatedEvent_connectionToBoxSurfaceEvent
#print axioms Percolation.twoArmSeparation_probability_le_one_sub_isolation
#print axioms Percolation.twoArmSeparation_probability_le_pow_of_uniformFiniteSlab
#print axioms Percolation.annularPeelingExponentialRate_pos
#print axioms Percolation.pow_natDiv_le_exp_neg_annularPeelingExponentialRate
#print axioms Percolation.one_sub_pow_le_exp_neg_annularPeelingExponentialRate
#print axioms Percolation.exists_twoArmSeparation_probability_le_exp_of_uniformFiniteSlab
#print axioms Percolation.exists_scaledTwoArmSeparation_probability_le_exp_of_uniformFiniteSlab
#print axioms Percolation.tendsto_cubicMetricBox_card_sq_mul_exp_neg_nat
#print axioms Percolation.infiniteClusterCoalescenceEvent_probability_tendsto_one_of_uniformFiniteSlab
#print axioms Percolation.secondMacroscopicCluster_probability_tendsto_zero_of_uniformFiniteSlab
#print axioms Percolation.tendsto_logarithmicInsetRadius_div_nat
#print axioms Percolation.tendsto_logarithmicInsetRadius_atTop
#print axioms Percolation.tendsto_logarithmicInset_boxCard_ratio
#print axioms Percolation.tendsto_logarithmicInsetWidth_boxCard_ratio
#print axioms Percolation.tendsto_cubicMetricBox_card_sq_mul_exp_neg_logarithmicInset
#print axioms Percolation.tendsto_cubicMetricBox_card_sq_mul_exp_neg_logarithmicInsetWidth
#print axioms Percolation.exists_logarithmicInset_infiniteClusterCoalescence_probability_tendsto_one
#print axioms Percolation.epsilonDenseCrossingClusterEvent_eq_largeCrossingClusterEvent
#print axioms Percolation.epsilonDenseCrossingCluster_probability_tendsto_one_of_uniformFiniteSlab
#print axioms Percolation.epsilonGoodBox_probability_tendsto_one_of_uniformFiniteSlab
#print axioms Percolation.halfSpaceTheta_critical_eq_zero_of_reliableBricks
#print axioms Percolation.slabCriticalProbability_tendsto_cubicCriticalProbability_of_approximation
#print axioms Percolation.regionThetaFrom_pos_of_critical_lt_of_connected
#print axioms Percolation.bernoulliBondMeasure_real_connectionEventWithinVerticesToSet_graphIso
#print axioms Percolation.infiniteQuarterSlabCluster_subset_slabCornerOriginExitEvent
#print axioms Percolation.regionThetaFrom_half_le_slabCornerConnectionEvent
#print axioms Percolation.slabCornerAllConnectionLowerBound_pos
#print axioms Percolation.slabCornerAllConnectionLowerBound_le
#print axioms Percolation.transportedSlabCornersConnectedEvent_probability
#print axioms Percolation.inter_figure715CornerEvents_subset_connectionS
#print axioms Percolation.sq_slabCornerLowerBound_le_figure715PlanarConnection
#print axioms Percolation.transverseCost_mul_sq_slabCornerLowerBound_le_normalizedConnectionS
#print axioms Percolation.transverseCost_mul_sq_slabCornerLowerBound_le_connectionS_origin
#print axioms Percolation.sq_rootConnectionLowerBound_le_finiteThickSlabSConnection
#print axioms Percolation.slabCornerLowerBound_four_mul_transverse_le_connectionS
#print axioms Percolation.finiteThickSlabSConnectionLowerBound_pos
#print axioms Percolation.finiteThickSlabSConnectionLowerBound_le
#print axioms Percolation.cubicGraphIsoRegion_tSlabSlice_subset_T
#print axioms Percolation.tSlabChainTail_lowerBound
#print axioms Percolation.finiteThickSlabTConnection_origin_lowerBound
#print axioms Percolation.exists_cubicPath_in_finiteThickSlabT
#print axioms Percolation.finiteThickSlabSConnectionLowerBound_pow_le_connectionT_of_L_le_n
#print axioms Percolation.finiteThickSlabTConnectionLowerBound_pos
#print axioms Percolation.finiteThickSlabTConnectionLowerBound_le
#print axioms Percolation.finiteThickSlabConnectionLowerBound_pos
#print axioms Percolation.uniformFiniteSlabConnectionLowerBound_of_quarterSlabCritical_lt
#print axioms Percolation.exists_uniformFiniteSlabConnectionLowerBound_of_critical_lt
#print axioms Percolation.exists_unit_uniformFiniteSlabConnectionLowerBound_of_critical_lt
#print axioms Percolation.exists_twoArmSeparation_probability_le_exp_of_quarterSlabCritical_lt
#print axioms Percolation.exists_secondMacroscopicCluster_probability_le_exp_of_quarterSlabCritical_lt
#print axioms Percolation.epsilonDenseCrossingCluster_probability_tendsto_one_of_quarterSlabCritical_lt
#print axioms Percolation.epsilonGoodBox_probability_tendsto_one_of_quarterSlabCritical_lt
#print axioms Percolation.generateFrom_compl_denumerablePrefix_le_tailBlock
#print axioms Percolation.IsInvariantUnderFiniteClosing.measurableSet_tail
#print axioms Percolation.bernoulli_zero_or_one_of_invariantUnderFiniteClosing
#print axioms Percolation.separatedAxisEdge_injective
#print axioms Percolation.SimpleGraph.Connected.reachable_deleteEdges_endpoint_cover
#print axioms Percolation.SimpleGraph.Connected.exists_infinite_reachable_deleteEdges_singleton
#print axioms Percolation.SimpleGraph.exists_infinite_reachable_deleteEdges_singleton
#print axioms Percolation.SimpleGraph.exists_infinite_reachable_deleteEdges_finset
#print axioms Percolation.cubicOpenGraph_spliceOn_empty
#print axioms Percolation.hasInfiniteOpenClusterInVertices_univ_iff_openGraph
#print axioms Percolation.isInvariantUnderFiniteClosing_hasInfiniteOpenClusterInVertices_univ
#print axioms Percolation.regionHasInfiniteClusterProbability_univ_eq_zero_or_one
#print axioms Percolation.regionHasInfiniteClusterProbability_univ_eq_one_of_theta_pos
#print axioms Percolation.iUnion_centralBoxMeetsInfiniteClusterEvent
#print axioms Percolation.centralBoxMeetsInfiniteCluster_probability_tendsto_one
#print axioms Percolation.exists_centralBoxMeetsInfiniteCluster_probability_gt
#print axioms Percolation.dependsOn_boundaryContactCardLtEvent
#print axioms Percolation.boxBoundaryContacts_nonempty_of_centralBoxMeetsInfiniteCluster
#print axioms Percolation.centralBoxMeetsInfiniteCluster_probability_le_one_le_contactCard
#print axioms Percolation.boxBoundaryExitEdges_card_le
#print axioms Percolation.boundaryContactSetEvent_indep_closedExitEdges
#print axioms Percolation.walk_support_subset_box_of_closed_contact_exits
#print axioms Percolation.boundaryContactSet_inter_closedExit_subset_next_empty
#print axioms Percolation.smallNonemptyBoundaryContact_probability_mul_pow_le_dieNext
#print axioms Percolation.pairwiseDisjoint_boundaryContactsDieNextEvent
#print axioms Percolation.smallNonemptyBoundaryContact_probability_tendsto_zero
#print axioms Percolation.exists_boundaryContactCardGe_probability_gt
#print axioms Percolation.cubicBoxSurface_subset_iUnion_boxSurfaceOrthant
#print axioms Percolation.boxBoundaryContacts_card_le_sum_orthantBoundaryContacts
#print axioms Percolation.isDecreasingEvent_orthantBoundaryContactCardLtEvent
#print axioms Percolation.orthantBoundaryContactProbability_eq_of_iso
#print axioms Percolation.prod_orthantContactLt_probability_le_fullContactLt
#print axioms Percolation.referenceToBoxSurfaceOrthantIso_mem_orthant
#print axioms Percolation.orthantBoundaryContactProbability_eq_reference
#print axioms Percolation.orthantContactLt_probability_pow_le_fullContactLt
#print axioms Percolation.exists_allPositiveOrthantContactCardGe_probability_gt
#print axioms Percolation.exists_eventually_allPositiveOrthantContactCardGe_probability_gt
#print axioms Percolation.cubicStepFrom_mem_canonicalBoundarySeedBox
#print axioms Percolation.canonicalBoundarySeedBoxWithinBoundaryLayer
#print axioms Percolation.isSeededBoundaryPoint_of_canonicalSeed
#print axioms Percolation.exists_pairwiseDisjoint_subfamily_card_mul_ge
#print axioms Percolation.exists_canonicalSeedFreshEdges_pairwiseDisjoint
#print axioms Percolation.bernoulliBondMeasure_iIndepSet_openEdgeSetEvent_of_pairwiseDisjoint
#print axioms Percolation.orthantContactGe_inter_seedConnection_compl_probability_le
#print axioms Percolation.seedConnection_probability_gt
#print axioms Percolation.couplingMeasure_real_sprinkledFailure_inter_history_le
#print axioms Percolation.sprinkledAvailableExit_inter_history_gt
#print axioms Percolation.sprinkledAvailableExit_conditionalProbability_gt
#print axioms Percolation.mem_regionConnectionToFiniteTargetEvent_iff_exists_open_availableExit
#print axioms Percolation.one_sub_p_pow_mul_restartAvailableExit_few_probability_lt
#print axioms Percolation.sprinkledRestart_inter_history_gt
#print axioms Percolation.sprinkledRestart_conditionalProbability_gt
#print axioms Percolation.grimmettMarstrandHalfwayBox_subset_endpointBoxes
#print axioms Percolation.grimmettMarstrandHalfwayBox_subset_thickening
#print axioms Percolation.exists_regionCriticalProbability_thickening_le_add_of_dynamicPercolation
#print axioms Percolation.FiniteRevealSchedule.accumulatedThreshold_le_of_overlapBound
#print axioms Percolation.FiniteRevealSchedule.accumulatedThreshold_le_add_of_grimmettMarstrandOverlap
#print axioms Percolation.translated_seedExplorationBox_subset_oldEndpointBox
#print axioms Percolation.translated_steeredBoundaryLayer_subset_halfwayBox
#print axioms Percolation.translated_steeredRestartRegion_subset_endpointBoxes
#print axioms Percolation.mem_cubicRegionNeighborFinset_iff
#print axioms Percolation.rootedSiteExploration_initial_wellFormed
#print axioms Percolation.rootedSiteExploration_initial_openRootedAt
#print axioms Percolation.cubicRegionSiteExploration_infinite_probability_pos
#print axioms Percolation.AdaptiveSiteExploration.cubicRegion_initial_openRootedAt
#print axioms Percolation.AdaptiveSiteExploration.step_openRootedAt
#print axioms Percolation.AdaptiveSiteExploration.measurable_occupiedLimit
#print axioms Percolation.AdaptiveSiteExploration.infiniteCluster_probability_pos_of_prefixLowerBound
#print axioms Percolation.hasInfiniteOpenClusterInVertices_of_infinite_anchor_connections
#print axioms Percolation.AdaptiveSiteExploration.bondInfiniteCluster_probability_pos_of_prefixLowerBound
#print axioms Percolation.allSuccess_inter_history_gt
#print axioms Percolation.pow_mul_measureReal_le_of_step
#print axioms Percolation.pow_mul_measureReal_lt_of_step
#print axioms Percolation.dynamicBlock_successFactor_gt_siteDensity
#print axioms Percolation.FiniteRevealSchedule.accumulatedThreshold_le_dynamicBlockBudget
#print axioms Percolation.AdaptiveSiteExploration.step_historyConsistent
#print axioms Percolation.AdaptiveSiteExploration.cubicRegion_stateAfter_historyConsistent
#print axioms Percolation.AdaptiveSiteExploration.historyInletParent_adj
#print axioms Percolation.AdaptiveSiteExploration.cubicRegion_stateAfter_frontier_has_inlet
#print axioms Percolation.cubicStepFrom_directionOfAdjacent
#print axioms Percolation.AdaptiveSiteExploration.cubicStepFrom_historyInletParent_inletDirection
#print axioms Percolation.infinitePi_map_precomp_embedding
#print axioms Percolation.couplingMeasure_map_reindex
#print axioms Percolation.couplingMeasure_real_preimage_cubicGraphIsoReindex
#print axioms Percolation.cubicDirectionOrientationIso_origin
#print axioms Percolation.cubicDirectionOrientationIso_positiveStep
#print axioms Percolation.couplingMeasure_real_orientedTransportEvent
#print axioms Percolation.thresholdConfiguration_cubicGraphIsoCouplingReindex
#print axioms Percolation.measurableSet_sprinkledRestartEvent
#print axioms Percolation.cubicDirectionOrientationIso_mem_cubicMetricBox_iff
#print axioms Percolation.cubicDirectionOrientationIso_image_cubicMetricBox
#print axioms Percolation.cubicDirectionOrientationIso_referenceNextSiteCenter
#print axioms Percolation.orientedSteeredRestartRegion_subset_endpointBoxes
#print axioms Percolation.thresholdConfiguration_mem_orientedConnectionEventIn
#print axioms Percolation.orientedSprinkledRestart_inter_history_gt
#print axioms Percolation.AdaptiveSiteExploration.adaptiveAnswerHistoryEvent_append_singleton
#print axioms Percolation.AdaptiveSiteExploration.measurableSet_adaptiveAnswerHistoryEvent
#print axioms Percolation.AdaptiveSiteExploration.measureReal_adaptiveAnswerHistoryEvent_append_true_add_false
#print axioms Percolation.AdaptiveSiteExploration.HasAdaptiveAnswerLowerBoundOn.false_mass_le
#print axioms Percolation.AdaptiveSiteExploration.measurableAnswer_eventAdaptiveAnswer
#print axioms Percolation.AdaptiveSiteExploration.boolInitMass_adaptiveQueryWeight
#print axioms Percolation.AdaptiveSiteExploration.adaptiveQueryWeight_hasSequentialLowerBound
#print axioms Percolation.AdaptiveSiteExploration.iidBoolEventMass_le_adaptiveQueryWeight
#print axioms Percolation.AdaptiveSiteExploration.adaptiveDecisionWinMass_succ
#print axioms Percolation.AdaptiveSiteExploration.iidAdaptiveDecisionValue_mul_historyMass_le
#print axioms Percolation.AdaptiveSiteExploration.iidAdaptiveDecisionValue_le_winMass
#print axioms Percolation.SiteExploration.step_decided_card_eq_add_one
#print axioms Percolation.SiteExploration.stateAfter_card_frontier_eq_empty
#print axioms Percolation.AdaptiveSiteExploration.step_wellFormed
#print axioms Percolation.AdaptiveSiteExploration.stateAfter_card_frontier_eq_empty
#print axioms Percolation.SiteExploration.step_answersAgree
#print axioms Percolation.SiteExploration.step_frontierClosed
#print axioms Percolation.SiteExploration.occupied_eq_siteOpenCluster_of_frontier_eq_empty
#print axioms Percolation.rootedSiteExploration_stateAfter_card_occupied_eq_siteOpenCluster
#print axioms Percolation.SiteExploration.completionHitProbability_eq_open_closed
#print axioms Percolation.SiteExploration.completionHitProbability_reject_le_accept
#print axioms Percolation.SiteExploration.iidAdaptiveDecisionValue_eq_completionHitProbability
#print axioms Percolation.SiteExploration.completionHitProbability_mul_historyMass_le_adaptiveDecisionWinMass
#print axioms Percolation.SiteExploration.finiteSiteHitsTarget_probability_le_adaptiveDecisionWinMass
#print axioms Percolation.AdaptiveSiteExploration.adaptiveDecisionLeafEvent_disjoint_of_ne
#print axioms Percolation.AdaptiveSiteExploration.measureReal_adaptiveDecisionWinEvent
#print axioms Percolation.SiteExploration.replayState_history_eq_or_frontier_eq_empty
#print axioms Percolation.SiteExploration.toAdaptive_stateAfter_eq_replayState_of_mem_leaf
#print axioms Percolation.SiteExploration.finiteSiteHitsTarget_probability_le_adaptiveTargetHitEvent
#print axioms Percolation.SiteExploration.measurableSet_adaptiveLimitTargetHitEvent
#print axioms Percolation.SiteExploration.finiteSiteHitsTarget_probability_le_adaptiveLimitTargetHitEvent
#print axioms Percolation.measureReal_limitEvent_ge_of_antitone_exhaustion
#print axioms Percolation.exists_getVert_cubicL1Dist_eq
#print axioms Percolation.SiteExploration.antitone_cubicRegion_adaptiveLimitSphereHitEvent
#print axioms Percolation.SiteExploration.iInter_cubicRegion_adaptiveLimitSphereHitEvent_subset_infinite
#print axioms Percolation.SiteExploration.cubicRegion_occupiedLimit_infinite_probability_ge_of_sphere_lowerBounds
#print axioms Percolation.rootedInfiniteSiteCluster_probability_pos_of_connected_of_criticalProbability_lt
#print axioms Percolation.rootedInfiniteSiteCluster_probability_le_finiteBallHitsSphere
#print axioms Percolation.SiteExploration.cubicRegionBall_adaptiveLimitTargetHitEvent_subset
#print axioms Percolation.SiteExploration.finiteBallHitsSphere_probability_le_cubicRegion_adaptiveLimitSphereHit
#print axioms Percolation.SiteExploration.cubicRegionSiteExploration_infinite_probability_pos_of_adaptiveLowerBound
#print axioms Percolation.SiteExploration.cubicRegionSiteExploration_hasInfiniteSiteCluster_probability_pos_of_adaptiveLowerBound
#print axioms Percolation.measurableSet_coordSigma_of_eqOn
#print axioms Percolation.measurableSet_sprinkledRestartEvent_restartCoordSigma
#print axioms Percolation.measurableSet_orientedSprinkledRestartEvent_coordSigma
#print axioms Percolation.orientedSprinkledRestart_inter_past_history_ge
#print axioms Percolation.AdaptiveSiteExploration.adaptiveAnswerHistoryEvent_eventAdaptiveAnswer_append_true
#print axioms Percolation.AdaptiveSiteExploration.hasAdaptiveAnswerLowerBoundOn_eventAdaptiveAnswer
#print axioms Percolation.AdaptiveSiteExploration.FreshOrientedRestartProtocol.hasAdaptiveAnswerLowerBound
#print axioms Percolation.AdaptiveSiteExploration.hasAdaptiveAnswerLowerBoundOn_finiteAdaptiveSuccessAnswer
#print axioms Percolation.AdaptiveSiteExploration.FiniteFreshOrientedRestartProgram.hasAdaptiveAnswerLowerBound
#print axioms Percolation.AdaptiveSiteExploration.FiniteFreshOrientedRestartProgram.cubicRegion_infinite_probability_pos
#print axioms Percolation.dynamicBlock_restartPow_gt_siteDensity
#print axioms Percolation.AdaptiveSiteExploration.FiniteFreshOrientedRestartProgram.cubicRegion_infinite_probability_pos_dynamicBlock
#print axioms Percolation.mul_measureReal_le_partitionedSuccess
#print axioms Percolation.AdaptiveSiteExploration.PartitionedOrientedRestartStage.success_lower_bound
#print axioms Percolation.AdaptiveSiteExploration.FinitePartitionedOrientedRestartProgram.hasAdaptiveAnswerLowerBound
#print axioms Percolation.AdaptiveSiteExploration.FinitePartitionedOrientedRestartProgram.cubicRegion_infinite_probability_pos_dynamicBlock
#print axioms Percolation.dynamicBlockBaseDensity_add_maxIncrement
#print axioms Percolation.RestartRevealCellIndex.regionVertices_subset_box
#print axioms Percolation.RestartRevealCellIndex.edgeMultiplicity_le
#print axioms Percolation.RestartRevealCellIndex.dynamicThresholdProfile_le
#print axioms Percolation.pairwiseDisjoint_exactRevealCellEvent
#print axioms Percolation.biUnion_filter_exactRevealCellEvent
#print axioms Percolation.AdaptiveSiteExploration.PartitionedOrientedRestartStage.cellUnion_ofFiniteRealization
#print axioms Percolation.restartExploredRegion_subset_box
#print axioms Percolation.cubicMetricBox_subset_restartExploredRegion
#print axioms Percolation.restartExploredRegion_boundary_not_open
#print axioms Percolation.restartExploredRegion_mem_boundaryClosedHistoryEvent
#print axioms Percolation.RestartRevealCellIndex.ofExploredRegion_boundary_closed
#print axioms Percolation.RestartRevealCellIndex.edgeMultiplicity_ofScheduleExploredRegion
#print axioms Percolation.RestartRevealCellIndex.thresholdProfile_ofScheduleExploredRegion
#print axioms Percolation.RestartRevealCellIndex.dynamicThresholdProfile_ofScheduleExploredRegion
#print axioms Percolation.FiniteRevealSchedule.multiplicity_le_stages_length
#print axioms Percolation.FiniteRevealSchedule.incidentDirectionSchedule_stages_length
#print axioms Percolation.FiniteRevealSchedule.incidentDirectionSchedule_hasOverlapBound
#print axioms Percolation.measurable_heterogeneousThresholdConfiguration
#print axioms Percolation.disjoint_cubicRegionInternalEdgesWithinBox_restartEventSupport
#print axioms Percolation.disjoint_orientedInternalEdges_restartSupport
#print axioms Percolation.measurableSet_restartInternalRegionLabelEvent_coordSigma
#print axioms Percolation.restartExploredRegion_eq_iff_internal_and_boundaryClosed
#print axioms Percolation.restartInternalRegionLabelEvent_inter_boundaryClosed
#print axioms Percolation.realizedScheduleRevealCell_eq_iff
#print axioms Percolation.exactRevealCellEvent_eq_past_inter_boundary
#print axioms Percolation.AdaptiveSiteExploration.PartitionedOrientedRestartStage.cellUnion_ofFiniteValidRealization
#print axioms Percolation.RestartRevealCellIndex.isScheduleRealizable_realizedScheduleRevealCell
#print axioms Percolation.RestartRevealCellIndex.realizedScheduleRevealCell_eq_iff_of_isScheduleRealizable
#print axioms Percolation.RestartRevealCellIndex.exactRevealCellEvent_eq_internalPast_inter_boundary_of_isScheduleRealizable
#print axioms Percolation.measurableSet_orientedRestartInternalRegionLabelEvent_coordSigma
#print axioms Percolation.orientedInternalPast_inter_boundary_eq_exactRevealCellEvent
#print axioms Percolation.measurableSet_orientedRestartRevealPastEvent_coordSigma
#print axioms Percolation.disjoint_orientedRestartRevealPastSupport_restartSupport
#print axioms Percolation.AdaptiveSiteExploration.PartitionedOrientedRestartStage.cellUnion_ofOrientedScheduleRealization
#print axioms Percolation.AdaptiveSiteExploration.adaptiveAnswerHistorySupportFrom_append_singleton
#print axioms Percolation.AdaptiveSiteExploration.HasFiniteAnswerSupports.measurableAnswer
#print axioms Percolation.AdaptiveSiteExploration.measurableSet_adaptiveAnswerHistoryEvent_coordSigma
#print axioms Percolation.AdaptiveSiteExploration.HistoryQuerySupportsFresh.disjoint_historySupport
#print axioms Percolation.AdaptiveSiteExploration.finiteAdaptiveSuccessPrefixSupport_succ
#print axioms Percolation.AdaptiveSiteExploration.measurableSet_finiteAdaptiveSuccessPrefix_coordSigma
#print axioms Percolation.AdaptiveSiteExploration.hasFiniteAnswerSupports_finiteAdaptiveSuccessAnswer
#print axioms Percolation.AdaptiveSiteExploration.measurableSet_finiteAdaptiveOuterHistoryEvent_coordSigma
#print axioms Percolation.AdaptiveSiteExploration.OuterHistorySupportsFresh.disjoint_outerHistorySupport
#print axioms Percolation.lss_parameter_selection
#print axioms Percolation.siteDilutionLaw_real_mem
#print axioms Percolation.stochasticallyDominates_siteDilutionLaw
#print axioms Percolation.hasFiniteSequentialLowerBound_iff_event
#print axioms Percolation.setBernoulli_real_retentionPrefixSection_inter_current
#print axioms Percolation.hasLSSRetentionFactorization
#print axioms Percolation.hasFiniteSequentialLowerBound_siteDilutionLaw
#print axioms Percolation.hasFiniteSequentialLowerBound_siteDilutionLaw_of_original
#print axioms Percolation.pairwiseDisjoint_lssNearZero_lssNearOne_lssFar
#print axioms Percolation.lssNearZero_union_lssNearOne_union_lssFar
#print axioms Percolation.lssNearZero_card_add_lssNearOne_card_le
#print axioms Percolation.dilutedConstraintEvent_eq_lss_partition
#print axioms Percolation.retentionClosedOnProductEvent_subset_dilutedConstraintEvent_nearZero
#print axioms Percolation.dependsOn_dilutedConstraint_originalSection
#print axioms Percolation.prod_setBernoulli_real_retentionClosedOnProductEvent
#print axioms Percolation.prod_setBernoulli_real_retentionOpenOnProductEvent
#print axioms Percolation.productMeasure_real_originalClosed_inter_dilutedConstraint_far
#print axioms Percolation.productMeasure_real_originalClosed_inter_dilutedConstraint_far_le
#print axioms Percolation.productMeasure_real_retentionClosed_inter_originalOpen_inter_dilutedConstraint
#print axioms Percolation.productMeasure_real_retentionOpen_inter_originalOpen_inter_dilutedConstraint
#print axioms Percolation.dilutedConstraintEvent_union_true
#print axioms Percolation.pow_mul_measureReal_dilutedConstraint_le_originalOpen_inter
