import Percolation.Critical.InfiniteClusterUniqueness
import Percolation.Critical.SupercriticalContinuity
import Percolation.Critical.SupercriticalCrossing
import Percolation.Critical.SupercriticalSizeForcing
import Percolation.Critical.SupercriticalFiniteRadiusRate
import Percolation.Critical.SupercriticalRadiusPositivity
import Percolation.Critical.SupercriticalStripFromSlab
import Percolation.Critical.SupercriticalConsequencesFromSlab
import Percolation.Critical.SupercriticalTruncatedConnectivity
import Percolation.Critical.SupercriticalTruncatedGluing
import Percolation.Critical.SupercriticalFiniteClusterTail
import Percolation.Critical.InfiniteClusterEdgeDensity
import Percolation.Critical.FiniteCylinderStrongLaw
import Percolation.Critical.InfiniteClusterEdgeStrongLaw
import Percolation.Critical.SupercriticalSmoothness

/-!
# Chapter 8 transitive axiom audit

The declarations in this file are deliberately `#print axioms` commands.  Their build log is
the machine-checkable transitive-assumption audit for the completed Chapter 8 results.
-/

#print axioms Percolation.unique_infiniteOpenCluster_almostSure_of_theta_pos
#print axioms Percolation.theta_continuousOn_supercritical
#print axioms Percolation.leftRightCrossing_probability_tendsto_one
#print axioms Percolation.exists_supercriticalClusterSize_scale
#print axioms Percolation.finiteClusterSizeProbability_ge_exp_neg_surface_of_critical_lt
#print axioms Percolation.finiteClusterLInfDiameterProbability_glue_lower_bound
#print axioms Percolation.finiteClusterLInfDiameterProbability_logRate_tendsto
#print axioms Percolation.finiteBoxRadiusProbability_logRate_tendsto
#print axioms Percolation.exists_finiteBoxRadiusProbability_le_pow_mul_exp_neg_rate
#print axioms Percolation.exists_truncatedAxisConnectivity_le_pow_mul_exp_neg_rate
#print axioms Percolation.truncatedAxisConnectivity_even_glue_lower_bound
#print axioms Percolation.truncatedAxisConnectivity_odd_glue_lower_bound
#print axioms Percolation.truncatedAxisConnectivity_logRate_tendsto
#print axioms Percolation.finiteClusterSizeTail_le_exp_neg_rpow_of_radiusRate_pos
#print axioms Percolation.summable_nat_pow_mul_exp_neg_mul_rpow
#print axioms Percolation.thetaAnimalSeries_eq_theta
#print axioms Percolation.theta_finiteSusceptibility_clusterDensity_contDiffOn_interior
#print axioms Percolation.finiteBoxRadiusEvent_subset_iUnion_signedHyperplane
#print axioms Percolation.finiteBoxRadiusProbability_le_sum_signedHyperplane
#print axioms Percolation.gamma_le_finiteClusterRadiusDecayRate_of_hyperplane_bound
#print axioms Percolation.finiteClusterRadiusDecayRate_pos_of_hyperplane_bound
#print axioms Percolation.bernoulliBondMeasure_real_coordinateStripAvoidanceHistory_le_pow
#print axioms Percolation.finiteClusterHitsHyperplane_probability_le_stripAvoidance_pow
#print axioms Percolation.finiteClusterHitsHyperplane_probability_le_exp_of_stripTheta_pos
#print axioms Percolation.finiteClusterRadiusDecayRate_pos_of_coordinateStrip_critical_lt
#print axioms Percolation.finiteClusterRadiusDecayRate_pos_of_critical_lt_of_slabCriticalApproximation
#print axioms Percolation.exists_uniformFiniteClusterSizeTailStretchedExponential_of_hyperplane_bound
#print axioms Percolation.exists_uniformFiniteClusterSizeTailStretchedExponential_of_coordinateStrip
#print axioms Percolation.exists_uniformFiniteClusterSizeTailStretchedExponential_of_slabCriticalApproximation
#print axioms Percolation.theta_finiteSusceptibility_clusterDensity_contDiffOn_interior_of_slabCriticalApproximation
#print axioms Percolation.theta_finiteSusceptibility_clusterDensity_contDiffOn_supercriticalInterior_of_slabCriticalApproximation
#print axioms Percolation.finiteClusterSizeTail_le_exp_neg_rpow_of_critical_lt_of_slabCriticalApproximation
#print axioms Percolation.infiniteClusterBoundaryInteriorEdgeRatio_tendsto_ae_of_critical_lt_of_slabCriticalApproximation
#print axioms Percolation.mem_infiniteClusterInteriorEdgeEvent_iff_all_endpoints
#print axioms Percolation.mem_infiniteClusterBoundaryEdgeEvent_iff
#print axioms Percolation.infiniteClusterInteriorEdgeEvent_probability
#print axioms Percolation.infiniteClusterBoundaryEdgeEvent_probability
#print axioms Percolation.one_sub_p_mul_infiniteClusterInteriorEdgeEvent_probability_eq
#print axioms Percolation.one_sub_p_mul_infiniteClusterInteriorEdgeIntensity_eq
#print axioms Percolation.infiniteClusterInteriorEdgeIntensity_pos
#print axioms Percolation.infiniteClusterBoundaryInteriorEdgeRatio_tendsto_ae_of_densityLimits
#print axioms Percolation.translatedEventAverage_tendsto_ae_of_summable_cylinderApprox
#print axioms Percolation.infiniteClusterInteriorEdgeDensity_tendsto_ae_of_radiusRate_pos
#print axioms Percolation.infiniteClusterBoundaryEdgeDensity_tendsto_ae_of_radiusRate_pos
#print axioms Percolation.infiniteClusterEdgeDensityLimits_of_radiusRate_pos
#print axioms Percolation.infiniteClusterBoundaryInteriorEdgeRatio_tendsto_ae_of_radiusRate_pos
