import Percolation.Critical.HalfSpaceBricks
import Percolation.Critical.LSSCubic
import Percolation.Critical.LSSGoodBlocks
import Percolation.Critical.StaticBlockSliceCrossing
import Percolation.Critical.StaticManyCrossings
import Percolation.Critical.StaticManyCrossingsFromSlab
import Percolation.Critical.DynamicReplayGlobalCertificate
import Percolation.Planar.SiteCrossingFrontier
import Percolation.Planar.SiteCrossingPeierls
import Percolation.Critical.DynamicSteeringSymmetry
import Percolation.Critical.AdaptiveAnswerHistory
import Percolation.Critical.AdaptiveAnswerSupport
import Percolation.Critical.DynamicBlockAnswerLaw
import Percolation.Critical.DynamicRestartPartition
import Percolation.Critical.DynamicRevealCells
import Percolation.Critical.DynamicExploredRegion
import Percolation.Critical.DynamicRestartCertificate
import Percolation.Critical.DynamicFramedRestart
import Percolation.Critical.DynamicFramedRestartPartition
import Percolation.Critical.DynamicFramedRevealFreshness
import Percolation.Critical.DynamicRevealIntervals
import Percolation.Critical.DynamicFramedRevealIntervals
import Percolation.Critical.DynamicRevealThresholdUpdate
import Percolation.Critical.DynamicEdgeExploration
import Percolation.Critical.DynamicSourceSchedule
import Percolation.Critical.DynamicRootRadialWitness
import Percolation.Critical.DynamicRootSteeringGeometry
import Percolation.Critical.DynamicRootExtensionState
import Percolation.Critical.DynamicRootMixedCompletion
import Percolation.Critical.DynamicMixedWitnessState
import Percolation.Critical.DynamicRootOutgoingSeeds
import Percolation.Critical.DynamicLaterSiteState
import Percolation.Critical.DynamicLaterSiteHistory
import Percolation.Critical.DynamicLaterSiteRuntime
import Percolation.Critical.DynamicLaterSiteRuntimeHistory
import Percolation.Critical.DynamicLaterSitePartition
import Percolation.Critical.DynamicLaterSiteConnectivity
import Percolation.Critical.DynamicRootConnectivity
import Percolation.Critical.DynamicReachableConnectivity
import Percolation.Critical.DynamicReplayConnectivity
import Percolation.Critical.DynamicReplayFinalThreshold
import Percolation.Critical.AdaptiveStateReplay
import Percolation.Critical.DynamicAcceptedAnchor
import Percolation.Critical.DynamicRootEdgeState
import Percolation.Critical.DynamicRecursiveEdgeState
import Percolation.Critical.DynamicRootRecursiveState
import Percolation.Critical.DynamicFramedStateStage
import Percolation.Critical.DynamicSourceEdgeState
import Percolation.Critical.DynamicRootSourceState
import Percolation.Critical.DynamicSeedWitness
import Percolation.Critical.DynamicSeededRevealCell
import Percolation.Critical.DynamicScheduleCells
import Percolation.Critical.DynamicRevealFreshness
import Percolation.Critical.DynamicProgramSupport
import Percolation.Critical.AdaptiveQueryDomination
import Percolation.Critical.AdaptiveDecisionTree
import Percolation.Critical.AdaptiveDecisionOutcome
import Percolation.Critical.AdaptiveDecisionRealization
import Percolation.Critical.AdaptiveAcceptanceTime
import Percolation.Critical.AdaptiveRealizedHistory
import Percolation.Critical.BondExploration
import Percolation.Critical.IncomingGreenDomination
import Percolation.Critical.BondToSiteCritical
import Percolation.Critical.AdaptiveTargetExhaustion
import Percolation.Critical.AdaptiveRegionShells
import Percolation.Critical.AdaptiveSiteExplorationTheorem
import Percolation.Critical.FiniteExplorationTermination
import Percolation.Critical.FiniteSiteExplorationCompleteness
import Percolation.Critical.FiniteExplorationBellman
import Percolation.Critical.SiteExplorationDomination
import Percolation.Planar.Crossings
import Percolation.Planar.CrossingMenger
import Percolation.Core.EdgeMenger
import Percolation.Core.EdgeMengerToSet
import Percolation.Bernoulli.SequentialDomination
import Percolation.Bernoulli.SequentialDominationCountable
import Percolation.Bernoulli.LSSParameters
import Percolation.Bernoulli.LSSDilution
import Percolation.Bernoulli.SequentialDominationEvents
import Percolation.Bernoulli.LSSDilutionSequential
import Percolation.Bernoulli.LSSInduction
import Percolation.Bernoulli.LSSCountable
import Percolation.Bernoulli.TailZeroOne
import Percolation.Critical.ExplorationLaw
import Percolation.Critical.StaticBlockTranslation
import Percolation.Critical.StaticBlockAdjacency
import Percolation.Critical.StaticBlockPath
import Percolation.Bernoulli.FiniteRangeVariance
import Percolation.Critical.RegionTranslation
import Percolation.Critical.RegionSymmetry
import Percolation.Critical.FiniteSlabLowerBound
import Percolation.Critical.FiniteSlabTLowerBound
import Percolation.Critical.StaticRenormalizationFromSlab
import Percolation.Critical.InfiniteClusterZeroOne
import Percolation.Critical.BoundaryContacts
import Percolation.Critical.BoundaryOrthants
import Percolation.Critical.SeedAmplification
import Percolation.Critical.RestartSprinkling
import Percolation.Critical.RestartGeometry
import Percolation.Critical.DynamicBlockGeometry
import Percolation.Critical.DynamicBlockAssembly
import Percolation.Critical.DynamicRevealBudget
import Percolation.Critical.DynamicSteering
import Percolation.Critical.RootedSiteExploration
import Percolation.Critical.AdaptiveExploration
import Percolation.Critical.DynamicBlockCertificate
import Percolation.Critical.BlockSuccessComposition
import Percolation.Critical.DynamicBlockParameters
import Percolation.Critical.DynamicRootInitialization
import Percolation.Critical.DynamicRootCompletion
import Percolation.Critical.ExplorationHistory
import Percolation.Bernoulli.CouplingSymmetry
import Percolation.Critical.SiteSymmetry
import Percolation.Critical.InfiniteClusterDensity
import Percolation.Critical.StaticCoalescence
import Percolation.Critical.StaticGoodAssembly
import Percolation.Critical.StaticLargeCrossing
import Percolation.Critical.SlabConnectivity
import Percolation.Critical.StaticSecondCluster
import Percolation.Critical.StaticAnnularPeeling
import Percolation.Critical.StaticLogInset
import Percolation.Critical.HalfSpaceCriticalAssembly
import Percolation.Critical.SlabLimitAssembly

/-! Transitive axiom audit for the current Chapter 7 infrastructure checkpoint. -/

#print axioms Percolation.dependsOn_halfSpaceBrickGoodEvent
#print axioms Percolation.continuous_halfSpaceBrickGoodProbability
#print axioms Percolation.epsilonGoodBlockLaw_kDependent
#print axioms Percolation.continuous_seedConnectionProbability
#print axioms Percolation.cubicDilatedThickening_eq_minkowskiSum
#print axioms Percolation.grimmettMarstrandSiteCenter_injective
#print axioms Percolation.couplingMeasure_real_hasInfiniteOpenClusterInVertices_thresholdConfiguration
#print axioms Percolation.AdaptiveSiteExploration.FinitePartitionedOrientedRestartProgram.regionHasInfiniteClusterProbability_pos_dynamicBlock
#print axioms Percolation.AdaptiveSiteExploration.FinitePartitionedOrientedRestartProgram.exists_regionCriticalProbability_thickening_le_add_dynamicBlock
#print axioms Percolation.slabCriticalProbability_antitone
#print axioms Percolation.cubicCriticalProbability_le_slabCriticalProbability
#print axioms Percolation.cubicTranslationConfigurationPullback_hasInfiniteOpenClusterInVertices_iff
#print axioms Percolation.regionHasInfiniteClusterProbability_translate
#print axioms Percolation.regionCriticalProbability_translate
#print axioms Percolation.hasOpenPathOfLengthAtLeastWithinVertices_graphIso_iff
#print axioms Percolation.cubicGraphIsoConfigurationPullback_hasInfiniteOpenClusterInVertices_iff
#print axioms Percolation.regionHasInfiniteClusterProbability_graphIso
#print axioms Percolation.regionCriticalProbability_graphIso
#print axioms Percolation.siteGraphIsoConfigurationPullback_mem_siteConnectionEvent_iff
#print axioms Percolation.siteGraphIsoConfigurationPullback_hasInfiniteSiteCluster_iff
#print axioms Percolation.siteTheta_graphIso
#print axioms Percolation.siteCriticalProbability_graphIso
#print axioms Percolation.siteExploration_infinite_probability_pos_of_dominates
#print axioms Percolation.stochasticallyDominates_iff_measureReal_le
#print axioms Percolation.HasMonotoneCoupling.stochasticallyDominates
#print axioms Percolation.SiteExploration.reachable_between_of_mem_occupiedLimit
#print axioms Percolation.SiteExploration.step_openRootedAt
#print axioms Percolation.SiteExploration.hasInfiniteSiteCluster_occupiedLimit_of_infinite
#print axioms Percolation.dependsOn_siteSquareRectangleCrossingEvent
#print axioms Percolation.hasEdgeDisjointSquareRectangleCrossings_iff_isEdgeReachableBetweenFinsets
#print axioms Percolation.mem_interiorDepth_squareRectangleCrossingEvent_iff
#print axioms Percolation.mem_interiorDepth_squareRectangleCrossingEvent_iff_le_max
#print axioms Percolation.bernoulliBondMeasure_real_maxCrossings_le_le
#print axioms Percolation.exists_staticManyCrossings_goodBlockScale_of_quarterSlabCritical_lt
#print axioms Percolation.exists_maxEdgeDisjointCrossings_probability_ge_aligned_of_quarterSlabCritical_lt
#print axioms Percolation.dependsOn_largeCrossingClusterEvent
#print axioms Percolation.dependsOn_secondMacroscopicClusterEvent
#print axioms Percolation.EdgeMenger.isEdgeReachable_iff_exists_pairwise_edgeDisjoint_paths
#print axioms Percolation.EdgeMenger.isEdgeReachableToFinset_iff_exists_pairwise_edgeDisjoint_walks
#print axioms Percolation.EdgeMenger.isEdgeReachableBetweenFinsets_iff_exists_pairwise_edgeDisjoint_walks
#print axioms Percolation.iidBoolEventMass_le_of_hasSequentialLowerBound
#print axioms Percolation.finiteSequentialLowerBound_stochasticallyDominates
#print axioms Percolation.finiteCylinder_measureReal_le_of_prefixSequential
#print axioms Percolation.infinite_siteSet_probability_eq_one_of_prefixSequential
#print axioms Percolation.infinite_siteSet_probability_pos_of_prefixSequential
#print axioms Percolation.SiteExploration.measurable_occupiedLimit_configurationAnswer
#print axioms Percolation.SiteExploration.occupiedLimit_infinite_probability_pos_of_prefixLowerBound
#print axioms Percolation.SiteExploration.occupiedLimit_hasInfiniteSiteCluster_probability_pos_of_prefixLowerBound
#print axioms Percolation.siteExploration_infinite_probability_pos
#print axioms Percolation.finiteBoxGraphLargestComponent_map_translation
#print axioms Percolation.finiteBoxGraph_isEpsilonGood_translation_iff
#print axioms Percolation.epsilonGoodBlockLaw_map_cubicSiteTranslationPullback
#print axioms Percolation.exists_cubicWalk_prefix_to_level_of_end_le
#print axioms Percolation.exists_cubicWalk_prefix_to_level_of_le_end
#print axioms Percolation.finiteBoxGraphLargestComponents_inter_of_good_step
#print axioms Percolation.finiteBoxGraphLargestComponents_inter_of_mem_goodBoxEvents
#print axioms Percolation.finiteBoxGraphComponentVertices_reachable_cubicOpenGraph
#print axioms Percolation.epsilonGoodBlockClusterVertices_reachable_of_good_walk
#print axioms Percolation.epsilonGoodBlockCluster_isCrossing_of_mem_goodBoxEvent
#print axioms Percolation.exists_cubicOpenGraph_reachable_between_faces_of_good_walk
#print axioms Percolation.exists_connectionEvent_between_faces_of_good_walk
#print axioms Percolation.variance_finset_average_le_of_finite_covariance_neighborhood
#print axioms Percolation.measure_average_deviation_le_of_finite_covariance_neighborhood
#print axioms Percolation.disjoint_cubicTranslation_image_edgeSets_of_far
#print axioms Percolation.covariance_translatedCylinderIndicator_eq_zero_of_far
#print axioms Percolation.bernoulliBondMeasure_real_infiniteClusterVertexDensity_deviation_le_of_approx
#print axioms Percolation.infiniteClusterVertexDensity_measureReal_tendsto_zero
#print axioms Percolation.mem_denseInfiniteClusterVertexEvent_iff_card
#print axioms Percolation.denseInfiniteClusterVertexEvent_probability_tendsto_one
#print axioms Percolation.exists_open_walk_to_cubicBoxSurface_in_box_of_mem
#print axioms Percolation.hasInfiniteOpenClusterFrom_mem_connectionToBoxSurfaceEvent
#print axioms Percolation.connectionEventIn_of_infinite_of_not_twoArm
#print axioms Percolation.infiniteClusterCoalescenceEvent_compl_subset_iUnion_twoArm
#print axioms Percolation.bernoulliBondMeasure_real_infiniteClusterCoalescenceEvent_compl_le_sum
#print axioms Percolation.infiniteClusterCoalescenceEvent_probability_tendsto_one_of_twoArm_bound
#print axioms Percolation.measureReal_peeling_le_pow_mul
#print axioms Percolation.measureReal_event_le_pow_of_peeling
#print axioms Percolation.finiteBoxGraphComponentCard_le_boxCard_of_diameter_lt
#print axioms Percolation.FiniteBoxGraph.isEpsilonGood_of_largeCrossing_of_noSecondMacroscopic
#print axioms Percolation.epsilonGoodBoxEvent_compl_subset_largeCrossing_compl_union_secondMacroscopic
#print axioms Percolation.one_sub_bernoulliBondMeasure_real_epsilonGoodBoxEvent_le
#print axioms Percolation.epsilonGoodBox_probability_tendsto_one_of_largeCrossing_of_second
#print axioms Percolation.walk_support_subset_cubicMetricBox_of_edges
#print axioms Percolation.finiteBoxOpenGraph_reachable_of_mem_connectionEventIn
#print axioms Percolation.measurableSet_innerInfiniteClusterReachesFaceEvent
#print axioms Percolation.mem_largeCrossingClusterEvent_of_dense_of_coalescence_of_allFaces
#print axioms Percolation.bernoulliBondMeasure_prod_le_real_biInter_fkg_of_decreasing
#print axioms Percolation.cubicGraphIsoConfigurationPullback_hasInfiniteOpenClusterFrom_iff
#print axioms Percolation.cubicGraphIsoConfigurationPullback_mem_connectionEventIn_iff
#print axioms Percolation.cubicCoordinatePermutation_image_cubicBoxEdges_eq
#print axioms Percolation.innerInfiniteClusterReachesFaceProbability_permutation
#print axioms Percolation.prod_complFaceProbabilities_le_innerHasInfiniteClusterVertexEvent_compl
#print axioms Percolation.one_sub_referenceFaceProbability_tendsto_zero
#print axioms Percolation.allInnerInfiniteClusterFacesEvent_probability_tendsto_one
#print axioms Percolation.allInnerInfiniteClusterFacesEvent_probability_tendsto_one_of_radii
#print axioms Percolation.largeCrossingCluster_probability_tendsto_one_of_coalescence
#print axioms Percolation.mem_finiteThickSlabSVertices_iff
#print axioms Percolation.mem_finiteThickSlabTVertices_iff
#print axioms Percolation.measurableSet_finiteThickSlabSConnectionEvent
#print axioms Percolation.finiteThickSlabSConnectionEvent_self
#print axioms Percolation.mem_slabCornerBoxVertices_iff
#print axioms Percolation.slabCornerVertex_mem
#print axioms Percolation.measurableSet_slabCornerConnectionEvent
#print axioms Percolation.slabCornerConnection_lowerBound_pow_four
#print axioms Percolation.measurableSet_allSlabCornersConnectedEvent
#print axioms Percolation.bernoulliBondMeasure_real_mul_pow_card_le_of_inter_openEdgeSet_subset
#print axioms Percolation.slabCornersConnected_probability_ge_of_fixedBridge
#print axioms Percolation.measurableSet_upwardDistanceAtMost
#print axioms Percolation.couplingMeasure_upwardDistance_le
#print axioms Percolation.IsIncreasingEvent.bernoulliBondMeasure_real_upwardDistanceAtMost_le
#print axioms Percolation.slabCornersConnected_probability_ge_of_boundedRepair
#print axioms Percolation.exists_cubicWalk_length_eq_l1Dist_support_between
#print axioms Percolation.cubicL1Dist_le_sub_two_mul_of_mem_slabCorner_of_agree_first_two
#print axioms Percolation.exists_transverse_cubicPath_in_slabCorner
#print axioms Percolation.mem_upwardDistanceAtMost_connectionWithin_slabCorner_of_agree_first_two
#print axioms Percolation.mem_projectCubicWalkFirstTwo_support_iff
#print axioms Percolation.projectCubicWalkFirstTwo_support_inter_iff
#print axioms Percolation.upwardDistanceAtMost_mono_radius
#print axioms Percolation.mem_upwardDistanceAtMost_connectionWithinVertices_trans
#print axioms Percolation.mem_upwardDistanceAtMost_connectionWithin_slabCorner_of_projected_inter
#print axioms Percolation.mem_upwardDistanceAtMost_allSlabCornersConnectedEvent_of_chain
#print axioms Percolation.mem_upwardDistanceAtMost_allSlabCornersConnectedEvent_of_projected_chain
#print axioms Percolation.mem_slabCornerConnectionEvent_iff_nonempty_witness
#print axioms Percolation.mem_allSlabCornerConnectionEvents_iff_nonempty_witnessFamily
#print axioms Percolation.SlabCornerConnectionWitnessFamily.hasProjectedChain_zero
#print axioms Percolation.squareWalk_support_inter_of_bottomLeft_right_and_bottomRight_top
#print axioms Percolation.squareWalk_support_inter_of_bottomRight_top_and_topRight_left
#print axioms Percolation.squareWalk_support_inter_of_topRight_left_and_topLeft_bottom
#print axioms Percolation.SlabCornerConnectionWitnessFamily.projected_inter_zero_one
#print axioms Percolation.SlabCornerConnectionWitnessFamily.projected_inter_one_two
#print axioms Percolation.SlabCornerConnectionWitnessFamily.projected_inter_two_three
#print axioms Percolation.SlabCornerConnectionWitnessFamily.hasProjectedChain
#print axioms Percolation.slabCornerProjectedChainGeometry
#print axioms Percolation.SlabCornerConnectionWitnessFamily.mem_upwardDistanceAtMost_of_hasProjectedChain
#print axioms Percolation.allSlabCornerConnectionEvents_subset_upwardDistanceAtMost_of_projectedChainGeometry
#print axioms Percolation.slabCornersConnected_probability_ge_of_projectedChainGeometry
#print axioms Percolation.allSlabCornerConnectionEvents_subset_upwardDistanceAtMost
#print axioms Percolation.slabCornersConnected_probability_ge
#print axioms Percolation.mem_coordinateHyperplaneVertices_iff
#print axioms Percolation.mem_coordinateHalfOpenStripVertices_iff
#print axioms Percolation.measurableSet_forwardTwoArmSeparationEvent
#print axioms Percolation.forwardTwoArmSeparationEvent_self_eq_empty
#print axioms Percolation.forwardTwoArmSeparationEvent_eq_empty_of_nat_lt
#print axioms Percolation.exists_cubicWalk_edgePrefix_to_level_of_le_end
#print axioms Percolation.connectionToCoordinateHyperplaneEvent_mono_width
#print axioms Percolation.forwardTwoArmSeparationEvent_anti_width
#print axioms Percolation.forwardTwoArmSeparation_probability_le_pow_of_block_step
#print axioms Percolation.mem_connectionEventWithinVertices_of_mem_finiteBoxGraphComponent
#print axioms Percolation.exists_pair_mem_finiteBoxGraphComponent_lInfDist_eq_diameter
#print axioms Percolation.exists_oriented_coordinate_span_of_le_finiteBoxGraphComponentDiameter
#print axioms Percolation.finiteBoxGraphComponents_eq_of_connectionWithinVertices
#print axioms Percolation.mem_connectionToCoordinateHyperplaneEvent_of_connectionWithin
#print axioms Percolation.exists_forwardTwoArmSeparationEvent_of_crossing_of_secondMacroscopic
#print axioms Percolation.measurableSet_secondMacroscopicClusterStripCoverEvent
#print axioms Percolation.secondMacroscopicClusterEvent_subset_stripCover
#print axioms Percolation.secondMacroscopicCluster_probability_le_card_sq_mul
#print axioms Percolation.secondMacroscopicCluster_probability_le_boxPolynomial_mul
#print axioms Percolation.nat_le_two_mul_mul_div
#print axioms Percolation.secondClusterPeelingRate_pos
#print axioms Percolation.pow_natDiv_le_exp_neg_secondClusterPeelingRate
#print axioms Percolation.exists_secondMacroscopicCluster_probability_le_exp_of_block_step
#print axioms Percolation.exists_cubicWalk_edgePrefix_to_level_of_end_le
#print axioms Percolation.exists_open_cubicWalk_between_levels
#print axioms Percolation.connectionEventWithinVertices_closedBand_eq_connectionEventIn
#print axioms Percolation.dependsOn_forwardTwoArmSeparationEvent
#print axioms Percolation.coordinateBandFrontierVertices_disjoint_of_mem_forwardTwoArm
#print axioms Percolation.coordinateClosedBandEdges_disjoint_freshForwardBandEdges
#print axioms Percolation.forwardTwoArmSeparation_probability_block_step_of_fresh_lowerBound
#print axioms Percolation.cubicGraphIsoConfigurationPullback_mem_connectionEventWithinVertices_iff
#print axioms Percolation.bernoulliBondMeasure_real_connectionEventWithinVertices_graphIso
#print axioms Percolation.coordinateBandToLastIso_mem_finiteThickSlabTVertices_iff
#print axioms Percolation.coordinateClosedStrip_connection_probability_ge_of_uniformFiniteSlab
#print axioms Percolation.forwardTwoArmSeparation_uniform_block_step_of_uniformFiniteSlab
#print axioms Percolation.exists_secondMacroscopicCluster_probability_le_exp_of_uniformFiniteSlab
#print axioms Percolation.connectionToBoxSurfaceEvent_mono_radius
#print axioms Percolation.cubicBoxEdges_mono_radius
#print axioms Percolation.annularPeelingSeparationEvent_anti
#print axioms Percolation.twoArmSeparationEvent_subset_annularPeelingSeparationEvent
#print axioms Percolation.twoArmSeparation_probability_le_pow_of_annular_block_step
#print axioms Percolation.exists_boxShellSlice_pair_chainCorners
#print axioms Percolation.boxShellSlice_connection_probability_ge_of_uniformFiniteSlab
#print axioms Percolation.pow_card_le_allBoxShellChainConnections_probability
#print axioms Percolation.mem_connectionWithin_outerBox_from_first_chainCorner
#print axioms Percolation.boxShellBridgeEvent_subset_connectionWithin_outerBox
#print axioms Percolation.boxShellBridge_probability_ge_of_uniformFiniteSlab
#print axioms Percolation.dependsOn_boxShellBridgeEvent
#print axioms Percolation.annularFrontierVertices_disjoint_of_mem_peeling
#print axioms Percolation.not_mem_next_annularPeeling_of_shellBridge
#print axioms Percolation.annularPeeling_probability_block_step_of_uniformFiniteSlab
#print axioms Percolation.disjoint_cubicVertexIsolatedEvent_connectionToBoxSurfaceEvent
#print axioms Percolation.twoArmSeparation_probability_le_one_sub_isolation
#print axioms Percolation.twoArmSeparation_probability_le_pow_of_uniformFiniteSlab
#print axioms Percolation.annularPeelingExponentialRate_pos
#print axioms Percolation.pow_natDiv_le_exp_neg_annularPeelingExponentialRate
#print axioms Percolation.one_sub_pow_le_exp_neg_annularPeelingExponentialRate
#print axioms Percolation.exists_twoArmSeparation_probability_le_exp_of_uniformFiniteSlab
#print axioms Percolation.exists_scaledTwoArmSeparation_probability_le_exp_of_uniformFiniteSlab
#print axioms Percolation.tendsto_cubicMetricBox_card_sq_mul_exp_neg_nat
#print axioms Percolation.infiniteClusterCoalescenceEvent_probability_tendsto_one_of_uniformFiniteSlab
#print axioms Percolation.secondMacroscopicCluster_probability_tendsto_zero_of_uniformFiniteSlab
#print axioms Percolation.tendsto_logarithmicInsetRadius_div_nat
#print axioms Percolation.tendsto_logarithmicInsetRadius_atTop
#print axioms Percolation.tendsto_logarithmicInset_boxCard_ratio
#print axioms Percolation.tendsto_logarithmicInsetWidth_boxCard_ratio
#print axioms Percolation.tendsto_cubicMetricBox_card_sq_mul_exp_neg_logarithmicInset
#print axioms Percolation.tendsto_cubicMetricBox_card_sq_mul_exp_neg_logarithmicInsetWidth
#print axioms Percolation.exists_logarithmicInset_infiniteClusterCoalescence_probability_tendsto_one
#print axioms Percolation.epsilonDenseCrossingClusterEvent_eq_largeCrossingClusterEvent
#print axioms Percolation.epsilonDenseCrossingCluster_probability_tendsto_one_of_uniformFiniteSlab
#print axioms Percolation.epsilonGoodBox_probability_tendsto_one_of_uniformFiniteSlab
#print axioms Percolation.halfSpaceTheta_critical_eq_zero_of_reliableBricks
#print axioms Percolation.slabCriticalProbability_tendsto_cubicCriticalProbability_of_approximation
#print axioms Percolation.regionThetaFrom_pos_of_critical_lt_of_connected
#print axioms Percolation.bernoulliBondMeasure_real_connectionEventWithinVerticesToSet_graphIso
#print axioms Percolation.infiniteQuarterSlabCluster_subset_slabCornerOriginExitEvent
#print axioms Percolation.regionThetaFrom_half_le_slabCornerConnectionEvent
#print axioms Percolation.slabCornerAllConnectionLowerBound_pos
#print axioms Percolation.slabCornerAllConnectionLowerBound_le
#print axioms Percolation.transportedSlabCornersConnectedEvent_probability
#print axioms Percolation.inter_figure715CornerEvents_subset_connectionS
#print axioms Percolation.sq_slabCornerLowerBound_le_figure715PlanarConnection
#print axioms Percolation.transverseCost_mul_sq_slabCornerLowerBound_le_normalizedConnectionS
#print axioms Percolation.transverseCost_mul_sq_slabCornerLowerBound_le_connectionS_origin
#print axioms Percolation.sq_rootConnectionLowerBound_le_finiteThickSlabSConnection
#print axioms Percolation.slabCornerLowerBound_four_mul_transverse_le_connectionS
#print axioms Percolation.finiteThickSlabSConnectionLowerBound_pos
#print axioms Percolation.finiteThickSlabSConnectionLowerBound_le
#print axioms Percolation.cubicGraphIsoRegion_tSlabSlice_subset_T
#print axioms Percolation.tSlabChainTail_lowerBound
#print axioms Percolation.finiteThickSlabTConnection_origin_lowerBound
#print axioms Percolation.exists_cubicPath_in_finiteThickSlabT
#print axioms Percolation.finiteThickSlabSConnectionLowerBound_pow_le_connectionT_of_L_le_n
#print axioms Percolation.finiteThickSlabTConnectionLowerBound_pos
#print axioms Percolation.finiteThickSlabTConnectionLowerBound_le
#print axioms Percolation.finiteThickSlabConnectionLowerBound_pos
#print axioms Percolation.uniformFiniteSlabConnectionLowerBound_of_quarterSlabCritical_lt
#print axioms Percolation.exists_uniformFiniteSlabConnectionLowerBound_of_critical_lt
#print axioms Percolation.exists_unit_uniformFiniteSlabConnectionLowerBound_of_critical_lt
#print axioms Percolation.exists_twoArmSeparation_probability_le_exp_of_quarterSlabCritical_lt
#print axioms Percolation.exists_secondMacroscopicCluster_probability_le_exp_of_quarterSlabCritical_lt
#print axioms Percolation.epsilonDenseCrossingCluster_probability_tendsto_one_of_quarterSlabCritical_lt
#print axioms Percolation.epsilonGoodBox_probability_tendsto_one_of_quarterSlabCritical_lt
#print axioms Percolation.generateFrom_compl_denumerablePrefix_le_tailBlock
#print axioms Percolation.IsInvariantUnderFiniteClosing.measurableSet_tail
#print axioms Percolation.bernoulli_zero_or_one_of_invariantUnderFiniteClosing
#print axioms Percolation.separatedAxisEdge_injective
#print axioms Percolation.SimpleGraph.Connected.reachable_deleteEdges_endpoint_cover
#print axioms Percolation.SimpleGraph.Connected.exists_infinite_reachable_deleteEdges_singleton
#print axioms Percolation.SimpleGraph.exists_infinite_reachable_deleteEdges_singleton
#print axioms Percolation.SimpleGraph.exists_infinite_reachable_deleteEdges_finset
#print axioms Percolation.cubicOpenGraph_spliceOn_empty
#print axioms Percolation.hasInfiniteOpenClusterInVertices_univ_iff_openGraph
#print axioms Percolation.isInvariantUnderFiniteClosing_hasInfiniteOpenClusterInVertices_univ
#print axioms Percolation.regionHasInfiniteClusterProbability_univ_eq_zero_or_one
#print axioms Percolation.regionHasInfiniteClusterProbability_univ_eq_one_of_theta_pos
#print axioms Percolation.iUnion_centralBoxMeetsInfiniteClusterEvent
#print axioms Percolation.centralBoxMeetsInfiniteCluster_probability_tendsto_one
#print axioms Percolation.exists_centralBoxMeetsInfiniteCluster_probability_gt
#print axioms Percolation.dependsOn_boundaryContactCardLtEvent
#print axioms Percolation.boxBoundaryContacts_nonempty_of_centralBoxMeetsInfiniteCluster
#print axioms Percolation.centralBoxMeetsInfiniteCluster_probability_le_one_le_contactCard
#print axioms Percolation.boxBoundaryExitEdges_card_le
#print axioms Percolation.boundaryContactSetEvent_indep_closedExitEdges
#print axioms Percolation.walk_support_subset_box_of_closed_contact_exits
#print axioms Percolation.boundaryContactSet_inter_closedExit_subset_next_empty
#print axioms Percolation.smallNonemptyBoundaryContact_probability_mul_pow_le_dieNext
#print axioms Percolation.pairwiseDisjoint_boundaryContactsDieNextEvent
#print axioms Percolation.smallNonemptyBoundaryContact_probability_tendsto_zero
#print axioms Percolation.exists_boundaryContactCardGe_probability_gt
#print axioms Percolation.cubicBoxSurface_subset_iUnion_boxSurfaceOrthant
#print axioms Percolation.boxBoundaryContacts_card_le_sum_orthantBoundaryContacts
#print axioms Percolation.isDecreasingEvent_orthantBoundaryContactCardLtEvent
#print axioms Percolation.orthantBoundaryContactProbability_eq_of_iso
#print axioms Percolation.prod_orthantContactLt_probability_le_fullContactLt
#print axioms Percolation.referenceToBoxSurfaceOrthantIso_mem_orthant
#print axioms Percolation.orthantBoundaryContactProbability_eq_reference
#print axioms Percolation.orthantContactLt_probability_pow_le_fullContactLt
#print axioms Percolation.exists_allPositiveOrthantContactCardGe_probability_gt
#print axioms Percolation.exists_eventually_allPositiveOrthantContactCardGe_probability_gt
#print axioms Percolation.cubicStepFrom_mem_canonicalBoundarySeedBox
#print axioms Percolation.canonicalBoundarySeedBoxWithinBoundaryLayer
#print axioms Percolation.isSeededBoundaryPoint_of_canonicalSeed
#print axioms Percolation.exists_pairwiseDisjoint_subfamily_card_mul_ge
#print axioms Percolation.exists_canonicalSeedFreshEdges_pairwiseDisjoint
#print axioms Percolation.bernoulliBondMeasure_iIndepSet_openEdgeSetEvent_of_pairwiseDisjoint
#print axioms Percolation.orthantContactGe_inter_seedConnection_compl_probability_le
#print axioms Percolation.seedConnection_probability_gt
#print axioms Percolation.seedConnection_probability_gt_allCoordinates
#print axioms Percolation.couplingMeasure_real_sprinkledFailure_inter_history_le
#print axioms Percolation.sprinkledAvailableExit_inter_history_gt
#print axioms Percolation.sprinkledAvailableExit_conditionalProbability_gt
#print axioms Percolation.mem_regionConnectionToFiniteTargetEvent_iff_exists_open_availableExit
#print axioms Percolation.one_sub_p_pow_mul_restartAvailableExit_few_probability_lt
#print axioms Percolation.sprinkledRestart_inter_history_gt
#print axioms Percolation.sprinkledRestart_inter_history_gt_allCoordinates
#print axioms Percolation.exists_uniformRestartBounds
#print axioms Percolation.sprinkledRestart_conditionalProbability_gt
#print axioms Percolation.grimmettMarstrandHalfwayBox_subset_endpointBoxes
#print axioms Percolation.grimmettMarstrandHalfwayBox_subset_thickening
#print axioms Percolation.exists_regionCriticalProbability_thickening_le_add_of_dynamicPercolation
#print axioms Percolation.FiniteRevealSchedule.accumulatedThreshold_le_of_overlapBound
#print axioms Percolation.FiniteRevealSchedule.accumulatedThreshold_le_add_of_grimmettMarstrandOverlap
#print axioms Percolation.translated_seedExplorationBox_subset_oldEndpointBox
#print axioms Percolation.translated_steeredBoundaryLayer_subset_halfwayBox
#print axioms Percolation.translated_steeredRestartRegion_subset_endpointBoxes
#print axioms Percolation.mem_cubicRegionNeighborFinset_iff
#print axioms Percolation.rootedSiteExploration_initial_wellFormed
#print axioms Percolation.rootedSiteExploration_initial_openRootedAt
#print axioms Percolation.cubicRegionSiteExploration_infinite_probability_pos
#print axioms Percolation.AdaptiveSiteExploration.cubicRegion_initial_openRootedAt
#print axioms Percolation.AdaptiveSiteExploration.step_openRootedAt
#print axioms Percolation.AdaptiveSiteExploration.measurable_occupiedLimit
#print axioms Percolation.AdaptiveSiteExploration.infiniteCluster_probability_pos_of_prefixLowerBound
#print axioms Percolation.hasInfiniteOpenClusterInVertices_of_infinite_anchor_connections
#print axioms Percolation.AdaptiveSiteExploration.bondInfiniteCluster_probability_pos_of_prefixLowerBound
#print axioms Percolation.allSuccess_inter_history_gt
#print axioms Percolation.pow_mul_measureReal_le_of_step
#print axioms Percolation.pow_mul_measureReal_lt_of_step
#print axioms Percolation.dynamicBlock_successFactor_gt_siteDensity
#print axioms Percolation.FiniteRevealSchedule.accumulatedThreshold_le_dynamicBlockBudget
#print axioms Percolation.AdaptiveSiteExploration.step_historyConsistent
#print axioms Percolation.AdaptiveSiteExploration.cubicRegion_stateAfter_historyConsistent
#print axioms Percolation.AdaptiveSiteExploration.historyInletParent_adj
#print axioms Percolation.AdaptiveSiteExploration.cubicRegion_stateAfter_frontier_has_inlet
#print axioms Percolation.cubicStepFrom_directionOfAdjacent
#print axioms Percolation.AdaptiveSiteExploration.cubicStepFrom_historyInletParent_inletDirection
#print axioms Percolation.infinitePi_map_precomp_embedding
#print axioms Percolation.couplingMeasure_map_reindex
#print axioms Percolation.couplingMeasure_real_preimage_cubicGraphIsoReindex
#print axioms Percolation.cubicDirectionOrientationIso_origin
#print axioms Percolation.cubicDirectionOrientationIso_positiveStep
#print axioms Percolation.couplingMeasure_real_orientedTransportEvent
#print axioms Percolation.thresholdConfiguration_cubicGraphIsoCouplingReindex
#print axioms Percolation.measurableSet_sprinkledRestartEvent
#print axioms Percolation.cubicDirectionOrientationIso_mem_cubicMetricBox_iff
#print axioms Percolation.cubicDirectionOrientationIso_image_cubicMetricBox
#print axioms Percolation.cubicDirectionOrientationIso_referenceNextSiteCenter
#print axioms Percolation.orientedSteeredRestartRegion_subset_endpointBoxes
#print axioms Percolation.thresholdConfiguration_mem_orientedConnectionEventIn
#print axioms Percolation.orientedSprinkledRestart_inter_history_gt
#print axioms Percolation.AdaptiveSiteExploration.adaptiveAnswerHistoryEvent_append_singleton
#print axioms Percolation.AdaptiveSiteExploration.measurableSet_adaptiveAnswerHistoryEvent
#print axioms Percolation.AdaptiveSiteExploration.measureReal_adaptiveAnswerHistoryEvent_append_true_add_false
#print axioms Percolation.AdaptiveSiteExploration.HasAdaptiveAnswerLowerBoundOn.false_mass_le
#print axioms Percolation.AdaptiveSiteExploration.HasAdaptiveAnswerUpperBoundOn.false_mass_ge
#print axioms Percolation.AdaptiveSiteExploration.measurableAnswer_eventAdaptiveAnswer
#print axioms Percolation.AdaptiveSiteExploration.boolInitMass_adaptiveQueryWeight
#print axioms Percolation.AdaptiveSiteExploration.adaptiveQueryWeight_hasSequentialLowerBound
#print axioms Percolation.AdaptiveSiteExploration.iidBoolEventMass_le_adaptiveQueryWeight
#print axioms Percolation.AdaptiveSiteExploration.adaptiveDecisionWinMass_succ
#print axioms Percolation.AdaptiveSiteExploration.iidAdaptiveDecisionValue_mul_historyMass_le
#print axioms Percolation.AdaptiveSiteExploration.iidAdaptiveDecisionValue_le_winMass
#print axioms Percolation.AdaptiveSiteExploration.adaptiveDecisionWinMass_le_iidAdaptiveDecisionValue_mul_historyMass
#print axioms Percolation.AdaptiveSiteExploration.winMass_le_iidAdaptiveDecisionValue
#print axioms Percolation.SiteExploration.step_decided_card_eq_add_one
#print axioms Percolation.SiteExploration.stateAfter_card_frontier_eq_empty
#print axioms Percolation.AdaptiveSiteExploration.step_wellFormed
#print axioms Percolation.AdaptiveSiteExploration.stateAfter_card_frontier_eq_empty
#print axioms Percolation.SiteExploration.step_answersAgree
#print axioms Percolation.SiteExploration.step_frontierClosed
#print axioms Percolation.SiteExploration.occupied_eq_siteOpenCluster_of_frontier_eq_empty
#print axioms Percolation.rootedSiteExploration_stateAfter_card_occupied_eq_siteOpenCluster
#print axioms Percolation.SiteExploration.completionHitProbability_eq_open_closed
#print axioms Percolation.SiteExploration.completionHitProbability_reject_le_accept
#print axioms Percolation.SiteExploration.iidAdaptiveDecisionValue_eq_completionHitProbability
#print axioms Percolation.SiteExploration.completionHitProbability_mul_historyMass_le_adaptiveDecisionWinMass
#print axioms Percolation.SiteExploration.adaptiveDecisionWinMass_le_completionHitProbability_mul_historyMass
#print axioms Percolation.SiteExploration.adaptiveDecisionWinMass_le_completionHitProbability_initial
#print axioms Percolation.SiteExploration.finiteSiteHitsTarget_probability_le_adaptiveDecisionWinMass
#print axioms Percolation.AdaptiveSiteExploration.adaptiveDecisionLeafEvent_disjoint_of_ne
#print axioms Percolation.AdaptiveSiteExploration.mem_adaptiveDecisionLeafEvent_adaptiveDecisionBits
#print axioms Percolation.AdaptiveSiteExploration.measureReal_adaptiveDecisionWinEvent
#print axioms Percolation.SiteExploration.replayState_history_eq_or_frontier_eq_empty
#print axioms Percolation.SiteExploration.toAdaptive_stateAfter_eq_replayState_of_mem_leaf
#print axioms Percolation.SiteExploration.adaptiveTargetHitEvent_eq_adaptiveDecisionWinEvent
#print axioms Percolation.SiteExploration.adaptiveTargetHitEvent_probability_le_rooted_completion
#print axioms Percolation.SiteExploration.finiteSiteHitsTarget_probability_le_adaptiveTargetHitEvent
#print axioms Percolation.SiteExploration.measurableSet_adaptiveLimitTargetHitEvent
#print axioms Percolation.SiteExploration.finiteSiteHitsTarget_probability_le_adaptiveLimitTargetHitEvent
#print axioms Percolation.measureReal_limitEvent_ge_of_antitone_exhaustion
#print axioms Percolation.exists_getVert_cubicL1Dist_eq
#print axioms Percolation.SiteExploration.antitone_cubicRegion_adaptiveLimitSphereHitEvent
#print axioms Percolation.SiteExploration.iInter_cubicRegion_adaptiveLimitSphereHitEvent_subset_infinite
#print axioms Percolation.SiteExploration.cubicRegion_occupiedLimit_infinite_probability_ge_of_sphere_lowerBounds
#print axioms Percolation.rootedInfiniteSiteCluster_probability_pos_of_connected_of_criticalProbability_lt
#print axioms Percolation.rootedInfiniteSiteCluster_probability_le_finiteBallHitsSphere
#print axioms Percolation.SiteExploration.cubicRegionBall_adaptiveLimitTargetHitEvent_subset
#print axioms Percolation.SiteExploration.finiteBallHitsSphere_probability_le_cubicRegion_adaptiveLimitSphereHit
#print axioms Percolation.SiteExploration.cubicRegionSiteExploration_infinite_probability_pos_of_adaptiveLowerBound
#print axioms Percolation.SiteExploration.cubicRegionSiteExploration_hasInfiniteSiteCluster_probability_pos_of_adaptiveLowerBound
#print axioms Percolation.measurableSet_coordSigma_of_eqOn
#print axioms Percolation.measurableSet_sprinkledRestartEvent_restartCoordSigma
#print axioms Percolation.measurableSet_orientedSprinkledRestartEvent_coordSigma
#print axioms Percolation.orientedSprinkledRestart_inter_past_history_ge
#print axioms Percolation.AdaptiveSiteExploration.adaptiveAnswerHistoryEvent_eventAdaptiveAnswer_append_true
#print axioms Percolation.AdaptiveSiteExploration.hasAdaptiveAnswerLowerBoundOn_eventAdaptiveAnswer
#print axioms Percolation.AdaptiveSiteExploration.FreshOrientedRestartProtocol.hasAdaptiveAnswerLowerBound
#print axioms Percolation.AdaptiveSiteExploration.hasAdaptiveAnswerLowerBoundOn_finiteAdaptiveSuccessAnswer
#print axioms Percolation.AdaptiveSiteExploration.FiniteFreshOrientedRestartProgram.hasAdaptiveAnswerLowerBound
#print axioms Percolation.AdaptiveSiteExploration.FiniteFreshOrientedRestartProgram.cubicRegion_infinite_probability_pos
#print axioms Percolation.dynamicBlock_restartPow_gt_siteDensity
#print axioms Percolation.dynamicBlock_laterSiteRestartPow_gt_siteDensity
#print axioms Percolation.AdaptiveSiteExploration.measureReal_cond_apply
#print axioms Percolation.AdaptiveSiteExploration.HasAdaptiveAnswerLowerBoundWithin.cond
#print axioms Percolation.SiteExploration.cubicRegionSiteExploration_infinite_inter_probability_pos_of_adaptiveLowerBoundWithin
#print axioms Percolation.AdaptiveSiteExploration.hasAdaptiveAnswerLowerBoundWithin_finiteAdaptiveSuccessAnswer
#print axioms Percolation.AdaptiveSiteExploration.InitializedFinitePartitionedRestartProgram.hasAdaptiveAnswerLowerBoundWithin
#print axioms Percolation.AdaptiveSiteExploration.InitializedFinitePartitionedRestartProgram.cubicRegion_infinite_inter_probability_pos_dynamicBlock
#print axioms Percolation.AdaptiveSiteExploration.InitializedFinitePartitionedRestartProgram.regionHasInfiniteClusterProbability_pos_initializedDynamicBlock
#print axioms Percolation.AdaptiveSiteExploration.InitializedFinitePartitionedRestartProgram.exists_regionCriticalProbability_thickening_le_add_initializedDynamicBlock
#print axioms Percolation.couplingMeasure_real_rootSeedLabelEvent
#print axioms Percolation.rootRadial_probability_gt
#print axioms Percolation.rootRadial_probability_pos
#print axioms Percolation.rootBranchSuccess_inter_rootSeed_gt
#print axioms Percolation.rootRadial_probability_pos_of_branchBounds
#print axioms Percolation.regionAvoidsSeededBoundaryQuadrant_centralBox
#print axioms Percolation.exists_rootReferenceBranchBounds
#print axioms Percolation.rootBranchBounds_of_reference
#print axioms Percolation.exists_rootRadial_probability_pos
#print axioms Percolation.exists_dynamicBlockRestartPackage
#print axioms Percolation.AdaptiveSiteExploration.RootExtensionProgram.pow_mul_radialEvent_le_completionEvent
#print axioms Percolation.AdaptiveSiteExploration.RootExtensionProgram.completionEvent_pos
#print axioms Percolation.AdaptiveSiteExploration.CompletedRootBlockPackage.initialEvent_pos
#print axioms Percolation.AdaptiveSiteExploration.FiniteFreshOrientedRestartProgram.cubicRegion_infinite_probability_pos_dynamicBlock
#print axioms Percolation.mul_measureReal_le_partitionedSuccess
#print axioms Percolation.AdaptiveSiteExploration.PartitionedOrientedRestartStage.success_lower_bound
#print axioms Percolation.AdaptiveSiteExploration.FinitePartitionedOrientedRestartProgram.hasAdaptiveAnswerLowerBound
#print axioms Percolation.AdaptiveSiteExploration.FinitePartitionedOrientedRestartProgram.cubicRegion_infinite_probability_pos_dynamicBlock
#print axioms Percolation.dynamicBlockBaseDensity_add_maxIncrement
#print axioms Percolation.RestartRevealCellIndex.regionVertices_subset_box
#print axioms Percolation.RestartRevealCellIndex.edgeMultiplicity_le
#print axioms Percolation.RestartRevealCellIndex.dynamicThresholdProfile_le
#print axioms Percolation.pairwiseDisjoint_exactRevealCellEvent
#print axioms Percolation.biUnion_filter_exactRevealCellEvent
#print axioms Percolation.AdaptiveSiteExploration.PartitionedOrientedRestartStage.cellUnion_ofFiniteRealization
#print axioms Percolation.restartExploredRegion_subset_box
#print axioms Percolation.cubicMetricBox_subset_restartExploredRegion
#print axioms Percolation.restartExploredRegion_boundary_not_open
#print axioms Percolation.restartExploredRegion_mem_boundaryClosedHistoryEvent
#print axioms Percolation.RestartRevealCellIndex.ofExploredRegion_boundary_closed
#print axioms Percolation.RestartRevealCellIndex.edgeMultiplicity_ofScheduleExploredRegion
#print axioms Percolation.RestartRevealCellIndex.thresholdProfile_ofScheduleExploredRegion
#print axioms Percolation.RestartRevealCellIndex.dynamicThresholdProfile_ofScheduleExploredRegion
#print axioms Percolation.FiniteRevealSchedule.multiplicity_le_stages_length
#print axioms Percolation.FiniteRevealSchedule.incidentDirectionSchedule_stages_length
#print axioms Percolation.FiniteRevealSchedule.incidentDirectionSchedule_hasOverlapBound
#print axioms Percolation.measurable_heterogeneousThresholdConfiguration
#print axioms Percolation.disjoint_cubicRegionInternalEdgesWithinBox_restartEventSupport
#print axioms Percolation.disjoint_orientedInternalEdges_restartSupport
#print axioms Percolation.measurableSet_restartInternalRegionLabelEvent_coordSigma
#print axioms Percolation.restartExploredRegion_eq_iff_internal_and_boundaryClosed
#print axioms Percolation.restartInternalRegionLabelEvent_inter_boundaryClosed
#print axioms Percolation.realizedScheduleRevealCell_eq_iff
#print axioms Percolation.exactRevealCellEvent_eq_past_inter_boundary
#print axioms Percolation.AdaptiveSiteExploration.PartitionedOrientedRestartStage.cellUnion_ofFiniteValidRealization
#print axioms Percolation.RestartRevealCellIndex.isScheduleRealizable_realizedScheduleRevealCell
#print axioms Percolation.RestartRevealCellIndex.realizedScheduleRevealCell_eq_iff_of_isScheduleRealizable
#print axioms Percolation.RestartRevealCellIndex.exactRevealCellEvent_eq_internalPast_inter_boundary_of_isScheduleRealizable
#print axioms Percolation.measurableSet_orientedRestartInternalRegionLabelEvent_coordSigma
#print axioms Percolation.orientedInternalPast_inter_boundary_eq_exactRevealCellEvent
#print axioms Percolation.measurableSet_orientedRestartRevealPastEvent_coordSigma
#print axioms Percolation.disjoint_orientedRestartRevealPastSupport_restartSupport
#print axioms Percolation.AdaptiveSiteExploration.PartitionedOrientedRestartStage.cellUnion_ofOrientedScheduleRealization
#print axioms Percolation.AdaptiveSiteExploration.adaptiveAnswerHistorySupportFrom_append_singleton
#print axioms Percolation.AdaptiveSiteExploration.HasFiniteAnswerSupports.measurableAnswer
#print axioms Percolation.AdaptiveSiteExploration.measurableSet_adaptiveAnswerHistoryEvent_coordSigma
#print axioms Percolation.AdaptiveSiteExploration.HistoryQuerySupportsFresh.disjoint_historySupport
#print axioms Percolation.AdaptiveSiteExploration.finiteAdaptiveSuccessPrefixSupport_succ
#print axioms Percolation.AdaptiveSiteExploration.measurableSet_finiteAdaptiveSuccessPrefix_coordSigma
#print axioms Percolation.AdaptiveSiteExploration.hasFiniteAnswerSupports_finiteAdaptiveSuccessAnswer
#print axioms Percolation.AdaptiveSiteExploration.measurableSet_finiteAdaptiveOuterHistoryEvent_coordSigma
#print axioms Percolation.AdaptiveSiteExploration.OuterHistorySupportsFresh.disjoint_outerHistorySupport
#print axioms Percolation.lss_parameter_selection
#print axioms Percolation.one_sub_le_lss_mixed_factor
#print axioms Percolation.siteDilutionLaw_real_mem
#print axioms Percolation.stochasticallyDominates_siteDilutionLaw
#print axioms Percolation.hasFiniteSequentialLowerBound_iff_event
#print axioms Percolation.setBernoulli_real_retentionPrefixSection_inter_current
#print axioms Percolation.hasLSSRetentionFactorization
#print axioms Percolation.hasFiniteSequentialLowerBound_siteDilutionLaw
#print axioms Percolation.hasFiniteSequentialLowerBound_siteDilutionLaw_of_original
#print axioms Percolation.pairwiseDisjoint_lssNearZero_lssNearOne_lssFar
#print axioms Percolation.lssNearZero_union_lssNearOne_union_lssFar
#print axioms Percolation.lssNearZero_card_add_lssNearOne_card_le
#print axioms Percolation.dilutedConstraintEvent_eq_lss_partition
#print axioms Percolation.retentionClosedOnProductEvent_subset_dilutedConstraintEvent_nearZero
#print axioms Percolation.dependsOn_dilutedConstraint_originalSection
#print axioms Percolation.prod_setBernoulli_real_retentionClosedOnProductEvent
#print axioms Percolation.prod_setBernoulli_real_retentionOpenOnProductEvent
#print axioms Percolation.productMeasure_real_originalClosed_inter_dilutedConstraint_far
#print axioms Percolation.productMeasure_real_originalClosed_inter_dilutedConstraint_far_le
#print axioms Percolation.productMeasure_real_retentionClosed_inter_originalOpen_inter_dilutedConstraint
#print axioms Percolation.productMeasure_real_retentionOpen_inter_originalOpen_inter_dilutedConstraint
#print axioms Percolation.dilutedConstraintEvent_union_true
#print axioms Percolation.pow_mul_measureReal_dilutedConstraint_le_originalOpen_inter
#print axioms Percolation.mul_measureReal_lssReducedHistoryEvent_le_originalOpen
#print axioms Percolation.lssConstraintLowerBound
#print axioms Percolation.dilutedProductPrefixEvent_eq_dilutedConstraintEvent
#print axioms Percolation.hasFiniteSequentialLowerBound_siteDilutionLaw_of_kDependent
#print axioms Percolation.finite_lssDomination
#print axioms Percolation.enumerationPrefixLaw_kDependent
#print axioms Percolation.enumerationPrefixLaw_siteDilutionLaw
#print axioms Percolation.enumerationPrefixLaw_siteDilution_hasFiniteSequentialLowerBound_lss
#print axioms Percolation.lss_finiteCylinder_measureReal_le
#print axioms Percolation.stochasticallyDominates_of_finiteCylinder_measureReal_le
#print axioms Percolation.sequentialLowerBound_stochasticallyDominates
#print axioms Percolation.lss_stochasticallyDominates
#print axioms Percolation.lssDominationDensity_stochasticallyDominates
#print axioms Percolation.exists_lssDominationDensity
#print axioms Percolation.lssDominationDensityUnit_tendsto_one
#print axioms Percolation.monotone_lssDominationDensityUnit
#print axioms Percolation.cubic_enumerationPrefixDependencyGraph_neighbor_card_le
#print axioms Percolation.cubic_lss_finiteCylinder_measureReal_le
#print axioms Percolation.cubic_lss_finiteCylinder_measureReal_le'
#print axioms Percolation.cubic_lss_stochasticallyDominates'
#print axioms Percolation.exists_cubic_lssDominationDensity
#print axioms Percolation.epsilonGoodBlockLaw_lss_finiteCylinder_measureReal_le
#print axioms Percolation.epsilonGoodBlockLaw_lss_stochasticallyDominates
#print axioms Percolation.epsilonGoodBlockLaw_lssDominationDensity_stochasticallyDominates
#print axioms Percolation.exists_lssFiniteCylinderDominationThreshold
#print axioms Percolation.exists_cubic_lssFiniteCylinderDominationThreshold
#print axioms Percolation.siteCrossingProbability_le_epsilonGoodBlockSliceCrossing
#print axioms Percolation.epsilonGoodBlockSliceCrossing_probability_ge_one_sub_exp
#print axioms Percolation.exists_connectionEvent_between_faces_of_mem_goodBlockSliceCrossing
#print axioms Percolation.exists_mem_siteRectangleLeftReachableBoundary_of_not_crossing
#print axioms Percolation.squareStarGraph_degree
#print axioms Percolation.card_squareStarSelfAvoidingCode_le
#print axioms Percolation.setBernoulli_real_closedSquareStarSelfAvoidingWalkEvent_le
#print axioms Percolation.exists_closed_squareStar_path_bottom_top_of_not_crossing
#print axioms Percolation.one_sub_siteSquareRectangleCrossingProbability_le
#print axioms Percolation.siteSquareCrossingProbability_ge_one_sub_exp
#print axioms Percolation.mem_interiorDepth_cubicBoxCrossingEvent_iff
#print axioms Percolation.hasEdgeDisjointCubicBoxCrossings_iff_le_max
#print axioms Percolation.mem_interiorDepth_cubicBoxCrossingEvent_iff_le_max
#print axioms Percolation.one_sub_bernoulliBondMeasure_real_cubicBox_maxCrossings_ge_le
#print axioms Percolation.bernoulliBondMeasure_real_cubicBox_maxCrossings_le_le
#print axioms Percolation.cubicBox_maxCrossings_probability_le_sprinkled_exp_staticTransverse
#print axioms Percolation.pow_mul_exp_neg_le_exp_neg_half_of_cast_le
#print axioms Percolation.staticManyCrossingsDensity_pos
#print axioms Percolation.cubicBox_maxCrossings_probability_le_exp_surface_of_threshold_le
#print axioms Percolation.maxEdgeDisjointCrossings_probability_ge_aligned
#print axioms Percolation.AdaptiveSiteExploration.hasAdaptiveAnswerUpperBoundOn_setBernoulli_of_fresh_support
#print axioms Percolation.FiniteBondExploration.adaptiveDecisionWinEvent_bond_eq_projectedBondHitsTargetEvent
#print axioms Percolation.FiniteBondExploration.setBernoulli_projectedBondHitsTarget_le_directedGreenHitsTarget
#print axioms Percolation.IncomingGreenDomination.card_incomingDartSupport
#print axioms Percolation.IncomingGreenDomination.hasAdaptiveAnswerUpperBoundOn_prefixedAnswer
#print axioms Percolation.IncomingGreenDomination.adaptiveTargetHitEvent_eq_directedGreenHitsTargetEvent
#print axioms Percolation.IncomingGreenDomination.setBernoulli_directedGreenHitsTarget_le_rootedCompletion
#print axioms Percolation.IncomingGreenDomination.setBernoulli_bondHitsTarget_le_rootedCompletion
#print axioms Percolation.SiteExploration.finiteBernoulliProbability_finiteSiteHitsTarget_eq_mul_rooted_completion
#print axioms Percolation.IncomingGreenDomination.density_mul_setBernoulli_bondHitsTarget_le_finiteSiteHitsTarget
#print axioms Percolation.setBernoulli_real_finiteRegionBall_bondHitsTarget_eq_ambient
#print axioms Percolation.regionInfiniteClusterEvent_subset_cubicRegionBondConnectionToSphereEvent
#print axioms Percolation.rootedInfiniteSiteCluster_probability_ge_of_finiteBallHitsSphere_lowerBounds
#print axioms Percolation.siteTheta_densityI_pos_of_regionCriticalProbability_lt
#print axioms Percolation.siteCriticalProbability_lt_one_of_regionCriticalProbability_lt_one
#print axioms Percolation.AdaptiveSiteExploration.FinitePartitionedOrientedRestartProgram.exists_regionCriticalProbability_thickening_le_add_dynamicBlock_of_bondCritical_lt_one
#print axioms Percolation.cubicDirectionOrientationIso_image_cubicBoxEdges_eq
#print axioms Percolation.mem_connectionEventIn_of_finiteBoxOpenGraph_reachable
#print axioms Percolation.sprinkledRestartEvent_subset_regionConnectionToSeededTarget
#print axioms Percolation.exists_inletSeed_connectionToSeededTarget_of_sprinkledRestart
#print axioms Percolation.exists_orientedInletSeed_connectionToSeededTarget_of_realizedCell
#print axioms Percolation.cubicRestartFrameIso_image_seededBoundaryQuadrant_eq_steered
#print axioms Percolation.framedSprinkledRestart_inter_history_gt
#print axioms Percolation.framedSprinkledRestart_inter_past_history_ge
#print axioms Percolation.AdaptiveSiteExploration.PartitionedFramedRestartStage.success_lower_bound
#print axioms Percolation.AdaptiveSiteExploration.PartitionedFramedRestartStage.cellUnion_ofFiniteRealization
#print axioms Percolation.AdaptiveSiteExploration.PartitionedFramedRestartStage.cellUnion_ofFiniteValidRealization
#print axioms Percolation.framedInternalPast_inter_boundary_eq_exactRevealCellEvent
#print axioms Percolation.AdaptiveSiteExploration.PartitionedFramedRestartStage.cellUnion_ofFramedScheduleRealization
#print axioms Percolation.FiniteRevealIntervalProfile.event_eq_withoutClosed_inter_boundaryClosedHistoryEvent
#print axioms Percolation.FramedRestartQuery.boundaryHistoryEvent_eq_physical
#print axioms Percolation.FiniteRevealIntervalProfile.event_eq_withoutClosed_inter_framedBoundaryHistory
#print axioms Percolation.AdaptiveSiteExploration.PartitionedFramedRestartStage.cellUnion_ofIntervalProfileRealization
#print axioms Percolation.firstRadial_updatedLower_apply
#print axioms Percolation.firstRadial_updatedUpper_apply
#print axioms Percolation.firstRadial_updatedLower_le_updatedUpper
#print axioms Percolation.mem_finiteEdgeReachableClosure_iff
#print axioms Percolation.sources_subset_finiteEdgeReachableClosure
#print axioms Percolation.rootRadialExploredEdges_subset_support
#print axioms Percolation.rootRadialReveal_updatedLower_le_updatedUpper
#print axioms Percolation.exploredEdgeStep_mem_firstRadial_updatedProfile
#print axioms Percolation.rootEdgeLineBoundary_subset_rootInitialBoundaryEdges
#print axioms Percolation.rootRadialExploredEdges_mem_updatedProfile
#print axioms Percolation.rootRadialEvent_subset_updatedProfile
#print axioms Percolation.mem_finiteEdgesBelowFamily_iff
#print axioms Percolation.exploredEdgeStepFamily_mem_updatedProfile
#print axioms Percolation.edgeBoundary_sdiff_update_eq
#print axioms Percolation.FiniteEdgeRevealState.next_profile_eq_updatedProfile
#print axioms Percolation.FiniteEdgeRevealState.mem_next_profile
#print axioms Percolation.FiniteEdgeRevealState.mem_run_profile
#print axioms Percolation.FiniteEdgeRevealState.withoutClosed_boundary_support
#print axioms Percolation.FiniteEdgeRevealState.profile_event_eq_past_inter_boundary
#print axioms Percolation.AdaptiveSiteExploration.PartitionedFramedRestartStage.cellUnion_ofFiniteEdgeStateRealization
#print axioms Percolation.AdaptiveSiteExploration.sourceBoundary_sdiff_query_disjoint_restartSupport
#print axioms Percolation.AdaptiveSiteExploration.PartitionedFramedRestartStage.cellUnion_ofSourceEdgeStateRealization
#print axioms Percolation.mem_cubicEdgeBoundary_iff
#print axioms Percolation.cubicEdgeBoundaryWithin_eq_inter
#print axioms Percolation.cubicRegionBoundary_endpointVertices_eq_boundary_inter_restartEventSupport
#print axioms Percolation.disjoint_cubicEdgeBoundary_target_of_endpointVertices
#print axioms Percolation.disjoint_explored_restartEventSupport_of_targetEndpointFresh
#print axioms Percolation.cubicEdgeLineGraph_adj_mapEdgeSet_iff
#print axioms Percolation.cubicEdgeBoundary_image_cubicGraphIso
#print axioms Percolation.SourceFiniteEdgeRevealState.referenceExploredEdges_image
#print axioms Percolation.SourceFiniteEdgeRevealState.framedQuery_physicalBoundaryThreshold
#print axioms Percolation.SourceFiniteEdgeRevealState.framedQuery_boundarySupport_eq_boundary_inter_restartSupport
#print axioms Percolation.SourceFiniteEdgeRevealState.framedQuery_boundarySupport_eq_boundary_inter_restartSupport_of_targetEndpointFresh
#print axioms Percolation.SourceFiniteEdgeRevealState.framedQuery_explored_disjoint_restartSupport_of_targetEndpointFresh
#print axioms Percolation.AdaptiveSiteExploration.PartitionedFramedRestartStage.cellUnion_ofCanonicalSourceEdgeStateRealization
#print axioms Percolation.AdaptiveSiteExploration.PartitionedFramedRestartStage.cellUnion_ofCanonicalSourceEdgeStateRealizationOfTargetEndpointFresh
#print axioms Percolation.SourceFiniteEdgeRevealState.couplingMeasure_real_nonnegativeBoundaryEvent
#print axioms Percolation.SourceFiniteEdgeRevealState.mem_next_profile
#print axioms Percolation.SourceFiniteEdgeRevealState.mem_run_profile
#print axioms Percolation.finiteEdgeReachableClosure_subset_of_closed
#print axioms Percolation.SourceFiniteEdgeRevealState.nextExplored_eq_of_mem_next_profile
#print axioms Percolation.SourceFiniteEdgeRevealState.next_eq_of_mem_next_historyProfile
#print axioms Percolation.SourceFiniteEdgeRevealState.mem_next_historyProfile
#print axioms Percolation.SourceFiniteEdgeRevealState.finite_range_next
#print axioms Percolation.SourceFiniteEdgeRevealState.next_historyProfile_event_subset_historyProfile_event
#print axioms Percolation.activeCubicEdgeBoundary_rootInitial_eq
#print axioms Percolation.sourceExploredEdgeStep_rootInitial_eq
#print axioms Percolation.rootRadialEvent_mem_postRadialSourceProfile
#print axioms Percolation.rootEdgeLineBoundary_eq_rootInitialBoundaryEdges
#print axioms Percolation.rootRadialEvent_subset_postRadialProfile
#print axioms Percolation.laterSiteDirectionOrder_length
#print axioms Percolation.laterSiteSupportSchedule_hasOverlapBound
#print axioms Percolation.rootExtensionSupportSchedule_hasOverlapBound
#print axioms Percolation.exists_rootRadialSelectedSeed_of_success
#print axioms Percolation.exists_rootRadialSeedProfile_of_mem
#print axioms Percolation.seedCenter_axis_eq_of_boxWithinBoundaryLayer
#print axioms Percolation.seedCenter_transverse_bounds_of_boxWithinBoundaryLayer
#print axioms Percolation.RootRadialSeedProfile.postRadialFrame_apply
#print axioms Percolation.RootRadialSeedProfile.postRadialRestartRegion_subset_endpointBoxes
#print axioms Percolation.seedConnectionSupport_subset_cubicBoxEdges_wide
#print axioms Percolation.endpoint_mem_seededBoundaryTargetSupport_coord_ge
#print axioms Percolation.restartEventSupport_subset_seedConnectionSupport
#print axioms Percolation.rootRadialEdgeSupport_subset_wideBox
#print axioms Percolation.rootPostRadialSourceEdgeState_targetEndpointFresh
#print axioms Percolation.rootPostRadial_framedQuery_boundarySupport_eq
#print axioms Percolation.rootPostRadial_framedQuery_explored_disjoint_restartSupport
#print axioms Percolation.seededBoundaryLayerRegion_transverse_bounds
#print axioms Percolation.endpoint_mem_seedConnectionSupport_transverse_bounds
#print axioms Percolation.endpoint_mem_restartEventSupport_transverse_bounds
#print axioms Percolation.RootRadialSeedProfile.postRadial_referenceCoord_lt_of_ne
#print axioms Percolation.RootRadialSeedProfile.postRadialRestartSupport_endpoint_coord_lt_of_ne
#print axioms Percolation.RootRadialSeedProfile.referenceEndpoint_coord_lt_next_of_ne
#print axioms Percolation.SourceFiniteEdgeRevealState.nextExplored_subset_explored_union_stageRegion
#print axioms Percolation.rootPostRadialExtensions_prefix_targetEndpointFresh
#print axioms Percolation.rootPostRadialExtensions_prefix_framedQuery_boundarySupport_eq
#print axioms Percolation.rootPostRadialExtensions_prefix_explored_disjoint_restartSupport
#print axioms Percolation.SourceFiniteEdgeRevealState.couplingMeasure_real_nonnegativeCouplingEvent
#print axioms Percolation.coe_budgetedRootExtensionThresholdPolicy_of_hasIncrementBudget
#print axioms Percolation.lower_le_budgetedRootExtensionThresholdPolicy
#print axioms Percolation.RootRadialSeedProfile.mem_runPostRadialExtensions_profile
#print axioms Percolation.RootRadialSeedProfile.finite_range_runPostRadialExtensions
#print axioms Percolation.RootRadialSeedProfile.runPostRadialExtensions_eq_of_mem_historyProfile
#print axioms Percolation.rootRadialEvent_mem_completedRootExtensionProfile
#print axioms Percolation.rootRadialEvent_mem_completedRootExtensionProfile_of_mem_nonnegativeCouplingEvent
#print axioms Percolation.rootRadialEvent_mem_completedRootExtensionHistoryProfile
#print axioms Percolation.RootRadialSeedProfile.finite_range_rootExtensionPrefixState
#print axioms Percolation.RootRadialSeedProfile.disjoint_historyProfile_of_mem_prefixStateRange
#print axioms Percolation.RootRadialSeedProfile.rootRadialEvent_inter_nonnegative_subset_prefixHistory
#print axioms Percolation.intervalProfile_event_eq_exactRevealCellEvent
#print axioms Percolation.AdaptiveSiteExploration.RootRadialSeedProfile.partitionedRootExtensionStage_cellUnion
#print axioms Percolation.AdaptiveSiteExploration.RootRadialSeedProfile.partitionedRootExtensionStageOfProfilePartition_cellUnion
#print axioms Percolation.AdaptiveSiteExploration.RootRadialSeedProfile.partitionedRootExtensionStageOfReachableHistory_cellUnion
#print axioms Percolation.FiniteRevealIntervalProfile.refineAtThreshold_event_eq
#print axioms Percolation.FiniteRevealIntervalProfile.mem_refineAtThreshold_realized
#print axioms Percolation.sprinkledRestartEvent_congr_of_thresholdIffOn_restartEventSupport
#print axioms Percolation.rootRadialEvent_congr_of_labelsBelow_rootRadialEdgeSupport
#print axioms Percolation.rootRadialSelectedSeed_congr_of_labelsBelow_rootRadialEdgeSupport
#print axioms Percolation.RootRadialSeedProfile.mem_realizedRootExtensionRefinedCell_profile
#print axioms Percolation.RootRadialSeedProfile.refinedRootExtensionPrefixHistory_subset
#print axioms Percolation.RootRadialSeedProfile.refinedPrefixHistory_inter_nonnegative_eq
#print axioms Percolation.RootRadialSeedProfile.pairwiseDisjoint_refinedRootExtensionPrefixHistory
#print axioms Percolation.RootRadialSeedProfile.stableRootExtensionPrefixHistory_eq
#print axioms Percolation.RootRadialSeedProfile.pairwiseDisjoint_stableRootExtensionPrefixHistory
#print axioms Percolation.AdaptiveSiteExploration.RootRadialSeedProfile.partitionedRootExtensionStageOfStableHistory_cellUnion
#print axioms Percolation.rootSeedLabelEvent_of_mem_rootPostRadialSourceHistoryProfile
#print axioms Percolation.RootRadialSeedProfile.rootSeedLabelEvent_of_mem_prefixHistoryProfile
#print axioms Percolation.walkEdgeFinset_subset_finiteEdgeReachableClosure_of_incident
#print axioms Percolation.cubicBoxEdges_subset_finiteEdgeReachableClosure_of_incident
#print axioms Percolation.rootBranch_mapEdgeSet_mem_rootInitialBoundaryEdges_iff
#print axioms Percolation.rootBranch_mapEdgeSet_mem_rootRadialExteriorEdges_of_restartSupport
#print axioms Percolation.label_lt_incremented_of_mem_rootPostRadialSourceHistoryProfile
#print axioms Percolation.label_lt_density_of_mem_rootPostRadialSourceHistoryProfile
#print axioms Percolation.exists_rootBranchExploredCertificate_of_success
#print axioms Percolation.rootBranchSuccessEvent_of_mem_rootPostRadialSourceHistoryProfile
#print axioms Percolation.rootRadialEvent_of_mem_rootPostRadialSourceHistoryProfile
#print axioms Percolation.RootRadialSeedProfile.rootRadialEvent_of_mem_prefixHistoryProfile
#print axioms Percolation.RootRadialSeedProfile.rootRadialEvent_inter_nonnegative_subset_stablePrefixHistory
#print axioms Percolation.RootRadialSeedProfile.stablePrefixHistory_inter_nonnegative_eq_rootRadial
#print axioms Percolation.SourceFiniteEdgeRevealState.label_lt_incremented_of_mem_nextHistoryProfile
#print axioms Percolation.SourceFiniteEdgeRevealState.label_lt_density_of_mem_nextHistoryProfile
#print axioms Percolation.SourceFiniteEdgeRevealState.mapEdgeSet_mem_sourceStageExterior_of_restartSupport
#print axioms Percolation.SourceFiniteEdgeRevealState.framedSuccessEvent_of_mem_nextHistoryProfile
#print axioms Percolation.RootRadialSeedProfile.runPostRadialExtensions_append
#print axioms Percolation.RootRadialSeedProfile.runPostRadialExtensionSuccesses_append
#print axioms Percolation.RootRadialSeedProfile.runPostRadialExtensionSuccesses_of_mem_historyProfile
#print axioms Percolation.RootRadialSeedProfile.rootExtensionPrefixState_succ
#print axioms Percolation.RootRadialSeedProfile.rootExtensionPrefixSuccessEvent_zero
#print axioms Percolation.RootRadialSeedProfile.rootExtensionPrefixSuccessEvent_of_mem_historyProfile
#print axioms Percolation.RootRadialSeedProfile.rootExtensionPrefixSuccess_inter_nonnegative_subset_stableHistory
#print axioms Percolation.RootRadialSeedProfile.stableHistory_inter_nonnegative_eq_rootExtensionPrefixSuccess
#print axioms Percolation.measureReal_inter_eq_of_measureReal_eq_one
#print axioms Percolation.AdaptiveSiteExploration.PartitionedFramedRestartStage.success_lower_bound_of_inter_support_eq
#print axioms Percolation.RevealThresholdUpdateData.updatedLower_le_of_le
#print axioms Percolation.RevealThresholdUpdateData.coe_updatedLower_le_of_le
#print axioms Percolation.SourceFiniteEdgeRevealState.coe_next_lower_le_of_le
#print axioms Percolation.coe_rootPostRadialSourceEdgeState_lower_le_max
#print axioms Percolation.coe_budgetedRootExtensionThresholdPolicy_le_add
#print axioms Percolation.RootRadialSeedProfile.coe_runPostRadialExtensions_budgeted_lower_le
#print axioms Percolation.RootRadialSeedProfile.coe_rootExtensionPrefixState_budgeted_lower_le
#print axioms Percolation.RootRadialSeedProfile.rootExtensionPrefixState_hasIncrementBudget
#print axioms Percolation.RootRadialSeedProfile.budgetedPolicy_addsOnPrefixes
#print axioms Percolation.RootRadialSeedProfile.mem_rootExtensionPrefixSuccessEvent_succ_iff
#print axioms Percolation.AdaptiveSiteExploration.RootRadialSeedProfile.rootExtensionPrefixSuccessStage_cellUnion_inter_nonnegative_eq
#print axioms Percolation.AdaptiveSiteExploration.RootRadialSeedProfile.rootExtensionPrefixSuccessStage_successEvent_inter_nonnegative_eq
#print axioms Percolation.AdaptiveSiteExploration.RootRadialSeedProfile.rootExtensionPrefixSuccess_measure_step
#print axioms Percolation.AdaptiveSiteExploration.RootRadialSeedProfile.nonempty_stableRootExtensionPrefixStateIndex_of_measure_pos
#print axioms Percolation.AdaptiveSiteExploration.RootRadialSeedProfile.pow_two_mul_mul_rootRadialEvent_le_budgetedPrefixSuccess
#print axioms Percolation.cubicRegionBoundaryEdgesWithinBox_inter_cubicMetricBox
#print axioms Percolation.cubicRegionExteriorEdgesWithinBox_inter_cubicMetricBox
#print axioms Percolation.restartEventSupport_inter_cubicMetricBox
#print axioms Percolation.sprinkledRestartEvent_inter_cubicMetricBox
#print axioms Percolation.regionAvoidsSeededBoundaryQuadrant_of_coord_add_one_lt
#print axioms Percolation.FramedRestartQuery.uniformRestartBounds_of_croppedRegion
#print axioms Percolation.cubicMetricBox_subset_cubicEdgeEndpointVertices_cubicBoxEdges
#print axioms Percolation.mem_sprinkledRestartEvent_iff_exists_mixedRestartSeedWitness
#print axioms Percolation.selectedMixedRestartSeedWitness_eq_some_of_success
#print axioms Percolation.exists_rootRadialMixedSelectedSeed_of_success
#print axioms Percolation.exists_rootRadialMixedSeedProfile_of_mem
#print axioms Percolation.exists_mixedRadialEvent_measure_pos_of_rootRadialEvent_measure_pos
#print axioms Percolation.RootRadialSeedProfile.mixedPrefixCell_uniformRestart
#print axioms Percolation.AdaptiveSiteExploration.RootRadialSeedProfile.mixedExtensionPrefixSuccess_measure_step
#print axioms Percolation.AdaptiveSiteExploration.RootRadialSeedProfile.mixedExtensionCompletion_measure_pos
#print axioms Percolation.SourceFiniteEdgeRevealState.mixedWitness_exploredCertificate
#print axioms Percolation.SourceFiniteEdgeRevealState.mixedWitness_of_mem_nextHistoryProfile
#print axioms Percolation.SourceFiniteEdgeRevealState.selectedMixedRestartSeedWitness_eq_of_mem_nextHistoryProfile
#print axioms Percolation.RootRadialSeedProfile.exists_rootOutgoingSeed_of_completion
#print axioms Percolation.exists_rootRadialSeedProfile_with_steering_of_mem
#print axioms Percolation.exists_framedInletSeed_connectionToSeededTarget_of_sprinkledRestart
#print axioms Percolation.cubicRestartFrameIso_mem_inletCompensatingBoundaryRegion
#print axioms Percolation.restartConnectedSeedWitnesses_nonempty_of_inlet_connection
#print axioms Percolation.selectedRestartSeedWitness_eq_some_of_inlet_connection
#print axioms Percolation.exists_selectedFramedRestartSeed_of_sprinkledRestart
#print axioms Percolation.measurableSet_selectedRestartSeedWitnessLabelEvent_coordSigma
#print axioms Percolation.realizedSeededRestartRevealCell_eq_cell_iff
#print axioms Percolation.SeededRestartRevealCellIndex.nextPhysicalSeedCenter_of_selected
#print axioms Percolation.LaterSiteRuntime.finite_range_step_of_finite_range
#print axioms Percolation.LaterSiteRuntime.finite_range_runFrom
#print axioms Percolation.LaterSiteRuntime.runFrom_eq_of_mem_historyProfile
#print axioms Percolation.LaterSiteRuntime.succeedsFrom_of_mem_historyProfile
#print axioms Percolation.LaterSiteRuntime.outgoingSeed_isMixed_of_succeeds
#print axioms Percolation.LaterSiteRuntime.finite_range_prefixRuntime
#print axioms Percolation.LaterSiteRuntime.stablePrefixHistory_eq
#print axioms Percolation.LaterSiteRuntime.pairwiseDisjoint_stablePrefixRuntimeHistory
#print axioms Percolation.LaterSiteRuntime.selectedTarget_connected_of_succeedsFrom
#print axioms Percolation.RootRadialSeedProfile.completedRootExtensionState_rootedOpen
#print axioms Percolation.RootRadialSeedProfile.completedRootExtensionState_rootedOpen_of_prefixBounds
#print axioms Percolation.RootRadialSeedProfile.finalThresholdBoundedOnPrefixes_budgeted
#print axioms Percolation.LaterSiteRuntime.rootedOpen_runFrom_of_prefixBounds
#print axioms Percolation.DynamicBlockHistoryReplay.replay_source_rootedOpen
#print axioms Percolation.DynamicBlockHistoryReplay.replay_source_rootedOpen_of_prefixBounds
#print axioms Percolation.DynamicBlockHistoryReplay.replayFrom_source_rootedOpen_of_prefixBounds
#print axioms Percolation.DynamicBlockHistoryReplay.ReplayProgramStageCertificates.outgoing_physicalCenter_connected_replay
#print axioms Percolation.DynamicBlockHistoryReplay.ReplayProgramFinalThresholdCertificate.replay_source_rootedOpen
#print axioms Percolation.DynamicBlockHistoryReplay.ReplayProgramFinalThresholdCertificate.outgoing_physicalCenter_connected_replay
#print axioms Percolation.AdaptiveSiteExploration.exists_acceptance_step_of_mem_occupiedLimit
#print axioms Percolation.AdaptiveSiteExploration.exists_realized_suffix_stateAfter
#print axioms Percolation.AdaptiveSiteExploration.stateAfter_drop_initialHistory_mem_adaptiveAnswerHistoryEvent
#print axioms Percolation.AdaptiveSiteExploration.InitializedPartitionedAdaptiveProgram.regionHasInfiniteClusterProbability_pos_initializedAdaptiveProgram_withAnchors
#print axioms Percolation.AdaptiveSiteExploration.InitializedPartitionedAdaptiveProgram.exists_regionCriticalProbability_thickening_le_add_initializedAdaptiveProgram_withAnchors
#print axioms Percolation.hasInfiniteOpenClusterInVertices_of_infinite_anchor_connections_finiteFibers
#print axioms Percolation.finite_preimage_of_anchor_mem_siteBox
#print axioms Percolation.grimmettMarstrandCenteredBox_subset_thickening
#print axioms Percolation.SiteExploration.stateAfter_eq_replayState_drop_initialHistory
#print axioms Percolation.SiteExploration.exists_acceptedReplayQuery_of_mem_occupiedLimit
#print axioms Percolation.DynamicBlockHistoryReplay.AcceptedReplayQuery.allPriorAdmissible
#print axioms Percolation.AdaptiveSiteExploration.InitializedPartitionedAdaptiveProgram.regionHasInfiniteClusterProbability_pos_initializedAdaptiveProgram_withFiniteFiberAnchors
#print axioms Percolation.AdaptiveSiteExploration.InitializedPartitionedAdaptiveProgram.exists_regionCriticalProbability_thickening_le_add_initializedAdaptiveProgram_withLocalAnchors
#print axioms Percolation.grimmettMarstrandBondCenter_mem_destinationBox
#print axioms Percolation.grimmettMarstrandHalfwayBox_subset_destinationBox
#print axioms Percolation.DynamicBlockHistoryReplay.ReplayProgramStageCertificates.outgoingSeedsInHalfwayBoxes_replay
#print axioms Percolation.DynamicBlockHistoryReplay.ReplayProgramStageCertificates.supportsWithin_thickening_replay
#print axioms Percolation.DynamicBlockHistoryReplay.ReplayProgramFinalThresholdCertificate.replay_source_rootedOpenWithin_thickening
#print axioms Percolation.DynamicBlockHistoryReplay.ReplayProgramFinalThresholdCertificate.outgoing_physicalCenter_connectedWithin_thickening_replay
#print axioms Percolation.DynamicBlockHistoryReplay.exists_localAcceptedAnchor
#print axioms Percolation.DynamicBlockHistoryReplay.localAcceptedAnchor_spec
#print axioms Percolation.DynamicBlockHistoryReplay.regionHasInfiniteClusterProbability_pos_of_replayCertificates
#print axioms Percolation.DynamicBlockHistoryReplay.exists_regionCriticalProbability_thickening_le_add_of_replayCertificates
#print axioms Percolation.ncard_grimmettMarstrandInfluenceSites_le
#print axioms Percolation.DynamicBlockHistoryReplay.replay_source_lower_le_spatialBudget
#print axioms Percolation.DynamicBlockHistoryReplay.runtimePrefix_lower_add_le_replayThresholdCap
#print axioms Percolation.DynamicBlockHistoryReplay.runtimePrefix_budgetedPolicy_eq_add
#print axioms Percolation.DynamicBlockHistoryReplay.runtime_finalThresholdBoundedOnPrefixes_budgeted
#print axioms Percolation.DynamicBlockHistoryReplay.replayProgramFinalThresholdCertificate_budgeted
