import Percolation.TheoremsForExperiment
import Percolation.Planar.BRCrossingExtension
import Percolation.Planar.RSWEndpointSplit
import Percolation.Planar.RSWStoppedContact

open Percolation

#print axioms Percolation.half_le_grimmettRectangleCrossingProbability_even
#print axioms Percolation.one_eighth_le_rswSquareCrossingProbability_half
#print axioms Percolation.one_sixteenth_le_rswSquareCrossingProbability_half
#print axioms Percolation.brExtensionCrossingProbability_mul_rswSquare_div_two_le_sourceX_filledHull
#print axioms Percolation.one_sub_sqrt_extensionCrossing_mul_rswSquare_le_sourceX_filledHull
#print axioms Percolation.one_sub_sqrt_rswSquare_mul_rswSquare_le_sourceX
#print axioms Percolation.one_sub_sqrt_rswSquare_le_upperStartCrossingProbability
#print axioms Percolation.one_sub_sqrt_rswSquare_le_brStoppedLowerContactProbability
#print axioms Percolation.grimmett_theorem_3_7
#print axioms Percolation.grimmett_theorem_11_70
#print axioms Percolation.duminilCopin_proposition_2_14
